### ISSUE TITLE
After loading 2-3 different pathways, subsequent selections will always give me an infinite spinner

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2509]

**Comment by fdlk** [comment]
It is not as reproducible as that, I'm afraid. But yes, the pathway tool does manage to get into a state with the infinite spinner. It didn't do this before the REST API was used, so chances are that it's an issue there.

**Comment by fdlk** [comment]
created a thread dump and it is an issue where the REST API's HTTP pool connections are not properly released:

```
"qtp189888904-197" #197 prio=5 os_prio=31 tid=0x00007fd893ebb000 nid=0x6123 waiting on condition [0x000000011d67a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007a0f4baf0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:133)
	at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:282)
	at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:64)
	at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:177)
	at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:170)
	at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:102)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:244)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:231)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:173)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.molgenis.wikipathways.client.WikiPathwaysRESTBindingStub.getPathwayAs(WikiPathwaysRESTBindingStub.java:337)
	at org.molgenis.pathways.service.WikiPathwaysService.lambda$3(WikiPathwaysService.java:52)
	at org.molgenis.pathways.service.WikiPathwaysService$$Lambda$47/1561068717.applyThrows(Unknown Source)
	at org.molgenis.pathways.service.RemoteFunction.apply(RemoteFunction.java:19)
	at org.molgenis.pathways.service.CacheFactory$1.load(CacheFactory.java:44)
[...]
```
