### ISSUE TITLE
StackOverflowError when uploading an Excel sheet with a lot of rows with formulas

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2691]
### How to Reproduce
1. Import [it_emx_formulas.xlsx](https://github.com/molgenis/molgenis/files/1966279/it_emx_formulas.xlsx) using the 'Advanced data import' plugin

### Expected behavior
- Import completes successfully. Alternatively the importer displays an error mentioning that the input files cannot be imported because it contains too many formulas.

### Observed behavior
- Import spinner keeps spinning indefinitely
- Logs display
```
Exception in thread "pool-4-thread-1" java.lang.StackOverflowError
	at java.util.regex.Pattern$Curly.match(Pattern.java:4229)
	at java.util.regex.Pattern$Ques.match(Pattern.java:4184)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719)
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4281)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4236)
	at java.util.regex.Pattern$Ques.match(Pattern.java:4184)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4606)
	at java.util.regex.Matcher.match(Matcher.java:1270)
	at java.util.regex.Matcher.matches(Matcher.java:604)
	at org.apache.poi.ss.formula.FormulaParser.parseSimpleRangePart(FormulaParser.java:1036)
	at org.apache.poi.ss.formula.FormulaParser.parseRangeable(FormulaParser.java:481)
	at org.apache.poi.ss.formula.FormulaParser.parseRangeExpression(FormulaParser.java:322)
	at org.apache.poi.ss.formula.FormulaParser.parseSimpleFactor(FormulaParser.java:1540)
	at org.apache.poi.ss.formula.FormulaParser.percentFactor(FormulaParser.java:1498)
	at org.apache.poi.ss.formula.FormulaParser.powerFactor(FormulaParser.java:1485)
	at org.apache.poi.ss.formula.FormulaParser.Term(FormulaParser.java:1858)
	at org.apache.poi.ss.formula.FormulaParser.additiveExpression(FormulaParser.java:1986)
	at org.apache.poi.ss.formula.FormulaParser.concatExpression(FormulaParser.java:1970)
	at org.apache.poi.ss.formula.FormulaParser.comparisonExpression(FormulaParser.java:1927)
	at org.apache.poi.ss.formula.FormulaParser.intersectionExpression(FormulaParser.java:1900)
	at org.apache.poi.ss.formula.FormulaParser.unionExpression(FormulaParser.java:1880)
	at org.apache.poi.ss.formula.FormulaParser.parse(FormulaParser.java:2028)
	at org.apache.poi.ss.formula.FormulaParser.parse(FormulaParser.java:170)
	at org.apache.poi.xssf.usermodel.XSSFEvaluationWorkbook.getFormulaTokens(XSSFEvaluationWorkbook.java:85)
	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:276)
	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateReference(WorkbookEvaluator.java:722)
	at org.apache.poi.ss.formula.SheetRefEvaluator.getEvalForCell(SheetRefEvaluator.java:48)
	at org.apache.poi.ss.formula.SheetRangeEvaluator.getEvalForCell(SheetRangeEvaluator.java:74)
	at org.apache.poi.ss.formula.LazyRefEval.getInnerValueEval(LazyRefEval.java:39)
	at org.apache.poi.ss.formula.eval.OperandResolver.chooseSingleElementFromRef(OperandResolver.java:179)
	at org.apache.poi.ss.formula.eval.OperandResolver.getSingleValue(OperandResolver.java:62)
	at org.apache.poi.ss.formula.eval.TwoOperandNumericOperation.singleOperandEvaluate(TwoOperandNumericOperation.java:29)
	at org.apache.poi.ss.formula.eval.TwoOperandNumericOperation.evaluate(TwoOperandNumericOperation.java:35)
	at org.apache.poi.ss.formula.functions.Fixed2ArgFunction.evaluate(Fixed2ArgFunction.java:33)
	at org.apache.poi.ss.formula.OperationEvaluatorFactory.evaluate(OperationEvaluatorFactory.java:119)
	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateFormula(WorkbookEvaluator.java:514)
	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:278)
	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateReference(WorkbookEvaluator.java:722)
	at org.apache.poi.ss.formula.SheetRefEvaluator.getEvalForCell(SheetRefEvaluator.java:48)
	at org.apache.poi.ss.formula.SheetRangeEvaluator.getEvalForCell(SheetRangeEvaluator.java:74)
	at org.apache.poi.ss.formula.LazyRefEval.getInnerValueEval(LazyRefEval.java:39)
	at org.apache.poi.ss.formula.eval.OperandResolver.chooseSingleElementFromRef(OperandResolver.java:179)
	at org.apache.poi.ss.formula.eval.OperandResolver.getSingleValue(OperandResolver.java:62)
	at org.apache.poi.ss.formula.eval.TwoOperandNumericOperation.singleOperandEvaluate(TwoOperandNumericOperation.java:29)
```

**Comment by mswertz** [comment]
we first must revisit user for these formulas

**Comment by Mark-de-Haan** [comment]
@tommydeboer Is this still an issue? @mswertz Are there users for this? Else maybe wontfix?

**Comment by Mark-de-Haan** [comment]
@tommydeboer  Can not find test file :(
