### ISSUE TITLE
model registry does not work for normal user

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#2744]
Added a user
gave the all users group permissions on the modelregistry
gave the all users group permissions on some entities

when logging in with this user and clicking the menu item an error is shown

**Comment by Mark-de-Haan** [comment]
This goes wrong because a user does not have permission on package and entity tables.
Quick fix is to set permission to read only for that user.

**Comment by fdlk** [comment]
The data that gets read from package and entity tables is cached in POJO's in the MetaDataService. So a user shouldn't need read access on those entities.

**Comment by fdlk** [comment]
what error / stack trace?

**Comment by Mark-de-Haan** [comment]
Caused by: 
org.molgenis.data.MolgenisDataAccessException: No READ permission on entity packages
	at org.molgenis.util.SecurityDecoratorUtils.validatePermission(SecurityDecoratorUtils.java:16)
	at org.molgenis.data.RepositorySecurityDecorator.findOne(RepositorySecurityDecorator.java:70)
	at org.molgenis.data.support.DataServiceImpl.findOne(DataServiceImpl.java:158)
	at org.molgenis.data.semantic.UntypedTagService.getTagsForPackage(UntypedTagService.java:156)
	at org.molgenis.standardsregistry.StandardsRegistryController.getTagsForPackage(StandardsRegistryController.java:321)
	at org.molgenis.standardsregistry.StandardsRegistryController.search(StandardsRegistryController.java:164)

**Comment by bartcharbon** [comment]
Search is not working for a normal user.
No stacktrace in the log, just an Error in the user interface
