### ISSUE TITLE
While the Importer is asynchronous importing, going to the data explorer will throw an error

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2752]
## Tested on: Molgenis01, Chrome ##

- Upload a large model from the model registry (like Chado or BioSample)
- Go through the import wizard untill you see the loading spinner
- Go to the Data explorer plugin
- Select an entity

Expected: I can view entities without any problems
Result: I get an error saying: Message:null and the table is not shown

Console log:
Request URL:https://molgenis01.target.rug.nl/menu/main/dataexplorer/module/data?entity=AttributeMapping&_=1428491671519
Request Method:GET
Status Code:500 Internal Server Error

**Comment by fdlk** [comment]
Server side:
```
19:07:43.104 [qtp1945718600-795] ERROR o.m.d.c.DataExplorerController - null
java.util.ConcurrentModificationException: null
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1207) ~[na:1.8.0_40]
	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1261) ~[na:1.8.0_40]
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:646) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-16.0.1.jar:na]
	at org.molgenis.dataexplorer.controller.DataExplorerController.getGenomeBrowserEntities(DataExplorerController.java:373) ~[classes/:na]
	at org.molgenis.dataexplorer.controller.DataExplorerController.getModule(DataExplorerController.java:216) ~[classes/:na]
```
