### ISSUE TITLE
Sorting on the ID attribute in the dataexplorer throws an error

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#2754]
## Tested on: Molgenis01, Chrome
- Go to the data explorer and view TypeTest
- Try to sort on the id column

Expected: The column is sorted
Result: An error is thrown and the pager breaks

`Error! Failed to execute phase [query_fetch], all shards failed; shardFailures {[EN447yWHTH-6jJpbV3UCvA][molgenis][0]: QueryPhaseExecutionException[[molgenis][0]: query[ConstantScore(cache(+_type:TypeTest +org.elasticsearch.index.search.nested.NonNestedDocsFilter@9f3b818d))],from[0],size[18],sort[]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }`

**Comment by Mark-de-Haan** [comment]
Dropped database and index, reimported. Error is gone.

**Comment by dennishendriksen** [comment]
Problem still exists with same data set.

**Comment by dennishendriksen** [comment]
Cannot reproduce, sorting on id column in TypeTest data set works.

**Comment by bartcharbon** [comment]
Reproduced again in 1.12 RC with Safari

**Comment by dennishendriksen** [comment]
Cannot reproduce with exactly the same MOLGENIS version, after importing ```molgenis-app\src\test\resources\xls\emx_all_datatypes.xlsx``` in a clean database. Editing a row, deleting a row and repeating the test also does not result in the error.

**Comment by jjettenn** [comment]
First I didn't had problems with reproducing this problem. When I dropped my database and index it worked. Strange!

To reproduce this issue you will need two data sets:
1. app\src\test\resources\xls\emx_all_datatypes.xlsx
2. [emx_all_datatypes_experiment.xlsx](https://github.com/molgenis/molgenis/files/40626/emx_all_datatypes_experiment.xlsx)

The problem is that the id field has the same name but different data type inside the same mapping.
1. id: integer (org_molgenis_test_TypeTest)
2. id: string (test_molgenis_test_TypetTest)

Section: Avoiding Type Gotchas
1. "The fact that documents of different types can be added to the same index introduces some unexpected complications." 
2."To ensure that you don’t run into these conflicts, it is advisable to ensure that fields with the same name are mapped in the same way in every type in an index."
(See doc: https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping.html)

W.I.P

**Comment by jjettenn** [comment]
When we have to field with different data types, int and string, this error occurs.
It is possible to use 
https://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html

**Comment by jjettenn** [comment]
W.I.P

**Comment by dennishendriksen** [comment]
Mapping types are used to group fields, but the fields in each mapping type are not independent of each other. Fields with:
- the same name
- in the same index
- in different mapping types
- map to the same field internally,
- and must have the same mapping.

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#field-conflicts

The percect solution is to have unique field names, either UUIDs or by using the type name (and index name?) as a prefix.

**Comment by tommydeboer** [comment]
After the migration I get this stacktrace and I can't start the app:

```
Caused by: java.sql.SQLException: Out of sort memory, consider increasing server sort buffer size
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1086) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4169) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:928) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:2053) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3543) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:491) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3245) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2413) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2836) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2825) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2313) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:703) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644) ~[spring-jdbc-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 82 common frames omitted
```

**Comment by jjettenn** [comment]
Also related to:
