### ISSUE TITLE
'Execution failed' when exceeding max length of text field in form

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2797]
### To reproduce
Paste a lot of text in a text field in a form. Tried 'Hallo ' repeated a lot of times, and 80000 bytes of Lorem ipsum (http://nl.lipsum.com/)

### Expected
Text is truncated and updates without problems.

### Actual
```Error! Failed execution``` in MOLGENIS.

Stacktrace:
```
Caused by: java.lang.IllegalArgumentException: Document contains at least one immense term in field="xtextnillable.raw" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[72, 97, 108, 108, 111, 32, 72, 97, 108, 108, 111, 32, 72, 97, 108, 108, 111, 32, 72, 97, 108, 108, 111, 32, 72, 97, 108, 108, 111, 32]...', original message: bytes can be at most 32766 in length; got 39936
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:687) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:359) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:318) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:282) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:416) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1341) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	at org.elasticsearch.index.engine.internal.InternalEngine.innerIndex(InternalEngine.java:601) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.index.engine.internal.InternalEngine.index(InternalEngine.java:522) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.index.shard.service.InternalIndexShard.index(InternalIndexShard.java:425) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:193) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419) ~[elasticsearch-1.4.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_31]
	... 1 common frames omitted
Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 39936
	at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:151) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:663) ~[lucene-core-4.10.3.jar:4.10.3 1644336 - mark - 2014-12-10 00:28:00]
	... 14 common frames omitted
```

**Comment by mswertz** [comment]
is it simple to just add an warning message as part of validation?

**Comment by dennishendriksen** [comment]
Reason is that text fields are also stored in a not-analyzed way to accommodate sorting and wildcard queries. When a field is stored in a not-analyzed way the text is considers as one token thus exceeding the maximum token size of Elasticsearch.  A solution is to remove line 209-110 in org.molgenis.data.elasticsearch.index.MappingsBuilder that configure the non-analyzed field. Alternatively we could only index the first 100 bytes for sorting and not support wildcard queries (normal search will still work).

**Comment by Mark-de-Haan** [comment]
Fixed with react forms
