### ISSUE TITLE
StackOverflowError when selecting 'entities' or 'attributes' entity in Data Explorer

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#2891]
### To reproduce:
Open the 'entities' or 'attributes' entity in the entity selection drop down in the data explorer.

### Result:
```
Caused by: 
java.lang.StackOverflowError
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4279)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
	at java.util.regex.Pattern$Start.match(Pattern.java:3461)
	at java.util.regex.Matcher.search(Matcher.java:1248)
	at java.util.regex.Matcher.find(Matcher.java:664)
	at java.util.Formatter.parse(Formatter.java:2549)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2927)
	at org.molgenis.data.rest.Href.concatMetaAttributeHref(Href.java:68)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:62)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
	at org.molgenis.data.rest.AttributeMetaDataResponse.<init>(AttributeMetaDataResponse.java:113)
	at org.molgenis.data.rest.EntityMetaDataResponse.<init>(EntityMetaDataResponse.java:89)
etc.
```

**Comment by tommydeboer** [comment]
Also happens for attributes entity

**Comment by dennishendriksen** [comment]
Related to #2900?
