### ISSUE TITLE
Elasticsearch index not recreated on restart

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#2917]
Reproduce:
1) Stop application
2) Remove the ElasticSearch index from ~/.molgenis/omx/data/elasticsearch
3) Start application
Expected: Elasticsearch index is recreated on startup
Actual: Error on startup:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webAppConfig': Invocation of init method failed; nested exception is org.springframework.jdbc.BadSq
lGrammarException: StatementCallback; bad SQL grammar [SELECT `attributes` FROM `attributes_attributes` WHERE `identifier` = '<identifier>' ORDER BY `order`]; nested e
xception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'omx.attributes_attributes' doesn't exist

**Comment by dennishendriksen** [comment]
Cannot reproduce.

**Comment by jjettenn** [comment]
It still does not work

**Comment by jjettenn** [comment]
16:27:19.428 [localhost-startStop-1] INFO  o.m.d.e.f.EmbeddedElasticSearchServiceFactory - Elastic search server stopped
16:27:19.435 [localhost-startStop-1] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webAppConfig': Invocation of init method failed; nested exception is org.molgenis.data.MolgenisDataException: Could not resolve dependencies of entities [g_genomic_1, g_genomic_2, g_genomic_all] are there circular dependencies?
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:407) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1546) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:706) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762) ~[spring-context-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482) ~[spring-context-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403) ~[spring-web-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) ~[spring-web-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5014) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524) [catalina.jar:7.0.59]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649) [catalina.jar:7.0.59]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081) [catalina.jar:7.0.59]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877) [catalina.jar:7.0.59]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
Caused by: org.molgenis.data.MolgenisDataException: Could not resolve dependencies of entities [g_genomic_1, g_genomic_2, g_genomic_all] are there circular dependencies?
	at org.molgenis.util.DependencyResolver.resolve(DependencyResolver.java:98) ~[molgenis-data-1.7.0.jar:1.7.0]
	at org.molgenis.util.DependencyResolver.resolve(DependencyResolver.java:38) ~[molgenis-data-1.7.0.jar:1.7.0]
	at org.molgenis.ui.MolgenisWebAppConfig.reindex(MolgenisWebAppConfig.java:390) ~[molgenis-core-ui-1.7.0.jar:1.7.0]
	at org.molgenis.ui.MolgenisWebAppConfig.initRepositories(MolgenisWebAppConfig.java:420) ~[molgenis-core-ui-1.7.0.jar:1.7.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.0.8.RELEASE.jar:4.0.8.RELEASE]
	... 27 common frames omitted

**Comment by fdlk** [comment]
Dat is de genome browser test set, die heb ik voor de dataexplorer test geuploaded. Ging toen prima, en nou ineens snapt hij hem niet meer?

**Comment by jjettenn** [comment]
I have reproduced this issue with the "genome browser test set" 

"Could not resolve dependencies of entities [g_genomic_1, g_genomic_2, g_genomic_all] are there circular dependencies?"

**Comment by jjettenn** [comment]
Just tested and it works
