### ISSUE TITLE
Disease matcher breaks search box if entity has no geneSymbol

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3069]
In the data explorer, if I visit the disease matcher and then do a search in the google filter box, I get an alert "Error! geneSymbol"

## Reproduce
Open the dataexplorer.
Select entity TypeTest.
Click the Disease Matcher tab.
Two warnings are shown. Warning! no geneSymbol column found!
Click the Data tab.
Type "label3" into the search box.
Press the search button.

## Expected
No alert is shown

## Actual
Alert is shown saying
Error! geneSymbol.
Server side a NullPointer exception sits in the catalina.out log:

```
11:52:40.677 [ajp-bio-8009-exec-64] ERROR o.molgenis.data.rest.RestController -
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[3rAobd3GTcOEsqtR2YsSGQ][molgenis][0]: SearchParseException[[molgenis][0]: from[0],size[10000]: Parse Failure [Failed to parse source [{"from":0,"size":10000,"query":{"filtered":{"query":{"match_all":{}},"filter":{"term":{"geneSymbol.raw":[""]}}}}}]]]; nested: NullPointerException; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:233) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:179) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565) ~[elasticsearch-1.4.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_31]
```

**Comment by tommydeboer** [comment]
Closed due to discontinuation of plugin.
