### ISSUE TITLE
Charts won't plot TypeTest ID column versus TypeTest ID column

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3077]
## Reproduce
Select Dataexplorer, Select TypeTest, Select charts
Create scatter plot for ID versus ID column.

## Expected
I can see the chart

## Actual
I get a somewhat obscure error:

```
18:32:36.221 [ajp-bio-8009-exec-161] ERROR org.molgenis.charts.ChartController - null
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query_fetch], all shards failed; shardFailures {[3rAobd3GTcOEsqtR2YsSGQ][molgenis][0]: QueryPhaseExecutionException[[molgenis][0]: query[ConstantScore(cache(+_type:org_molgenis_test_TypeTest +org.elasticsearch.index.search.nested.NonNestedDocsFilter@7b0ccb35))],from[0],size[1000],sort[<custom:"id": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@64be0481>,<custom:"id": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@73957d5e>]: Query Failed [Failed to execute main query]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:233) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:179) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565) ~[elasticsearch-1.4.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_31]
```

**Comment by Mark-de-Haan** [comment]
Can not reproduce
