### ISSUE TITLE
Infinite import when ImportRun message is too long

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#3172]
Reproduce:
- Import [EMX file with attributes tab with 5000 attributes for one entity](https://github.com/molgenis/molgenis/files/624491/emx_3172.xlsx)

Expected:
- Import fails with 'too many columns message'

Actual:
- Importer UI keeps show spinner indefinitely because an exception occured updating ImporterRun entity in the database. Reason is that the importer message is too long.

This can be solved by validating the message length and only storing the last <MAX> chars.

**Comment by Mark-de-Haan** [comment]
@dennishendriksen  Is this still an issue?

**Comment by dennishendriksen** [comment]
@Mark-de-Haan Yes. The issue was encountered during both 3.0-RC1 and 3.0-RC2 release testing by different people.

**Comment by ConnorStroomberg** [comment]
Stack trace from email Mark:
13:21:23.304 [pool-9-thread-18] INFO  org.molgenis.data.importer.ImportJob - Import started
13:21:23.307 [pool-9-thread-18] INFO  org.molgenis.data.importer.ImportJob - Import failed.
org.molgenis.data.MolgenisDataException: ; nested exception is org.molgenis.data.MolgenisDataAccessException: No [WRITE] permission on entity [sys_ont_OntologyTermDynamicAnnotation]
        at org.molgenis.ontology.importer.OntologyImportService.doImport(OntologyImportService.java:103) ~[molgenis-ontology-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.molgenis.ontology.importer.OntologyImportService$$FastClassBySpringCGLIB$$a0674a50.invoke(<generated>) ~[molgenis-ontology-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.molgenis.ontology.importer.OntologyImportService$$EnhancerBySpringCGLIB$$acb06b9c.doImport(<generated>) ~[molgenis-ontology-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.molgenis.data.importer.ImportJob.run(ImportJob.java:50) ~[molgenis-data-import-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
Caused by: org.molgenis.data.MolgenisDataAccessException: No [WRITE] permission on entity [sys_ont_OntologyTermDynamicAnnotation]
        at org.molgenis.util.SecurityDecoratorUtils.validatePermission(SecurityDecoratorUtils.java:18) ~[molgenis-data-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.molgenis.data.RepositorySecurityDecorator.add(RepositorySecurityDecorator.java:191) ~[molgenis-data-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$add$19(TransactionalRepositoryDecorator.java:198) ~[molgenis-data-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.molgenis.data.transaction.TransactionalRepositoryDecorator.add(TransactionalRepositoryDecorator.java:198) ~[molgenis-data-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:161) ~[molgenis-data-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.molgenis.ontology.importer.OntologyImportService.doImport(OntologyImportService.java:70) ~[molgenis-ontology-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        ... 14 common frames omitted
Exception in thread "pool-9-thread-18" java.lang.NullPointerException
        at org.molgenis.data.importer.ImportRunService.failImportRun(ImportRunService.java:123)
        at org.molgenis.data.importer.ImportRunService$$FastClassBySpringCGLIB$$810a1a5b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:61)
        at org.molgenis.security.core.runas.RunAsSystemProxy.invoke(RunAsSystemProxy.java:39)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at org.molgenis.data.importer.ImportRunService$$EnhancerBySpringCGLIB$$fc47d146.failImportRun(<generated>)
        at org.molgenis.data.importer.ImportJob.run(ImportJob.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617

**Comment by ConnorStroomberg** [comment]
Created a fix (https://github.com/ConnorStroomberg/molgenis/tree/issue/%233172) for the null pointer seen in the stack trace seen above, but this does not seem the fix the issue as far as i can seen.

While reproducing the issue on a local machine the importing takes a very long time ( > 1 hour), but no exception is thrown, this still needs to be looked into.
