### ISSUE TITLE
When adding a TypeTest entity mapping source to a TypeTest target for the first time I get an error

### ISSUE THREAD

**Issue by jjettenn** [molgenis/molgenis#3483]
To reproduce:
1. Start a clean Molgenis (drop schema and elastic).
2. Upload TypeTest into molgenis.
3. Got to the mapping service and create a project with TypeTest.
4. Add TypeTest as  a source to the TypeTest target.

Error:
{
  "errors": [
    {
      "message": "An error occurred. Please contact the administrator.<br />Message:Mapping already present for source org_molgenis_test_TypeTest"
    }
  ]
}

Stack trace:

10:57:40.861 [qtp748257243-31] ERROR o.m.d.m.c.MappingServiceController - Mapping already present for source org_molgenis_test_TypeTest
java.lang.IllegalStateException: Mapping already present for source org_molgenis_test_TypeTest
	at org.molgenis.data.mapper.mapping.model.MappingTarget.addSource(MappingTarget.java:75) ~[classes/:na]
	at org.molgenis.data.mapper.controller.MappingServiceController.addEntityMapping(MappingServiceController.java:225) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]

**Comment by Mark-de-Haan** [comment]
Can not reproduce:

- Dropped database
- Uploaded type test
- Created a project with typetest entity
- Added the source typetest

Worked OK
