### ISSUE TITLE
JPA generation of MREFs doesn't work.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3537]
Using MREFs in JPA's doesn't work anymore.

Sample model file:
```
<?xml version="1.0" encoding="UTF-8"?>
<molgenis name="org.molgenis.data">
	<module name="mrefbug">
		<entity name="EntityA">
			<field name="id" type="autoid" hidden="true" description="automatically generated internal id, only for internal use." />
			<field name="b" type="mref" nillable="true" xref_entity="EntityB"/>
		</entity>
		<entity name="EntityB">
			<field name="id" type="autoid" hidden="true" description="automatically generated internal id, only for internal use." />
		</entity>
	</module>
</molgenis>
```

First you get a compilation error in the generated classes.
```
       @Override
	public String getIdValue()
	{
		return getAutoid();
	}
```
Fixable by adding a toString() in the DataTypeGen.ftl.

Then you get a nullpointer exception when starting up molgenis.
I think this is because a repository gets created for the MREF tables but it does not get registered with the dataService.

```
15:02:07.849 [main] ERROR o.s.web.context.ContextLoader - Context initialization failed
java.lang.IllegalArgumentException: repository is null
	at org.molgenis.data.elasticsearch.ElasticsearchRepositoryDecorator.<init>(ElasticsearchRepositoryDecorator.java:24) ~[classes/:na]
	at org.molgenis.data.elasticsearch.IndexedRepositoryCollectionDecorator.addEntityMeta(IndexedRepositoryCollectionDecorator.java:72) ~[classes/:na]
	at org.molgenis.data.meta.MetaDataServiceImpl.add(MetaDataServiceImpl.java:205) ~[classes/:na]
	at org.molgenis.data.meta.MetaDataServiceImpl.addEntityMeta(MetaDataServiceImpl.java:217) ~[classes/:na]
	at org.molgenis.data.meta.MetaDataServiceImpl$$Lambda$33/1193352814.accept(Unknown Source) ~[na:na]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_40]
	at org.molgenis.data.meta.MetaDataServiceImpl.onApplicationEvent(MetaDataServiceImpl.java:354) ~[classes/:na]
	at org.molgenis.data.meta.MetaDataServiceImpl.onApplicationEvent(MetaDataServiceImpl.java:42) ~[classes/:na]
	at org.molgenis.data.meta.MetaDataServiceImpl$$FastClassBySpringCGLIB$$7c65c46d.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.molgenis.data.meta.MetaDataServiceImpl$$EnhancerBySpringCGLIB$$887b55a9.onApplicationEvent(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:798) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:789) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294) [jetty-servlet-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1345) [jetty-webapp-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:296) [jetty-maven-plugin-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1338) [jetty-webapp-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:501) [jetty-webapp-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:365) [jetty-maven-plugin-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.maven.plugin.JettyServer.doStart(JettyServer.java:73) [jetty-maven-plugin-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:534) [jetty-maven-plugin-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:357) [jetty-maven-plugin-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:167) [jetty-maven-plugin-9.2.6.v20141205.jar:9.2.6.v20141205]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155) [maven-core-3.2.1.jar:3.2.1]
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584) [maven-embedder-3.2.1.jar:3.2.1]
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213) [maven-embedder-3.2.1.jar:3.2.1]
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157) [maven-embedder-3.2.1.jar:3.2.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.1.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.1.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.1.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.1.jar:na]
2015-08-31 15:02:07.856:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.m.p.JettyWebAppContext@5ae6a240{/,[file:/Users/fkelpin/git/molgenis/molgenis-app/src/main/resources/],STARTING}{[file:/Users/fkelpin/git/molgenis/molgenis-app/src/main/resources/]}
java.lang.IllegalArgumentException: repository is null
	at org.molgenis.data.elasticsearch.ElasticsearchRepositoryDecorator.<init>(ElasticsearchRepositoryDecorator.java:24)
	at org.molgenis.data.elasticsearch.IndexedRepositoryCollectionDecorator.addEntityMeta(IndexedRepositoryCollectionDecorator.java:72)
	at org.molgenis.data.meta.MetaDataServiceImpl.add(MetaDataServiceImpl.java:205)
	at org.molgenis.data.meta.MetaDataServiceImpl.addEntityMeta(MetaDataServiceImpl.java:217)
	at org.molgenis.data.meta.MetaDataServiceImpl$$Lambda$33/1193352814.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.molgenis.data.meta.MetaDataServiceImpl.onApplicationEvent(MetaDataServiceImpl.java:354)
	at org.molgenis.data.meta.MetaDataServiceImpl.onApplicationEvent(MetaDataServiceImpl.java:42)
	at org.molgenis.data.meta.MetaDataServiceImpl$$FastClassBySpringCGLIB$$7c65c46d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
	at org.molgenis.data.meta.MetaDataServiceImpl$$EnhancerBySpringCGLIB$$887b55a9.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:798)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:789)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1345)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:296)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1338)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:501)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:365)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.maven.plugin.JettyServer.doStart(JettyServer.java:73)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:534)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:357)
	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:167)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2015-08-31 15:02:07.857:WARN:oejsh.RequestLogHandler:main: !RequestLog
2015-08-31 15:02:07.892:INFO:oejs.ServerConnector:main: Started ServerConnector@6038186d{HTTP/1.1}{0.0.0.0:8080}
2015-08-31 15:02:07.893:INFO:oejs.Server:main: Started @29722ms
```

**Comment by mswertz** [comment]
propose to discontinue JPA and instead aid POJO conversion to our normal data api

**Comment by bartcharbon** [comment]
JPA has been removed
