### ISSUE TITLE
Clinvar annotator gives Message:null

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3625]
## Reproduce
  - Upload test_mutation_emx
  - Set Clinvar runtime property to the correct folder
  - Run annotator

## Expected
Succesful annotation

## Observed
Error: Message = null

java.lang.NullPointerException: null
	at org.molgenis.data.annotation.resources.impl.ResourceImpl.findAll(ResourceImpl.java:75) ~[classes/:na]
	at org.molgenis.data.annotation.resources.impl.ResourcesImpl.findAll(ResourcesImpl.java:50) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.AnnotatorImpl.annotateEntity(AnnotatorImpl.java:61) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.AnnotatorImpl.annotateEntity(AnnotatorImpl.java:1) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.RepositoryAnnotatorImpl.annotateEntity(RepositoryAnnotatorImpl.java:53) ~[classes/:na]
	at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:41) ~[classes/:na]
	at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:1) ~[classes/:na]
	at org.molgenis.data.annotation.CrudRepositoryAnnotator.iterateOverEntitiesAndAnnotate(CrudRepositoryAnnotator.java:104) ~[classes/:na]
	at org.molgenis.data.annotation.CrudRepositoryAnnotator.annotate(CrudRepositoryAnnotator.java:85) ~[classes/:na]
	at org.molgenis.dataexplorer.controller.AnnotatorController.annotateData(AnnotatorController.java:122) ~[classes/:na]
	at org.molgenis.dataexplorer.controller.AnnotatorController$$FastClassBySpringCGLIB$$30dc3d57.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]

**Comment by fdlk** [comment]
Shouldn't that be a file rather than a folder?

**Comment by Mark-de-Haan** [comment]
Then a fix is to change the default runtime property setting
