### ISSUE TITLE
GoNL annotator throws UnknownAttributeException for AF column

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3645]
## Reproduce
Import EMX from https://molgenis26.target.rug.nl/downloads/annotator_test.xlsx
Run the GoNL annotator

## Expected
GoNL annotates succesfully

## Observed
org.molgenis.data.UnknownAttributeException: AF
	at org.molgenis.data.support.DefaultEntity.set(DefaultEntity.java:301) ~[classes/:na]
	at org.molgenis.data.annotation.filter.GoNLMultiAllelicResultFilter.filterResults(GoNLMultiAllelicResultFilter.java:48) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.AnnotatorImpl.annotateEntity(AnnotatorImpl.java:72) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.AnnotatorImpl.annotateEntity(AnnotatorImpl.java:1) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.RepositoryAnnotatorImpl.annotateEntity(RepositoryAnnotatorImpl.java:53) ~[classes/:na]
	at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:41) ~[classes/:na]
	at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:1) ~[classes/:na]
	at org.molgenis.data.annotation.CrudRepositoryAnnotator.iterateOverEntitiesAndAnnotate(CrudRepositoryAnnotator.java:104) ~[classes/:na]
	at org.molgenis.data.annotation.CrudRepositoryAnnotator.annotate(CrudRepositoryAnnotator.java:85) ~[classes/:na]
	at org.molgenis.dataexplorer.controller.AnnotatorController.annotateData(AnnotatorController.java:122) ~[classes/:na]

**Comment by fdlk** [comment]
The underlying problem is that the GONL annotator misuses the query / filter / copy format of the standard framework by letting the filter not only filter the results but also compute new values based on the multiple results found.
