### ISSUE TITLE
Exac annotator throws a tabix query error

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#3646]
## Reproduce
Import EMX from https://molgenis26.target.rug.nl/downloads/annotator_test.xlsx
Run the Exac annotator

## Expected
Exac annotator runs succesfully

## Observed
16:22:38.059 [qtp891694555-529] INFO  o.m.d.a.CrudRepositoryAnnotator - Started annotating "AnnotatorTest" with the exac annotator (started by "admin")
16:22:39.327 [qtp891694555-529] ERROR o.m.d.a.resources.impl.ResourcesImpl - Error querying Resource EXACTabixResource.
16:22:39.505 [qtp891694555-529] ERROR o.m.d.controller.AnnotatorController - -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.molgenis.data.annotator.tabix.TabixReader.query(TabixReader.java:400) ~[classes/:na]
	at org.molgenis.data.annotator.tabix.TabixReader.query(TabixReader.java:452) ~[classes/:na]
	at org.molgenis.data.annotator.tabix.TabixVcfRepository.query(TabixVcfRepository.java:92) ~[classes/:na]
	at org.molgenis.data.annotator.tabix.TabixVcfRepository.findAll(TabixVcfRepository.java:75) ~[classes/:na]
	at org.molgenis.data.annotation.resources.impl.ResourceImpl.findAll(ResourceImpl.java:75) ~[classes/:na]
	at org.molgenis.data.annotation.resources.impl.ResourcesImpl.findAll(ResourcesImpl.java:50) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.AnnotatorImpl.annotateEntity(AnnotatorImpl.java:61) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.AnnotatorImpl.annotateEntity(AnnotatorImpl.java:1) ~[classes/:na]
	at org.molgenis.data.annotation.entity.impl.RepositoryAnnotatorImpl.annotateEntity(RepositoryAnnotatorImpl.java:53) ~[classes/:na]
	at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:41) ~[classes/:na]
	at org.molgenis.data.annotation.AbstractRepositoryEntityAnnotator$1.next(AbstractRepositoryEntityAnnotator.java:1) ~[classes/:na]
	at org.molgenis.data.annotation.CrudRepositoryAnnotator.iterateOverEntitiesAndAnnotate(CrudRepositoryAnnotator.java:104) ~[classes/:na]
	at org.molgenis.data.annotation.CrudRepositoryAnnotator.annotate(CrudRepositoryAnnotator.java:85) ~[classes/:na]
	at org.molgenis.dataexplorer.controller.AnnotatorController.annotateData(AnnotatorController.java:122) ~[classes/:na]

**Comment by dennishendriksen** [comment]
Cannot reproduce:
```cadd (annotation datasource unreachable)
CGD (annotation datasource unreachable)
dann (annotation datasource unreachable)
clinvar (annotation datasource unreachable)
hpo (annotation datasource unreachable)
exac (annotation datasource unreachable)
fitcon (annotation datasource unreachable)
snpEff (annotation datasource unreachable)
thousand_genomes (annotation datasource unreachable)```

**Comment by Mark-de-Haan** [comment]
Duplicate of #3751
