### ISSUE TITLE
Molgenis sometimes breaks the elasticsearch index when you shut down tomcat7.

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3765]
Stopping and starting tomcat7 sometimes leaves the elasticsearch index broken.
Only way to fix it is to clean the index.
Happened twice on molgenis62.

**Comment by fdlk** [comment]
```
17:56:44.950 [localhost-startStop-1] ERROR o.s.web.context.ContextLoader - Context initialization failed
java.lang.NullPointerException: null
	at org.molgenis.data.elasticsearch.index.MappingsBuilder.createAttributeMappingContents(MappingsBuilder.java:137) ~[molgenis-data-elasticsearch-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.elasticsearch.index.MappingsBuilder.createAttributeMapping(MappingsBuilder.java:109) ~[molgenis-data-elasticsearch-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.elasticsearch.index.MappingsBuilder.buildMapping(MappingsBuilder.java:94) ~[molgenis-data-elasticsearch-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.elasticsearch.ElasticSearchService.createMappings(ElasticSearchService.java:269) ~[molgenis-data-elasticsearch-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.elasticsearch.ElasticSearchService.createMappings(ElasticSearchService.java:301) ~[molgenis-data-elasticsearch-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.elasticsearch.ElasticSearchService.createMappings(ElasticSearchService.java:256) ~[molgenis-data-elasticsearch-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.elasticsearch.IndexedRepositoryCollectionDecorator.addEntityMeta(IndexedRepositoryCollectionDecorator.java:70) ~[molgenis-data-elasticsearch-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.meta.MetaDataServiceImpl.onApplicationEvent(MetaDataServiceImpl.java:352) ~[molgenis-data-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.meta.MetaDataServiceImpl.onApplicationEvent(MetaDataServiceImpl.java:47) ~[molgenis-data-1.10.0-SNAPSHOT.jar:1.10.0-SNAPSHOT]
	at org.molgenis.data.meta.MetaDataServiceImpl$$FastClassBySpringCGLIB$$7c65c46d.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:1.10.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.molgenis.data.meta.MetaDataServiceImpl$$EnhancerBySpringCGLIB$$ad24400d.onApplicationEvent(<generated>) ~[spring-core-4.1.6.RELEASE.jar:1.10.0-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) ~[spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5014) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524) [catalina.jar:7.0.59]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.59]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649) [catalina.jar:7.0.59]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081) [catalina.jar:7.0.59]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877) [catalina.jar:7.0.59]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
```

**Comment by erwinwinder** [comment]
Cannot reproduce.
Can only be reproduced by deleting the refEntity attr in the dataexplorer of the entities
