### ISSUE TITLE
Commandline annotator gives unhelpful error message when VCF validation cannot be run

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3828]
When annotating with for example a VCF-tools dir with unsufficient permissions set, the result is:
Validating produced VCF file...
Exception in thread "main" java.lang.NullPointerException
	at org.molgenis.data.annotation.cmd.VcfValidator.validateVCF(VcfValidator.java:108)
	at org.molgenis.data.annotation.cmd.CmdLineAnnotator.annotate(CmdLineAnnotator.java:286)
	at org.molgenis.data.annotation.cmd.CmdLineAnnotator.run(CmdLineAnnotator.java:155)
	at org.molgenis.data.annotation.cmd.CmdLineAnnotator.main(CmdLineAnnotator.java:178)

The nullpointer being the closing of a stream that was never instantiated due to a previous exception.

Real error, which should be logged/printed is: 
java.io.IOException: Cannot run program "/Users/charbonb/.molgenis/vcf-tools/bin/vcf-validator" (in directory "/Users/charbonb/.molgenis/vcf-tools/bin"): error=13, Permission denied

**Comment by fdlk** [comment]
Oh sweet irony. Bug created by findbugs!

**Comment by fdlk** [comment]
Fixed in the master.
