### ISSUE TITLE
Import user needs READ permission on MolgenisGroupMember

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#3885]
Sign up a new user, give write access to importer plugin.
Import an EMX file.

Expected:
File gets imported

Actual:
I get HTTP Status 500 error page

```
org.molgenis.data.MolgenisDataAccessException: No READ permission on entity MolgenisGroupMember
	at org.molgenis.util.SecurityDecoratorUtils.validatePermission(SecurityDecoratorUtils.java:16)
	at org.molgenis.data.RepositorySecurityDecorator.findAll(RepositorySecurityDecorator.java:84)
	at org.molgenis.data.support.DataServiceImpl.findAll(DataServiceImpl.java:148)
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$2e01a46.findAll(<generated>)
	at org.molgenis.data.elasticsearch.ElasticsearchEntityIterable$1.doBatchSearch(ElasticsearchEntityIterable.java:198)
	at org.molgenis.data.elasticsearch.ElasticsearchEntityIterable$1.hasNext(ElasticsearchEntityIterable.java:93)
	at org.molgenis.data.support.ConvertingIterator.hasNext(ConvertingIterator.java:25)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators.addAll(Iterators.java:356)
	at com.google.common.collect.Lists.newArrayList(Lists.java:147)
	at com.google.common.collect.Lists.newArrayList(Lists.java:129)
	at org.molgenis.data.importer.ValidationResultWizardPage.handleRequest(ValidationResultWizardPage.java:105)
	at org.molgenis.data.importer.ValidationResultWizardPage$$FastClassBySpringCGLIB$$1ae1595c.invoke(<generated>)
```

**Comment by fdlk** [comment]
And the rollback fails.

**Comment by Mark-de-Haan** [comment]
Nope the rollback fails for me as well

**Comment by dennishendriksen** [comment]
Problem does not occur in v1.10.0

**Comment by fdlk** [comment]
Happens after the import when determining the list of groups that you can give rights on the imported entities to.

**Comment by fdlk** [comment]
This is a tricky one. I think the code checked in in #3864 introduced it.

ElasticsearchEntityIterable:198 queries the dataService when it is iterated to get the entities from the original source. This means the query goes to a decorated repository with permission checks.
These permission checks are done **at iteration time**, under the securityContext **that does the iteration**. Not the securityContext used to do the query that created the iterable.

So Iterables created with elevated privileges in a runAsSystem method and returned from those methods will throw an exception when you iterate them outside the runAsSystem method.

I've patched this in this specific case in the userService by collecting the results before returning from the runAsSystem method. But that's a single bandage on a more general problem.

I don't really know how to patch this in general. Is it okay to do the ElasticSearchEntityIterable's query with elevated privileges? Would it swapping the context for each next() method be horribly slow? 

Haven't the permissions already been checked when you obtained the ElasticSearchEntityIterable? So would it perhaps be better and more efficient to do the query on an undecorated repository? But how does that look for xrefs and mrefs? Have the user's rights on the referenced repositories already been checked when the ElasticSearchEntityIterable was created?

**Comment by dennishendriksen** [comment]
This is indeed caused by #3864, which exposes a security issue that we weren't aware of before.
 
In my opinion the correct fix is that the Iterable<Entity> iterator() and all underlying calls should be executed with the same privileges used to create the Iterable<Entity> in order to guarantee that access to referenced data is permitted.

Who is responsible, the caller or the callee?

1) The caller
```
Iterable<Entity> entities;
runAsSystem(() -> {
   entities = dataService.findAll("NotMyEntity");
});
for(Entity entity : entities) { ... }
```

Throws an exception if the user executing this code has no permission on 'NotMyEntity'. 
```
runAsSystem(() -> {
   Iterable<Entity> entities = dataService.findAll("NotMyEntity");
   for(Entity entity : entities) { ... }
});
```
Does not throw an exception if the user executing this code has no permission on 'NotMyEntity'.

2) The callee
```
Iterable<Entity> entities;
runAsSystem(() -> {
   entities = dataService.findAll("NotMyEntity");
});
for(Entity entity : entities) { ... }
```
Does not throw an exception if the user executing this code has no permission on 'NotMyEntity'. This is dangerous since the entity might unintentionally expose data through a chain of references.

How does MySqlRepository deal with this, since it supports cross-backend entities (JpaRepository does not support this)?

**Comment by fdlk** [comment]
Won't that be terribly inefficient?

**Comment by dennishendriksen** [comment]
No, the efficiency doesn't change if you use solution 1)

**Comment by fdlk** [comment]
Ah, I misunderstood. Thought you meant that the callee had to make sure that the calls get executed with the same privileges that the original call was executed with.
