### ISSUE TITLE
Error when annotating VCF with "copy" selected

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#3890]
- load corner_cases.vcf (on the googledrive in the testplans/testdata folder)
- select all annotators
- select "copy before annotating"
- run

Error occurs, log states:
15:29:20.498 [ajp-bio-8009-exec-10] INFO  o.m.d.a.CrudRepositoryAnnotator - Started annotating "vcYcXVwpAvNnWkBbJFLgyBhUJQemVa" with the snpEff annotator (started by "admin")
15:30:05.773 [ajp-bio-8009-exec-10] INFO  o.m.d.a.CrudRepositoryAnnotator - Finished annotating "vcYcXVwpAvNnWkBbJFLgyBhUJQemVa" with the snpEff annotator (started by "admin")
15:30:05.777 [ajp-bio-8009-exec-10] INFO  o.m.d.a.CrudRepositoryAnnotator - Started annotating "vcYcXVwpAvNnWkBbJFLgyBhUJQemVa" with the thousand_genomes annotator (started by "admin")
15:30:06.820 [ajp-bio-8009-exec-10] INFO  o.m.d.a.CrudRepositoryAnnotator - Finished annotating "vcYcXVwpAvNnWkBbJFLgyBhUJQemVa" with the thousand_genomes annotator (started by "admin")
15:30:06.972 [ajp-bio-8009-exec-10] ERROR o.m.d.controller.AnnotatorController - null
java.lang.NullPointerException: null
    at org.molgenis.data.elasticsearch.index.EntityToSourceConverter.convertAttribute(EntityToSourceConverter.java:91) ~[molgenis-data-elasticsearch-1.11.0-SNAPSHOT.jar:1.11.0-SNAPSHOT]
    at org.molgenis.data.elasticsearch.index.EntityToSourceConverter.convert(EntityToSourceConverter.java:52) ~[molgenis-data-elasticsearch-1.11.0-SNAPSHOT.jar:1.11.0-SNAPSHOT]
    at org.molgenis.data.elasticsearch.index.EntityToSourceConverter.access$000(EntityToSourceConverter.java:24) ~[molgenis-data-elasticsearch-1.11.0-SNAPSHOT.jar:1.11.0-SNAPSHOT]
    at org.molgenis.data.elasticsearch.index.EntityToSourceConverter$1.apply(EntityToSourceConverter.java:138) ~[molgenis-data-elasticsearch-1.11.0-SNAPSHOT.jar:1.11.0-SNAPSHOT]
    at org.molgenis.data.elasticsearch.index.EntityToSourceConverter$1.apply(EntityToSourceConverter.java:132) ~[molgenis-data-elasticsearch-1.11.0-SNAPSHOT.jar:1.11.0-SNAPSHOT]
    at com.google.common.collect.Iterators$8.transform(Iterators.java:794) ~[guava-16.0.1.jar:na]
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-16.0.1.jar:na]
    at com.google.common.collect.Iterators.addAll(Iterators.java:357) ~[guava-16.0.1.jar:na]
    at com.google.common.collect.Lists.newArrayList(Lists.java:147) ~[guava-16.0.1.jar:na]
    at com.google.common.collect.Lists.newArrayList(Lists.java:129) ~[guava-16.0.1.jar:na]
    at org.molgenis.data.elasticsearch.index.EntityToSourceConverter.convertAttribute(EntityToSourceConverter.java:131) ~[molgenis-data-elasticsearch-1.11.0-SNAPSHOT.jar:1.11.0-SNAPSHOT]
    at org.molgenis.data.elasticsearch.index.EntityToSourceConverter.convert(EntityToSourceConverter.java:52) ~[molgenis-data-elasticsearch-1.11.0-SNAPSHOT.jar:1.11.0-SNAPSHOT]

**Comment by bartcharbon** [comment]
For the record: without the copy selected the annotating finishes succesfull

**Comment by Mark-de-Haan** [comment]
Can not import the file mentioned in the issue:

`Error! Your import failed:
Invalid characters in: [corner_cases _1_] Only letters (a-z, A-Z), digits (0-9), underscores (_) and hashes (#) are allowed.`

**Comment by fdlk** [comment]
@jjettenn is this relevant to your fix or will your fix fix this as well?
