### ISSUE TITLE
Model DICOM_MODEL.xlsx import error

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4003]
Reproduce:
- Log in as non-superuser with read permission on importer, standardsregistry
- Import molgenis-model-registry\src\test\resources\DICOM_MODEL.xlsx

Expected:
- Import successful

Actual:
```No READ permission on entity entities```

**Comment by dennishendriksen** [comment]
```org.molgenis.data.MolgenisDataAccessException: No READ permission on entity entities
	at org.molgenis.util.SecurityDecoratorUtils.validatePermission(SecurityDecoratorUtils.java:16) ~[classes/:na]
	at org.molgenis.data.RepositorySecurityDecorator.findOne(RepositorySecurityDecorator.java:77) ~[classes/:na]
	at org.molgenis.data.support.DataServiceImpl.findOne(DataServiceImpl.java:154) ~[classes/:na]
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$489e7b2a.findOne(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.molgenis.data.semanticsearch.service.impl.UntypedTagService.findEntity(UntypedTagService.java:62) ~[classes/:na]
	at org.molgenis.data.semanticsearch.service.impl.UntypedTagService.addEntityTag(UntypedTagService.java:141) ~[classes/:na]```
