### ISSUE TITLE
Model registry error occurred opening plugin 

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#4015]
Reproduce:
- Login as non-superuser
- Import some data sets
- Go to model registry plugin

Expected:
- I see my uploaded models

Actual:
```Error! An error occurred. Please contact the administrator.``` with the following log entries ```Error rendering view [org.springframework.web.servlet.view.InternalResourceView: unnamed; URL [/plugin/standardsregistry/search]] in DispatcherServlet with nam
e 'dispatcher'
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.molgenis.data.MolgenisDataAccessException: No COUNT permission on entity RuntimeProperty```

**Comment by dennishendriksen** [comment]
```Caused by: org.molgenis.data.MolgenisDataAccessException: No COUNT permission on entity RuntimeProperty
        at org.molgenis.util.SecurityDecoratorUtils.validatePermission(SecurityDecoratorUtils.java:16) ~[molgenis-data-1.12.0-SNAPSHOT.jar:1.12.0-SNAPSHOT]
        at org.molgenis.data.RepositorySecurityDecorator.count(RepositorySecurityDecorator.java:56) ~[molgenis-data-1.12.0-SNAPSHOT.jar:1.12.0-SNAPSHOT]
        at org.molgenis.data.support.DataServiceImpl.count(DataServiceImpl.java:130) ~[molgenis-data-1.12.0-SNAPSHOT.jar:1.12.0-SNAPSHOT]
        at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:1.12.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$6978505f.count(<generated>) ~[spring-core-4.1.6.RELEASE.jar:1.12.0-SNAPSHOT]
        at org.molgenis.standardsregistry.StandardsRegistryController$1.apply(StandardsRegistryController.java:157) ~[molgenis-model-registry-1.12.0-SNAPSHOT.jar:1.12.0-SNAPSHOT]
        at org.molgenis.standardsregistry.StandardsRegistryController$1.apply(StandardsRegistryController.java:144) ~[molgenis-model-registry-1.12.0-SNAPSHOT.jar:1.12.0-SNAPSHOT]
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647) ~[guava-16.0.1.jar:na]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-16.0.1.jar:na]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-16.0.1.jar:na]
        at com.google.common.collect.Iterators.addAll(Iterators.java:356) ~[guava-16.0.1.jar:na]
        at com.google.common.collect.Lists.newArrayList(Lists.java:147) ~[guava-16.0.1.jar:na]
        at com.google.common.collect.Lists.newArrayList(Lists.java:129) ~[guava-16.0.1.jar:na]
        at org.molgenis.standardsregistry.StandardsRegistryController.search(StandardsRegistryController.java:142) ~[molgenis-model-registry-1.12.0-SNAPSHOT.jar:1.12.0-SNAPSHOT]```

**Comment by erwinwinder** [comment]
When you open Model Registry you see for a short time the error 'Assetion Failed'.
Then the page refreshes and the model is shown.

**Comment by erwinwinder** [comment]
This is a different issue
