### ISSUE TITLE
SQLError 'Too many connections' on dataexplorer 'aggregates' tab

### ISSUE THREAD

**Issue by erwinwinder** [molgenis/molgenis#4189]
Sometimes when you are on the 'aggregates' tab and you do some queries this exception occurs:
(Or maybe it is the switching between data/agrgregates tab?)

09:27:12.590 [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2] WARN  c.m.v.resourcepool.BasicResourcePool - com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@aeb0c25 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
	at sun.reflect.GeneratedConstructorAccessor189.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0_25]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1114) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2493) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2526) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2311) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.28.jar:na]
	at sun.reflect.GeneratedConstructorAccessor180.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0_25]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:347) ~[mysql-connector-java-5.1.28.jar:na]
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:134) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:182) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:171) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547) [c3p0-0.9.1.2.jar:0.9.1.2]

**Comment by fdlk** [comment]
I tried to debug this on the server side, and everything looks just fine there.
I added 
```java
		dataSource.setMaxPoolSize(10); // down from 200
		dataSource.setCheckoutTimeout(15000); //get angry when connections aren't returned after 15 seconds
		dataSource.setDebugUnreturnedConnectionStackTraces(true); //and debug a stacktrace when that happens
```
I found out this way that one connection gets eaten up from the pool and is never returned. This happens because an old migration name conversion step checks out a single connection to the database and never returns it.

```
SingleConnectionDataSource singleConnectionDS = null;
		try
		{
			singleConnectionDS = new SingleConnectionDataSource(dataSource.getConnection(), true);
		}
		catch (SQLException e)
		{
			e.printStackTrace();
		}

		upgradeService.addUpgrade(new Step11ConvertNames(singleConnectionDS));
```

That is only one connection getting lost, though, on startup.

If I upload and select TypeTest and click around on the aggregates screen, The pool gets by using only 10 connections tops.

**Comment by fdlk** [comment]
So, like the error says, this is the mysql server complaining. Could it be that it's configured to allow less connections than the 200 that our c3p0 connection pool is configured to claim as a maximum?

**Comment by fdlk** [comment]
Alright, figured it out.
Default maximum number of connections for mysql is 150.
Molgenis by default has a connection pool of max 200 connections, which I'd call ridiculously high.

So under peak load, for instance when spamming requests when debugging a buggy client, we can overload the server and get these messages. Fixing this by lowering the max connection count for molgenis to 150.
