### ISSUE TITLE
When doing an apiv2 request on with an attrs query, you get an error if the id attribute is not requested as well

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4190]
## Reproduce
- Import TypeTest
- Perform the following REST query:
    
```
http://localhost:8080/api/v2/org_molgenis_test_TypeTest?attrs=xbool
```

## Expected
I get all xbool entries back

## Observed
```javascript
10:22:11.171 [qtp436605483-168] ERROR o.m.data.rest.v2.RestControllerV2 - Runtime exception occurred.
java.lang.NullPointerException: null key in entry: null=org.molgenis.data.support.PartialEntity@52f021cd
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1164) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140) ~[guava-16.0.1.jar:na]
	at org.molgenis.data.support.AbstractRepository.findAllBatched(AbstractRepository.java:120) ~[classes/:na]
	at org.molgenis.data.support.AbstractRepository.access$0(AbstractRepository.java:116) ~[classes/:na]
	at org.molgenis.data.support.AbstractRepository$1.apply(AbstractRepository.java:111) ~[classes/:na]
	at org.molgenis.data.support.AbstractRepository$1.apply(AbstractRepository.java:1) ~[classes/:na]
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543) ~[guava-16.0.1.jar:na]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811) ~[na:1.8.0_40]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$221(StreamSpliterators.java:294) ~[na:1.8.0_40]
	at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$58/593885463.getAsBoolean(Unknown Source) ~[na:na]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[na:1.8.0_40]
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161) ~[na:1.8.0_40]
```

## Note
You can work around this bug by adding the id attribute to the query:
```
http://localhost:8080/api/v2/org_molgenis_test_TypeTest?attrs=id,xbool
```

**Comment by mswertz** [comment]
Duplicate with #4310
