### ISSUE TITLE
StackOverflowError when inspecting a self-referencing reference

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#4284]
### To reproduce:
1. Import 
[this EMX](https://github.com/molgenis/molgenis/files/65478/test_selfReference2.xlsx)
 with self references.
2. Go to Data Explorer
3. Open the **SelfReference** entity
4. Click on one of the values in the **xref_self** column

### Expected:
A modal is shown with the referenced entity.

### Actual:
Referencing back to the same entity type is allowed (for example A -> B), but referencing to the same entity instance is not (A -> A).

```java
Caused by: java.lang.StackOverflowError: null
	at org.elasticsearch.common.collect.RegularImmutableMap.get(RegularImmutableMap.java:155) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.common.settings.ImmutableSettings.get(ImmutableSettings.java:234) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.common.settings.ImmutableSettings.getAsInt(ImmutableSettings.java:319) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.cluster.metadata.IndexMetaData.numberOfShards(IndexMetaData.java:280) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.cluster.routing.operation.plain.PlainOperationRouting.shardId(PlainOperationRouting.java:272) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.cluster.routing.operation.plain.PlainOperationRouting.shards(PlainOperationRouting.java:257) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.cluster.routing.operation.plain.PlainOperationRouting.getShards(PlainOperationRouting.java:79) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.get.TransportGetAction.shards(TransportGetAction.java:70) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.<init>(TransportShardSingleOperationAction.java:151) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.<init>(TransportShardSingleOperationAction.java:116) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:89) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction.doExecute(TransportShardSingleOperationAction.java:55) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:197) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.get.GetRequestBuilder.doExecute(GetRequestBuilder.java:201) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:73) ~[elasticsearch-1.7.3.jar:na]
	at org.molgenis.data.elasticsearch.ElasticsearchService.get(ElasticsearchService.java:701) ~[classes/:na]
	at org.molgenis.data.elasticsearch.ElasticsearchService.get(ElasticsearchService.java:654) ~[classes/:na]
	at org.molgenis.data.elasticsearch.AbstractElasticsearchRepository.findOne(AbstractElasticsearchRepository.java:84) ~[classes/:na]
	at org.molgenis.data.EntityReferenceResolverDecorator.findOne(EntityReferenceResolverDecorator.java:92) ~[classes/:na]
	at org.molgenis.data.ComputedEntityValuesDecorator.findOne(ComputedEntityValuesDecorator.java:90) ~[classes/:na]
	at org.molgenis.ui.EntityListenerRepositoryDecorator.findOne(EntityListenerRepositoryDecorator.java:95) ~[classes/:na]
	at org.molgenis.data.transaction.TransactionLogRepositoryDecorator.findOne(TransactionLogRepositoryDecorator.java:93) ~[classes/:na]
	at org.molgenis.data.validation.RepositoryValidationDecorator.findOne(RepositoryValidationDecorator.java:457) ~[classes/:na]
	at org.molgenis.data.AutoValueRepositoryDecorator.findOne(AutoValueRepositoryDecorator.java:138) ~[classes/:na]
	at org.molgenis.data.RepositorySecurityDecorator.findOne(RepositorySecurityDecorator.java:85) ~[classes/:na]
	at org.molgenis.data.support.DataServiceImpl.findOne(DataServiceImpl.java:153) ~[classes/:na]
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[spring-core-4.1.8.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$bb94bd1c.findOne(<generated>) ~[spring-core-4.1.8.RELEASE.jar:na]
	at org.molgenis.data.support.LazyEntity.getLazyLoadedEntity(LazyEntity.java:186) ~[classes/:na]
	at org.molgenis.data.support.LazyEntity.getEntity(LazyEntity.java:137) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponseRec(RestControllerV2.java:598) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponse(RestControllerV2.java:576) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityResponse(RestControllerV2.java:564) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponseRec(RestControllerV2.java:603) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponse(RestControllerV2.java:576) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityResponse(RestControllerV2.java:564) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponseRec(RestControllerV2.java:603) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponse(RestControllerV2.java:576) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityResponse(RestControllerV2.java:564) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponseRec(RestControllerV2.java:603) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponse(RestControllerV2.java:576) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityResponse(RestControllerV2.java:564) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponseRec(RestControllerV2.java:603) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityValuesResponse(RestControllerV2.java:576) ~[classes/:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityResponse(RestControllerV2.java:564) ~[classes/:na]
etc...
```

**Comment by fdlk** [comment]
Alright, I have a hacky fix that chops self-references off after depth one.
I think the real solution is to use the Fetch for that attribute so that the data explorer can use a complicated fetch to fetch deeper nested structures.

**Comment by fdlk** [comment]
Got the Fetch thing sort of working now. There's some serious bugs in the AttributeFilter -> Fetch conversions for XREF and MREFs

**Comment by fdlk** [comment]
Root cause for this is #4312, solved that instead.
