### ISSUE TITLE
Uploading a VCF will throw an error

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#4431]
## Reproduce
Upload one of the vcf files located in this zip: [TestVcfFiles.zip](https://github.com/molgenis/molgenis/files/117343/TestVcfFiles.zip)

## Expected
A nice vcf upload that passes

## Observed
Took log from the server (both 01 and 31)

```
2:31:32.790` [pool-8-thread-1] INFO  org.molgenis.data.importer.ImportJob - Import failed.
org.molgenis.data.MolgenisDataException: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no documents to get;
	at org.molgenis.data.vcf.importer.VcfImporterService.doImport(VcfImporterService.java:104) ~[molgenis-data-vcf-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.importer.ImportJob.run(ImportJob.java:51) ~[molgenis-data-import-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
Caused by: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no documents to get;
	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:29) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.get.MultiGetRequest.validate(MultiGetRequest.java:286) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:67) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.client.support.AbstractClient.multiGet(AbstractClient.java:323) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.get.MultiGetRequestBuilder.doExecute(MultiGetRequestBuilder.java:92) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:73) ~[elasticsearch-1.7.3.jar:na]
	at org.molgenis.data.elasticsearch.ElasticsearchService.get(ElasticsearchService.java:806) ~[molgenis-data-elasticsearch-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.elasticsearch.AbstractElasticsearchRepository.findAll(AbstractElasticsearchRepository.java:103) ~[molgenis-data-elasticsearch-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.EntityReferenceResolverDecorator.findAll(EntityReferenceResolverDecorator.java:117) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.ComputedEntityValuesDecorator.findAll(ComputedEntityValuesDecorator.java:115) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.ui.EntityListenerRepositoryDecorator.findAll(EntityListenerRepositoryDecorator.java:114) ~[molgenis-core-ui-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.transaction.TransactionLogRepositoryDecorator.findAll(TransactionLogRepositoryDecorator.java:112) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.validation.RepositoryValidationDecorator.findAll(RepositoryValidationDecorator.java:204) ~[molgenis-data-validation-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.AutoValueRepositoryDecorator.findAll(AutoValueRepositoryDecorator.java:145) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.RepositorySecurityDecorator.findAll(RepositorySecurityDecorator.java:107) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.support.DataServiceImpl.findAll(DataServiceImpl.java:326) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[spring-core-4.1.8.RELEASE.jar:1.17.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$7c5fe17.findAll(<generated>) ~[spring-core-4.1.8.RELEASE.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.EntityManagerImpl.resolveReferences(EntityManagerImpl.java:133) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.EntityReferenceResolverDecorator.resolveEntityReferences(EntityReferenceResolverDecorator.java:240) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.EntityReferenceResolverDecorator.findAll(EntityReferenceResolverDecorator.java:64) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.ComputedEntityValuesDecorator.findAll(ComputedEntityValuesDecorator.java:61) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.ui.EntityListenerRepositoryDecorator.findAll(EntityListenerRepositoryDecorator.java:84) ~[molgenis-core-ui-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.transaction.TransactionLogRepositoryDecorator.findAll(TransactionLogRepositoryDecorator.java:82) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.validation.RepositoryValidationDecorator.initUniqueValidation(RepositoryValidationDecorator.java:386) ~[molgenis-data-validation-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.validation.RepositoryValidationDecorator.initValidation(RepositoryValidationDecorator.java:315) ~[molgenis-data-validation-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.validation.RepositoryValidationDecorator.validate(RepositoryValidationDecorator.java:283) ~[molgenis-data-validation-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:112) ~[molgenis-data-validation-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.AutoValueRepositoryDecorator.add(AutoValueRepositoryDecorator.java:61) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.RepositorySecurityDecorator.add(RepositorySecurityDecorator.java:177) ~[molgenis-data-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.vcf.importer.VcfImporterService.importVcf(VcfImporterService.java:256) ~[molgenis-data-vcf-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	at org.molgenis.data.vcf.importer.VcfImporterService.doImport(VcfImporterService.java:79) ~[molgenis-data-vcf-1.17.0-SNAPSHOT.jar:1.17.0-SNAPSHOT]
	... 4 common frames omitted
```

**Comment by Mark-de-Haan** [comment]
@mswertz This bug has been introduced in the last few days and is also blocking the selenium test. So I would propose to fix it now.
