### ISSUE TITLE
unable to annotate with a "normal" user

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#4619]
when clicking the annotator tab with a "normal" user, I get:

Error! An error occurred. Please contact the administrator.
Message:No READ permission on entity AnnotationJobExecution

When I than give the user permissions for AnnotationJobExecution and try again I get a login dialog when surfing to the data explorer. (browser console error in attached image)

![exception](https://cloud.githubusercontent.com/assets/3714029/13597666/117956ba-e51a-11e5-9db1-3a69ca4f661f.png)

**Comment by bartcharbon** [comment]
furthermore if I surf straight to the dataset i want to annotate by url, the explorer works, I can open the annotator tab, after hitting the button it returns to the annotator tab without an error in the UI. 

the server log states: java.lang.RuntimeException: org.molgenis.data.MolgenisDataAccessException: No WRITEMETA permission on entity fiveGPM_GPM

Which is correct, but should be reported by the UI, and from usability point of view the anntoators should not be available for this user for this entity

**Comment by bartcharbon** [comment]
setting the WriteMEta for the user gets you a:

    java.lang.RuntimeException: org.molgenis.data.MolgenisDataAccessException: No READ     permission on entity entities
	at     org.molgenis.data.annotation.CrudRepositoryAnnotator.annotate(CrudRepositoryAnnotator.java:72) ~[molgenis-data-annotators-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
	at org.molgenis.data.annotation.CrudRepositoryAnnotator$$FastClassBySpringCGLIB$$8b149205.invoke(<generated>) ~[spring-core-4.1.8.RELEASE.jar:1.18.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at     org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]


while trying to annotate
