### ISSUE TITLE
ConcurrentModificationException in the ElasticSearchService updateReferences method

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4634]
Occurred when I was repeatedly running the ImportApiTest.

```
	java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_73]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[na:1.8.0_73]
        at org.molgenis.util.EntityUtils.lambda$getReferencingEntityMetaData$32(EntityUtils.java:54) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_73]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_73]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_73]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_73]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_73]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_73]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_73]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_73]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_73]
        at org.molgenis.util.EntityUtils.getReferencingEntityMetaData(EntityUtils.java:49) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.elasticsearch.ElasticsearchService.updateReferences(ElasticsearchService.java:1043) ~[molgenis-data-elasticsearch-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.elasticsearch.ElasticsearchService.index(ElasticsearchService.java:519) ~[molgenis-data-elasticsearch-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.elasticsearch.ElasticsearchService.index(ElasticsearchService.java:414) ~[molgenis-data-elasticsearch-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.elasticsearch.ElasticsearchService.index(ElasticsearchService.java:401) ~[molgenis-data-elasticsearch-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.elasticsearch.AbstractElasticsearchRepository.update(AbstractElasticsearchRepository.java:170) ~[molgenis-data-elasticsearch-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.EntityReferenceResolverDecorator.update(EntityReferenceResolverDecorator.java:138) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.ComputedEntityValuesDecorator.update(ComputedEntityValuesDecorator.java:137) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.ui.EntityListenerRepositoryDecorator.update(EntityListenerRepositoryDecorator.java:132) ~[molgenis-core-ui-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.transaction.TransactionLogRepositoryDecorator.update(TransactionLogRepositoryDecorator.java:135) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.validation.RepositoryValidationDecorator.update(RepositoryValidationDecorator.java:79) ~[molgenis-data-validation-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.AutoValueRepositoryDecorator.update(AutoValueRepositoryDecorator.java:163) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.RepositorySecurityDecorator.update(RepositorySecurityDecorator.java:128) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.transaction.AsyncTransactionLog$QueueConsumer.lambda$run$76(AsyncTransactionLog.java:81) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:60) ~[molgenis-security-core-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at org.molgenis.data.transaction.AsyncTransactionLog$QueueConsumer.run(AsyncTransactionLog.java:69) ~[molgenis-data-1.19.0-SNAPSHOT.jar:1.19.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
```

**Comment by dennishendriksen** [comment]
Fixed in 2.0-RC, the updateReferences method doesn't exist anymore.
