### ISSUE TITLE
Sorta job failure: NPE

### ISSUE THREAD

**Issue by ChaoPang** [molgenis/molgenis#4702]
## Comment

The Sorta job fails after the first job succeeds with the same dataset and the same ontology
## DataSet

[input_dataset_sorta.txt](https://github.com/molgenis/molgenis/files/183876/input_dataset_sorta.txt)
[Active_admin_info.zip](https://github.com/molgenis/molgenis/files/183878/Active_admin_info.zip)
[error_log.txt](https://github.com/molgenis/molgenis/files/187812/error_log.txt)
## Stacktrace

```
10:55:28.008 INFO  - start ()
10:55:35.747 INFO  - progress (50, )
10:55:43.508 INFO  - progress (100, )
10:55:51.220 INFO  - progress (150, )
10:55:58.760 INFO  - progress (200, )
10:56:06.550 INFO  - progress (250, )
10:56:14.969 INFO  - progress (300, )
10:56:22.804 INFO  - progress (350, )
10:56:30.827 INFO  - progress (400, )
10:56:38.850 INFO  - progress (450, )
10:56:45.127 ERROR - Failed
java.lang.IllegalArgumentException: null value
    at org.mapdb.HTreeMap.put(HTreeMap.java:473) ~[mapdb-1.0.6.jar:na]
    at java.util.AbstractMap.putAll(AbstractMap.java:281) ~[na:1.8.0_31]
    at org.molgenis.util.HugeMap.put(HugeMap.java:74) ~[molgenis-core-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.validation.RepositoryValidationDecorator.lambda$validateEntityValueUniqueness$13(RepositoryValidationDecorator.java:508) ~[molgenis-data-validation-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.validation.RepositoryValidationDecorator$$Lambda$164/2074016185.accept(Unknown Source) ~[na:na]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_31]
    at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[na:1.8.0_31]
    at org.molgenis.data.validation.RepositoryValidationDecorator.validateEntityValueUniqueness(RepositoryValidationDecorator.java:484) ~[molgenis-data-validation-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.validation.RepositoryValidationDecorator.lambda$validate$1(RepositoryValidationDecorator.java:306) ~[molgenis-data-validation-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.validation.RepositoryValidationDecorator$$Lambda$161/18743408.test(Unknown Source) ~[na:na]
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_31]
    at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[na:1.8.0_31]
    at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$207(StreamSpliterators.java:294) ~[na:1.8.0_31]
    at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$94/362553006.getAsBoolean(Unknown Source) ~[na:na]
    at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[na:1.8.0_31]
    at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169) ~[na:1.8.0_31]
    at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[na:1.8.0_31]
    at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:1.8.0_31]
    at org.elasticsearch.common.collect.Iterators$6.next(Iterators.java:626) ~[elasticsearch-1.7.3.jar:na]
    at org.elasticsearch.common.collect.Iterators$6.next(Iterators.java:614) ~[elasticsearch-1.7.3.jar:na]
    at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_31]
    at org.molgenis.data.elasticsearch.ElasticsearchRepositoryDecorator.add(ElasticsearchRepositoryDecorator.java:62) ~[molgenis-data-elasticsearch-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.EntityReferenceResolverDecorator.add(EntityReferenceResolverDecorator.java:186) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.ComputedEntityValuesDecorator.add(ComputedEntityValuesDecorator.java:185) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.ui.EntityListenerRepositoryDecorator.add(EntityListenerRepositoryDecorator.java:198) ~[molgenis-core-ui-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.transaction.TransactionLogRepositoryDecorator.add(TransactionLogRepositoryDecorator.java:215) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.util.MySqlRepositoryExceptionTranslatorDecorator.lambda$add$81(MySqlRepositoryExceptionTranslatorDecorator.java:171) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.util.MySqlRepositoryExceptionTranslatorDecorator$$Lambda$162/1634191458.run(Unknown Source) ~[na:na]
    at org.molgenis.util.SQLExceptionTranslatorTemplate.tryCatchSQLException(SQLExceptionTranslatorTemplate.java:20) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.util.MySqlRepositoryExceptionTranslatorDecorator.add(MySqlRepositoryExceptionTranslatorDecorator.java:170) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:114) ~[molgenis-data-validation-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.AutoValueRepositoryDecorator.add(AutoValueRepositoryDecorator.java:61) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.RepositorySecurityDecorator.add(RepositorySecurityDecorator.java:184) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.support.DataServiceImpl.add(DataServiceImpl.java:168) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[spring-core-4.1.8.RELEASE.jar:1.18.0-SNAPSHOT]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$da4a6daa.add(<generated>) ~[spring-core-4.1.8.RELEASE.jar:1.18.0-SNAPSHOT]
    at org.molgenis.ontology.sorta.job.SortaJobProcessor.lambda$process$6(SortaJobProcessor.java:98) ~[molgenis-ontology-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.ontology.sorta.job.SortaJobProcessor$$Lambda$171/762042304.run(Unknown Source) ~[na:na]
    at org.molgenis.security.core.runas.RunAsSystemProxy.lambda$runAsSystem$0(RunAsSystemProxy.java:46) ~[molgenis-security-core-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.security.core.runas.RunAsSystemProxy$$Lambda$100/51851746.run(Unknown Source) ~[na:na]
    at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:60) ~[molgenis-security-core-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:45) ~[molgenis-security-core-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.ontology.sorta.job.SortaJobProcessor.process(SortaJobProcessor.java:50) ~[molgenis-ontology-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.ontology.sorta.job.SortaJobImpl.call(SortaJobImpl.java:24) ~[molgenis-ontology-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.ontology.sorta.job.SortaJobImpl.call(SortaJobImpl.java:10) ~[molgenis-ontology-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.jobs.Job.runWithAuthentication(Job.java:39) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.jobs.Job.access$000(Job.java:18) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.molgenis.data.jobs.Job$1.doInTransaction(Job.java:60) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
    at org.molgenis.data.jobs.Job.call(Job.java:53) ~[molgenis-data-1.18.0-SNAPSHOT.jar:1.18.0-SNAPSHOT]
    at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1445) [na:1.8.0_31]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_31]
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902) [na:1.8.0_31]
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689) [na:1.8.0_31]
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644) [na:1.8.0_31]
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [na:1.8.0_31]
```

**Comment by ChaoPang** [comment]
After dropping mysql database and index, the problem disappears

**Comment by fdlk** [comment]
Since we currently still store the results in the same entity, I think it could be triggered by the result entity count reaching a certain maximum.

**Comment by dennishendriksen** [comment]
After fixing the ontology (see updated dataset in issue description) I get the following error running Sorta:
```org.molgenis.data.validation.MolgenisValidationException: Name [1eopulgyqz2tl26sbnir10urn_input] is too long: maximum length is 30 characters.```.

Disabling the length check in Java and running again results in the following exception:
```Caused by: org.molgenis.data.validation.MolgenisValidationException: Qualified entity name [AAAACWBPOIQGJREFBA6ETGIAAE] not equal to entity name [e028g51hwb1mxustso0ngtyp_input]
	at org.molgenis.data.validation.meta.EntityTypeValidator.validateEntityName(EntityTypeValidator.java:254)```

**Comment by dennishendriksen** [comment]
Cannot reproduce after fixing SORTA https://github.com/molgenis/molgenis/pull/5467
