### ISSUE TITLE
ElasticSearch BulkProcessor still active while shutting down

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#4937]
#### Reproduce
Deploy to tomcat, shut down tomcat.
(For me happens when I redeploy exploded webapp on my laptop from IntelliJ)

#### Expected
Application shuts down cleanly

#### Observed
Stacktrace pops up that BulkProcessor is still active even though ElasticSearch is stopped.:

```
15:31:51.010 [RMI TCP Connection(8)-127.0.0.1] INFO  o.m.d.e.f.EmbeddedElasticSearchServiceFactory - Elastic search server stopped
02-Jun-2016 15:31:51.085 WARNING [RMI TCP Connection(8)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
02-Jun-2016 15:31:55.752 INFO [elasticsearch[Tomorrow Man][bulk_processor][T#1]] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.elasticsearch.action.bulk.BulkItemResponse$Failure]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.elasticsearch.action.bulk.BulkItemResponse$Failure]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1325)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1178)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1139)
	at org.elasticsearch.action.bulk.TransportBulkAction$2.onFailure(TransportBulkAction.java:342)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.finishAsFailed(TransportShardReplicationOperationAction.java:536)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.onFailure(TransportShardReplicationOperationAction.java:435)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.onRejection(AbstractRunnable.java:65)
	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.routeRequestOrPerformLocally(TransportShardReplicationOperationAction.java:432)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.doRun(TransportShardReplicationOperationAction.java:370)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction.doExecute(TransportShardReplicationOperationAction.java:112)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction.doExecute(TransportShardReplicationOperationAction.java:74)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:323)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:162)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:67)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:167)
	at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:327)
	at org.elasticsearch.action.bulk.BulkProcessor.access$400(BulkProcessor.java:47)
	at org.elasticsearch.action.bulk.BulkProcessor$Flush.run(BulkProcessor.java:391)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I suspect it's the elasticsearch logger appender that is logging the line 
`15:31:51.010 [RMI TCP Connection(8)-127.0.0.1] INFO  o.m.d.e.f.EmbeddedElasticSearchServiceFactory - Elastic search server stopped` to elasticsearch.

**Comment by dennishendriksen** [comment]
@fdlk Changes were made to Elasticsearch indexing, can you still reproduce this issue?

**Comment by fdlk** [comment]
The entire elasticsearch logger has gone and so has its error message.
