### ISSUE TITLE
NullPointerException when importing test-edgecases.vcf

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#5035]
#### Reproduce
Import *molgenis-annotators/src/test/resources/test-edgecases.vcf*

#### Expected
File is imported

#### Observed
```java
java.lang.NullPointerException: null
	at org.molgenis.data.vcf.utils.VcfUtils.createId(VcfUtils.java:64) ~[molgenis-data-vcf-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.vcf.format.VcfToEntity.toEntity(VcfToEntity.java:274) ~[molgenis-data-vcf-2.0.0-SNAPSHOT.jar:na]
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-16.0.1.jar:na]
	at org.molgenis.data.vcf.importer.VcfImporterService.importVcf(VcfImporterService.java:172) ~[molgenis-data-vcf-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.vcf.importer.VcfImporterService.doImport(VcfImporterService.java:62) ~[molgenis-data-vcf-2.0.0-SNAPSHOT.jar:na]
```

**Comment by tommydeboer** [comment]
Seems to be fixed.
