### ISSUE TITLE
Cannot open the wizard in dataexplorer

### ISSUE THREAD

**Issue by marieke-bijlsma** [molgenis/molgenis#5068]
#### Reproduce
1. Upload this EMX file: https://drive.google.com/open?id=0B8iNw4kI1MA2UTlpZS01a3JqZmM
2. Go to entity collections
3. Click on "wizard" button

#### Expected
Pop-up 

#### Observed
Uncaught TypeError: Cannot read property 'items' of null

ERROR o.molgenis.data.rest.RestController -
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query], all shards failed; shardFailures {[-U_dwoYCQ0ygrFCHmn06zw][molgenis][0]: SearchParseException[[molgenis][0]: from[0],size[100]: Parse Failure [Failed to parse source [{"from":0,"size":100,"sort":[{"size.raw":{"order":"asc","mode":"min"}}]}]]]; nested: QueryParsingException[[molgenis] [nested] failed to find nested object under path [size]]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:237) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:183) ~[elasticsearch-1.7.3.jar:na]
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565) ~[elasticsearch-1.7.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_31]

**Comment by dennishendriksen** [comment]
Solved in 2.0-RC, wizard opens without any errors.
