### ISSUE TITLE
Filtering on xref with INT id fails

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5185]
#### Reproduce
Import BBMRI Imaging data.
Filter cohorts imaging data attribute on an instance of 'Brain'.

#### Expected
Rows get filtered.

#### Observed
> Error! Attribute [id] query value is of type [String] instead of [Integer]

Stack trace:
```
15:50:29.179 [http-nio-8080-exec-3] INFO  o.m.data.rest.v2.RestControllerV2 - Operation failed.
org.molgenis.data.MolgenisDataException: Attribute [id] query value is of type [String] instead of [Integer]
	at org.molgenis.data.postgresql.PostgreSqlUtils.getPostgreSqlQueryValue(PostgreSqlUtils.java:192) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlQueryGenerator.getSqlWhere(PostgreSqlQueryGenerator.java:575) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlQueryGenerator.getSqlCount(PostgreSqlQueryGenerator.java:370) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlRepository.count(PostgreSqlRepository.java:139) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.AbstractRepositoryDecorator.count(AbstractRepositoryDecorator.java:67) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.AbstractRepositoryDecorator.count(AbstractRepositoryDecorator.java:67) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.elasticsearch.IndexedRepositoryDecorator.count(IndexedRepositoryDecorator.java:231) ~[molgenis-data-elasticsearch-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.AbstractRepositoryDecorator.count(AbstractRepositoryDecorator.java:67) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.EntityReferenceResolverDecorator.count(EntityReferenceResolverDecorator.java:67) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.listeners.EntityListenerRepositoryDecorator.count(EntityListenerRepositoryDecorator.java:86) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.validation.RepositoryValidationDecorator.count(RepositoryValidationDecorator.java:138) ~[molgenis-data-validation-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.AutoValueRepositoryDecorator.count(AutoValueRepositoryDecorator.java:117) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.RepositorySecurityDecorator.count(RepositorySecurityDecorator.java:76) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.support.DataServiceImpl.count(DataServiceImpl.java:61) ~[molgenis-data-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[spring-core-4.1.8.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$4cb2cc46.count(<generated>) ~[spring-core-4.1.8.RELEASE.jar:na]
	at org.molgenis.data.rest.v2.RestControllerV2.createEntityCollectionResponse(RestControllerV2.java:602) ~[molgenis-data-rest-2.0.0-SNAPSHOT.jar:na]
	at org.molgenis.data.rest.v2.RestControllerV2.retrieveEntityCollection(RestControllerV2.java:223) ~[molgenis-data-rest-2.0.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775) ~[spring-webmvc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) ~[spring-webmvc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) [spring-webmvc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) [spring-webmvc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
```

**Comment by fdlk** [comment]
MolgenisRSqlVisitor calls DataConverter.convert().

**Comment by fdlk** [comment]
Fixed by writing a String -> Object parser that parses the query values.
