### ISSUE TITLE
Reindexing can fail if a metadata edit transaction commits during reindexing

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5508]
#### Reproduce
Found in the Metadata type conversion integration tests, though the tests do not fail when this happens.
Happened twice today on my machine when I ran IntTypeEditing test.

#### Expected
Test never throws exceptions while indexing

#### Observed
```
16:52:21.470 [pool-1-thread-1] ERROR o.m.d.e.index.job.IndexJob - Index job failed
com.google.common.util.concurrent.UncheckedExecutionException: org.molgenis.data.MolgenisDataException: ; nested exception is org.postgresql.util.PSQLException: Bad value for type int : t
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4881) ~[guava-19.0.jar:na]
	at org.molgenis.data.cache.l2.L2Cache.get(L2Cache.java:92) ~[classes/:na]
	at org.molgenis.data.cache.l2.L2CacheRepositoryDecorator.findOneById(L2CacheRepositoryDecorator.java:74) ~[classes/:na]
	at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.findOneById(L1CacheRepositoryDecorator.java:85) ~[classes/:na]
	at org.molgenis.data.elasticsearch.IndexedRepositoryDecorator.findOneById(IndexedRepositoryDecorator.java:110) ~[classes/:na]
	at org.molgenis.data.AbstractRepositoryDecorator.findOneById(AbstractRepositoryDecorator.java:90) ~[classes/:na]
	at org.molgenis.data.AbstractRepositoryDecorator.findOneById(AbstractRepositoryDecorator.java:90) ~[classes/:na]
	at org.molgenis.data.EntityReferenceResolverDecorator.findOneById(EntityReferenceResolverDecorator.java:115) ~[classes/:na]
	at org.molgenis.data.listeners.EntityListenerRepositoryDecorator.findOneById(EntityListenerRepositoryDecorator.java:103) ~[classes/:na]
	at org.molgenis.data.validation.RepositoryValidationDecorator.findOneById(RepositoryValidationDecorator.java:154) ~[classes/:na]
	at org.molgenis.data.RepositorySecurityDecorator.findOneById(RepositorySecurityDecorator.java:96) ~[classes/:na]
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$findOneById$6(TransactionalRepositoryDecorator.java:86) ~[classes/:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.findOneById(TransactionalRepositoryDecorator.java:86) ~[classes/:na]
	at org.molgenis.data.support.DataServiceImpl.findOneById(DataServiceImpl.java:80) ~[classes/:na]
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[spring-core-4.1.8.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$4b978b4a.findOneById(<generated>) ~[spring-core-4.1.8.RELEASE.jar:na]
	at org.molgenis.data.elasticsearch.index.job.IndexJob.rebuildIndexOneEntity(IndexJob.java:185) [classes/:na]
	at org.molgenis.data.elasticsearch.index.job.IndexJob.performAction(IndexJob.java:126) [classes/:na]
	at org.molgenis.data.elasticsearch.index.job.IndexJob.performIndexActions(IndexJob.java:84) [classes/:na]
	at org.molgenis.data.elasticsearch.index.job.IndexJob.call(IndexJob.java:58) [classes/:na]
	at org.molgenis.data.elasticsearch.index.job.IndexJob.call(IndexJob.java:32) [classes/:na]
	at org.molgenis.data.jobs.Job.runWithAuthentication(Job.java:89) [classes/:na]
	at org.molgenis.data.jobs.Job.tryRunWithAuthentication(Job.java:74) [classes/:na]
	at org.molgenis.data.jobs.Job.call(Job.java:44) [classes/:na]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
Caused by: org.molgenis.data.MolgenisDataException: ; nested exception is org.postgresql.util.PSQLException: Bad value for type int : t
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:79) ~[classes/:na]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:41) ~[classes/:na]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:660) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:695) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:727) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:737) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:787) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.molgenis.data.postgresql.PostgreSqlRepository$1.getBatch(PostgreSqlRepository.java:415) ~[classes/:na]
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:36) ~[classes/:na]
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:14) ~[classes/:na]
	at org.molgenis.util.BatchingIterable$1.nextBatch(BatchingIterable.java:138) ~[classes/:na]
	at org.molgenis.util.BatchingIterable$1.hasNext(BatchingIterable.java:58) ~[classes/:na]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811) ~[na:1.8.0_91]
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:1.8.0_91]
	at org.molgenis.data.postgresql.PostgreSqlRepository.findOne(PostgreSqlRepository.java:152) ~[classes/:na]
	at org.molgenis.data.postgresql.PostgreSqlRepository.findOneById(PostgreSqlRepository.java:166) ~[classes/:na]
	at org.molgenis.data.cache.l2.L2Cache$1.load(L2Cache.java:186) ~[classes/:na]
	at org.molgenis.data.cache.l2.L2Cache$1.load(L2Cache.java:177) ~[classes/:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-19.0.jar:na]
	... 34 common frames omitted
Caused by: org.postgresql.util.PSQLException: Bad value for type int : t
	at org.postgresql.jdbc.PgResultSet.toInt(PgResultSet.java:2835) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2050) ~[postgresql-9.4.1211.jar:9.4.1211]
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2485) ~[postgresql-9.4.1211.jar:9.4.1211]
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getInt(NewProxyResultSet.java:451) ~[c3p0-0.9.5.2.jar:0.9.5.2]
	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapValue(PostgreSqlEntityFactory.java:158) ~[classes/:na]
	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapValue(PostgreSqlEntityFactory.java:94) ~[classes/:na]
	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapRow(PostgreSqlEntityFactory.java:77) ~[classes/:na]
	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapRow(PostgreSqlEntityFactory.java:49) ~[classes/:na]
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:708) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	... 53 common frames omitted
```

**Comment by fdlk** [comment]
The underlying issue is that PostgresqlRepository contains a POJO for the entityType so if metadata changes after it's created, the query will interpret the new data with old metadata.

**Comment by fdlk** [comment]
Going to take a look if I can still reproduce it with the extra postgres flag

**Comment by fdlk** [comment]
Can still reproduce with version 6.1 and flag `autosave=CONSERVATIVE`
