### ISSUE TITLE
getCachedOwnAttrs can nullpointer

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#5512]
#### Reproduce
Unsure, threading issue? Happened in the integration test. Rerun of the test succeeded

#### Expected
If your metadata is correct, getCachedOwnAttrs should never nullpointer

#### Observed
```
java.lang.NullPointerException
	at org.molgenis.data.meta.model.EntityType.lambda$getCachedOwnAttrs$12(EntityType.java:802)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.molgenis.data.meta.model.EntityType.getCachedOwnAttrs(EntityType.java:802)
	at org.molgenis.data.meta.model.EntityType.lambda$getOwnAtomicAttributes$11(EntityType.java:726)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at org.molgenis.data.meta.model.EntityType.getMappedByAttributes(EntityType.java:746)
	at org.molgenis.data.index.IndexActionRepositoryDecorator.registerRefEntityIndexActions(IndexActionRepositoryDecorator.java:122)
	at org.molgenis.data.index.IndexActionRepositoryDecorator.deleteAll(IndexActionRepositoryDecorator.java:72)
	at org.molgenis.data.EntityReferenceResolverDecorator.deleteAll(EntityReferenceResolverDecorator.java:190)
	at org.molgenis.data.listeners.EntityListenerRepositoryDecorator.deleteAll(EntityListenerRepositoryDecorator.java:173)
	at org.molgenis.data.validation.RepositoryValidationDecorator.deleteAll(RepositoryValidationDecorator.java:198)
	at org.molgenis.data.AbstractRepositoryDecorator.deleteAll(AbstractRepositoryDecorator.java:146)
	at org.molgenis.data.RepositorySecurityDecorator.deleteAll(RepositorySecurityDecorator.java:172)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$deleteAll$17(TransactionalRepositoryDecorator.java:180)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.deleteAll(TransactionalRepositoryDecorator.java:178)
	at org.molgenis.data.support.DataServiceImpl.deleteAll(DataServiceImpl.java:152)
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$5ea7a5f7.deleteAll(<generated>)
	at org.molgenis.integrationtest.platform.PlatformIT.lambda$afterMethod$1(PlatformIT.java:206)
	at org.molgenis.security.core.runas.RunAsSystemProxy.lambda$runAsSystem$0(RunAsSystemProxy.java:47)
	at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:61)
	at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:45)
	at org.molgenis.integrationtest.platform.PlatformIT.afterMethod(PlatformIT.java:202)
```

**Comment by dennishendriksen** [comment]
@fdlk EntityType is not thread-safe. Is this required?
