### ISSUE TITLE
Elasticsearch indexing performance

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5519]
#### Reproduce
- Bootstrap the application with an empty database

#### Expected
- Indexing of initial database data takes about 1-2 seconds

#### Observed
- Indexing of initial database data takes about 10 seconds

**Comment by dennishendriksen** [comment]
The MOLGENIS indexing thread (pool-2-thread-1) is waiting (=orange) instead of running (=green) most of the time: 
![esperf](https://cloud.githubusercontent.com/assets/2477186/20264957/79220edc-aa6e-11e6-9e4b-426d896badaa.png)

1. Calling ```ElasticsearchUtils.index(Stream<IndexRequest> requests, boolean awaitCompletion)``` with ```awaitCompletion=true```  instead of ```awaitCompletion=false``` speeds up indexing by a factor of 3.
2. Configuring BulkProcessorFactory.build with ```setConcurrentRequests(5)``` speeds up indexing by about 500 ms (might not be significant)
3. Setting ```ElasticsearchIndexCreator.createIndexInternal``` max_gram to 2 instead of 10 speeds up indexing by about 1s

Preliminary findings indicate that we should aim for one bulk process indexing step for one transaction containing documents of different entity types.

**Comment by marikaris** [comment]
Just tested. It works in 1-2 seconds!

**Comment by dennishendriksen** [comment]
@marikaris Bootstrapping the application (latest molgenis/master branch) with an empty database on my local machine takes about 16 seconds. The issue seems to be getting worse instead of being resolved. Could you check your logs and compare them with mine?

```
07:44:03.969 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (1, Indexing sys_Language)
07:44:04.277 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (2, Indexing sys_set_hpo)
07:44:04.566 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (3, Indexing sys_ont_OntologyTerm)
07:44:04.775 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (4, Indexing sys_App)
07:44:04.925 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (5, Indexing sys_ont_Ontology)
07:44:04.999 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (6, Indexing sys_ont_OntologyTermDynamicAnnotation)
07:44:05.133 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (7, Indexing sys_sec_RecoveryCode)
07:44:05.292 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (8, Indexing sys_job_SortaJobExecution)
07:44:05.530 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (9, Indexing sys_sec_GroupAuthority)
07:44:06.782 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (10, Indexing sys_set_CGD)
07:44:06.927 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (11, Indexing sys_set_StyleSheet)
07:44:07.088 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (12, Indexing sys_set_cadd)
07:44:07.215 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (13, Indexing sys_scr_Script)
07:44:07.395 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (14, Indexing sys_job_ScriptJobExecution)
07:44:07.512 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (15, Indexing sys_job_OneClickImportJobExecution)
07:44:07.661 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (16, Indexing sys_L10nString)
07:44:08.066 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (17, Indexing sys_set_app)
07:44:08.227 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (18, Indexing sys_set_OpenCpuSettings)
07:44:08.373 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (19, Indexing sys_map_MappingProject)
07:44:08.789 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (20, Indexing sys_md_Attribute)
07:44:11.207 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (21, Indexing sys_set_gonl)
07:44:11.361 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (22, Indexing sys_sec_GroupMember)
07:44:11.508 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (23, Indexing sys_sec_UserAuthority)
07:44:11.967 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (24, Indexing sys_sec_Group)
07:44:12.280 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (25, Indexing sys_mail_JavaMailProperty)
07:44:12.544 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (26, Indexing sys_set_fitcon)
07:44:12.668 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (27, Indexing sys_job_ScheduledJobType)
07:44:12.858 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (28, Indexing sys_ont_OntologyTermSynonym)
07:44:12.969 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (29, Indexing sys_set_clinvar)
07:44:13.080 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (30, Indexing sys_set_auth)
07:44:13.197 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (31, Indexing sys_set_OMIM)
07:44:13.294 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (32, Indexing sys_job_ScheduledJob)
07:44:13.381 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (33, Indexing sys_scr_ScriptType)
07:44:13.506 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (34, Indexing sys_genomebrowser_GenomeBrowserSettingsMetadata)
07:44:13.642 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (35, Indexing sys_ImportRun)
07:44:13.762 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (36, Indexing sys_set_exac)
07:44:13.914 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (37, Indexing sys_job_AnnotationJobExecution)
07:44:14.022 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (38, Indexing sys_set_directory)
07:44:14.156 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (39, Indexing sys_scr_ScriptParameter)
07:44:14.283 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (40, Indexing sys_sec_Token)
07:44:14.399 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (41, Indexing sys_Plugin)
07:44:14.556 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (42, Indexing sys_md_Package)
07:44:15.675 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (43, Indexing sys_set_Gavin)
07:44:15.867 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (44, Indexing sys_map_EntityMapping)
07:44:15.970 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (45, Indexing sys_set_thousandgenomes)
07:44:16.080 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (46, Indexing sys_ont_OntologyTermHit)
07:44:16.202 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (47, Indexing sys_set_snpEff)
07:44:16.297 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (48, Indexing sys_set_MailSettings)
07:44:16.435 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (49, Indexing sys_md_EntityType)
07:44:17.142 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (50, Indexing sys_FileMeta)
07:44:17.264 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (51, Indexing sys_ont_OntologyTermNodePath)
07:44:17.429 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (52, Indexing sys_job_FileIngestJobExecution)
07:44:17.541 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (53, Indexing sys_map_AttributeMapping)
07:44:17.668 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (54, Indexing sys_ont_TermFrequency)
07:44:17.804 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (55, Indexing sys_job_MappingJobExecution)
07:44:17.944 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (56, Indexing sys_sec_UserSecret)
07:44:18.051 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (57, Indexing sys_job_AmazonBucketJobExecution)
07:44:18.178 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (58, Indexing sys_set_dataexplorer)
07:44:18.421 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (59, Indexing sys_set_dann)
07:44:18.523 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (60, Indexing sys_StaticContent)
07:44:18.615 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (61, Indexing sys_job_GavinJobExecution)
07:44:18.695 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (62, Indexing sys_sec_User)
07:44:18.783 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (63, Indexing sys_md_Tag)
07:44:18.863 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (64, Indexing sys_genomebrowser_GenomeBrowserAttributesMetadata)
07:44:18.960 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (65, Indexing sys_map_MappingTarget)
07:44:19.029 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (66, Executed all index actions, cleaning up the actions...)
07:44:19.049 [pool-3-thread-1] DEBUG o.m.data.jobs.model.JobExecution - progress (66, Cleaned up the actions.)
07:44:19.050 [pool-3-thread-1] INFO  o.m.data.jobs.model.JobExecution - Refresh index start
07:44:19.314 [pool-3-thread-1] INFO  o.m.data.jobs.model.JobExecution - Refresh index done
07:44:19.314 [pool-3-thread-1] INFO  o.m.data.jobs.model.JobExecution - Finished indexing for transaction id: [aaaacxu52bnpagg36jrg2zaaae]
07:44:19.354 [pool-3-thread-1] INFO  o.m.data.jobs.model.JobExecution - Execution successful. Time spent: 16s 316ms
```

**Comment by marikaris** [comment]
Related:
When loading VKGL models + data and running scripts, a huge amount of indexing jobs are created (all the same jobs):
![screen shot 2018-10-01 at 13 51 05](https://user-images.githubusercontent.com/10075439/46287171-f663f880-c581-11e8-8be9-3ef95c8d6f4e.png)
And after reindexing, a new reindexing job starts for each time a job is created. During the process, stacktraces might be thrown:
```
13:47:05.133 [ajp-bio-8009-exec-11] ERROR o.m.d.e.client.ClientFacade -
org.elasticsearch.index.IndexNotFoundException: no such index
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.infe(IndexNameExpressionResolver.java:676)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:630)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:578)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:168)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:140)
	at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:263)
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:186)
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:65)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:64)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:54)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1544)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110)
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1501)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1385)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```
