### ISSUE TITLE
Error creating new automatic import entry

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5535]
#### Reproduce
- Import [city.xlsx](https://github.com/molgenis/molgenis/files/591515/city.xlsx)
- Extract [city.zip](https://github.com/molgenis/molgenis/files/591516/city.zip) and put the resulting csv on your dropbox
- Select the 'Automatic imports' plugin in the 'Plugins' menu
- Select the '+' button
- Fill in the form
  - Url: the url to the city.csv on your dropbox
  - Target EntityMetaData: city
  - CronExpression: 0/20 * * * * ?
  - Active: yes
  - Failure email: your email address
- Select 'Save changes'

#### Expected
- Wait for half a minute, in the 'city' import jobs table should appear rows, Job status 'SUCCESS'

#### Observed
- Error! An error occurred. Please contact the administrator.
Uncaught TypeError: Cannot read property 'fullName' of undefined

**Comment by dennishendriksen** [comment]
I've received the following stacktrace by email:
```
17:00:00.034 INFO  - Execution started.
17:00:00.034 DEBUG - progress (0, Downloading url 'https://www.dropbox.com/s/s85794hh1sdr31e/city.csv?dl=0')
17:00:02.252 DEBUG - progress (1, Importing...)
17:00:02.434 ERROR - Failed
java.lang.NullPointerException: Null id
        at org.molgenis.data.AutoValue_EntityKey.<init>(AutoValue_EntityKey.java:20) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.EntityKey.create(EntityKey.java:18) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.cache.utils.CombinedEntityCache.put(CombinedEntityCache.java:86) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.cache.l1.L1Cache.put(L1Cache.java:137) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.lambda$add$0(L1CacheRepositoryDecorator.java:61) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372) ~[na:1.8.0_112]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_112]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[na:1.8.0_112]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294) ~[na:1.8.0_112]
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[na:1.8.0_112]
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161) ~[na:1.8.0_112]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[na:1.8.0_112]
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:1.8.0_112]
        at com.google.common.collect.Iterators$6.hasNext(Iterators.java:638) ~[guava-19.0.jar:na]
        at java.util.Iterator.forEachRemaining(Iterator.java:115) ~[na:1.8.0_112]
        at org.molgenis.data.postgresql.PostgreSqlRepository.addBatching(PostgreSqlRepository.java:431) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.postgresql.PostgreSqlRepository.add(PostgreSqlRepository.java:255) ~[molgenis-data-postgresql-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:158) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.add(L1CacheRepositoryDecorator.java:63) ~[molgenis-data-cache-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.elasticsearch.IndexedRepositoryDecorator.add(IndexedRepositoryDecorator.java:64) ~[molgenis-data-elasticsearch-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:158) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.index.IndexActionRepositoryDecorator.add(IndexActionRepositoryDecorator.java:89) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.EntityReferenceResolverDecorator.add(EntityReferenceResolverDecorator.java:202) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.listeners.EntityListenerRepositoryDecorator.add(EntityListenerRepositoryDecorator.java:185) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:90) ~[molgenis-data-validation-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:158) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.RepositorySecurityDecorator.add(RepositorySecurityDecorator.java:186) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$add$19(TransactionalRepositoryDecorator.java:198) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.molgenis.data.transaction.TransactionalRepositoryDecorator.add(TransactionalRepositoryDecorator.java:198) ~[molgenis-data-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.importer.ImportWriter.insertIntoRepo(ImportWriter.java:665) ~[molgenis-data-import-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.importer.ImportWriter.update(ImportWriter.java:567) ~[molgenis-data-import-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.importer.ImportWriter.importData(ImportWriter.java:186) ~[molgenis-data-import-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.importer.ImportWriter.doImport(ImportWriter.java:100) ~[molgenis-data-import-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.importer.ImportWriter$$FastClassBySpringCGLIB$$52fbfda4.invoke(<generated>) ~[spring-core-4.1.8.RELEASE.jar:2.0.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.molgenis.data.importer.ImportWriter$$EnhancerBySpringCGLIB$$727314f4.doImport(<generated>) ~[spring-core-4.1.8.RELEASE.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.importer.EmxImportService.doImport(EmxImportService.java:85) ~[molgenis-data-import-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.importer.EmxImportService.doImport(EmxImportService.java:72) ~[molgenis-data-import-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.file.ingest.execution.FileIngester.ingest(FileIngester.java:64) ~[molgenis-file-ingester-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.file.ingest.execution.FileIngestJob.call(FileIngestJob.java:34) ~[molgenis-file-ingester-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.file.ingest.execution.FileIngestJob.call(FileIngestJob.java:9) ~[molgenis-file-ingester-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.jobs.Job.runWithAuthentication(Job.java:89) ~[molgenis-jobs-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.jobs.Job.tryRunWithAuthentication(Job.java:74) ~[molgenis-jobs-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.data.jobs.Job.lambda$call$0(Job.java:40) ~[molgenis-jobs-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.molgenis.data.jobs.Job.call(Job.java:40) ~[molgenis-jobs-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.file.ingest.FileIngesterQuartzJob.run(FileIngesterQuartzJob.java:80) [molgenis-file-ingester-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.file.ingest.FileIngesterQuartzJob.lambda$execute$0(FileIngesterQuartzJob.java:60) [molgenis-file-ingester-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.security.core.runas.RunAsSystemProxy.lambda$runAsSystem$0(RunAsSystemProxy.java:47) ~[molgenis-security-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:61) ~[molgenis-security-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:45) ~[molgenis-security-core-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.molgenis.file.ingest.FileIngesterQuartzJob.execute(FileIngesterQuartzJob.java:60) [molgenis-file-ingester-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.2.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.2.2.jar:na]
```
