### ISSUE TITLE
Index job failed running integration test

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#5638]
### How to Reproduce
- Run IntAttributeTypeUpdateTest

### Expected behavior
- Test succeeds, no errors in logs

### Observed behavior
- Test succeeds with the following errors in the logs:
```
11:33:14.887 [main] INFO  o.m.data.meta.MetaDataServiceImpl - Removed entity [MAIN_ENTITY]
11:33:14.911 [main] INFO  o.m.data.meta.MetaDataServiceImpl - Removed entity [REFERENCE_ENTITY]
11:33:14.977 [pool-1-thread-1] ERROR o.m.d.e.index.job.IndexJob - Index job failed
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT this."id", this."mainAttribute" FROM "MAIN_ENTITY" AS this]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "MAIN_ENTITY" does not exist
  Position: 45
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
```

**Comment by bartcharbon** [comment]
After https://github.com/molgenis/molgenis/pull/8837 no unexplained stack traces remain when running the integration tests
