### ISSUE TITLE
When deleting a row in the EntityType table, I get a RuntimeException: Unknown attribute for column name [fullName]

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#5773]
### How to Reproduce
- Import TypeTest
[it_emx_datatypes.xlsx](https://github.com/molgenis/molgenis/files/726611/it_emx_datatypes.xlsx)
- Go to the EntityType table in the data explorer
- Try to delete the Location entity

### Expected behavior
Location is deleted

### Observed behavior
```
java.lang.RuntimeException: Unknown attribute for column name [fullName]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.getAttributeName(PostgreSqlExceptionTranslator.java:460) ~[molgenis-data-postgresql-2.1.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.translateForeignKeyViolation(PostgreSqlExceptionTranslator.java:330) ~[molgenis-data-postgresql-2.1.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:109) ~[molgenis-data-postgresql-2.1.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:70) ~[molgenis-data-postgresql-2.1.0-SNAPSHOT.jar:na]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:58) ~[molgenis-data-postgresql-2.1.0-SNAPSHOT.jar:na]
```

**Comment by Mark-de-Haan** [comment]
No longer an issue
