### ISSUE TITLE
home page logs nullpointer after clean deploy

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/molgenis#5950]
### How to Reproduce
drop db and index
startup molgenis 3.0.1
surf to the landing page of the server

### Expected behavior
home plugin shows and no errors are logged

### Observed behavior
home pluging shows fine
But the catalina.out shows:
16:05:07.683 [ajp-bio-8009-exec-2] ERROR o.molgenis.data.rest.RestController -
java.lang.NullPointerException: null
        at org.molgenis.data.rest.RestController.getAttributePostInternal(RestController.java:1064) ~[molgenis-data-rest-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
        at org.molgenis.data.rest.RestController.retrieveEntityAttributeMeta(RestController.java:190) ~[molgenis-data-rest-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
        at org.molgenis.data.rest.RestController$$FastClassBySpringCGLIB$$dc749bba.invoke(<generated>) ~[molgenis-data-rest-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]

**Comment by bartcharbon** [comment]
correction: every plugin results in this stacktrace

I found this behavior on molgenis62, molgenis42 does not show this behavior with the same war. Main difference is that m42 has content on its homepage and therefore a entry in the database for the "home" staticcontent
