### ISSUE TITLE
Job logs can exceed max log size, disastrous consequences 

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#5985]
### How to Reproduce
Use RD connect version of 3.0
Data in Marieke and Mariska RD connect folder on drive
Upload: RD connect model v20, diseases, tngb, ncl, bioner, ring14
Upload mappings (with new admin id)
Map to new entity

Molgenis 80 failed to run when this error occured during bootstrapping!

### Expected behavior
Mappings succeed without errors

### Observed behavior
Mapping succeeds but during indexing, the log keeps throwing this error message:
`' for attribute 'Log' of entity 'sys_idx_IndexJobExecution'.Value must be less than or equal to 65535 characters
	at org.molgenis.data.validation.RepositoryValidationDecorator.lambda$validate$0(RepositoryValidationDecorator.java:110) ~[molgenis-data-validation-3.0.0.jar:3.0.0]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_112]
	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405) ~[na:1.8.0_112]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_112]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_112]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_112]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_112]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_112]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_112]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_112]
	at org.molgenis.data.validation.RepositoryValidationDecorator.update(RepositoryValidationDecorator.java:55) ~[molgenis-data-validation-3.0.0.jar:3.0.0]
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:131) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.RepositorySecurityDecorator.update(RepositorySecurityDecorator.java:128) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$update$11(TransactionalRepositoryDecorator.java:120) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.update(TransactionalRepositoryDecorator.java:118) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:131) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.support.DataServiceImpl.update(DataServiceImpl.java:121) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$2b061ccf.update(<generated>) ~[molgenis-data-3.0.0.jar:3.0.0]
	at org.molgenis.data.jobs.JobExecutionUpdaterImpl.tryUpdate(JobExecutionUpdaterImpl.java:40) [molgenis-jobs-3.0.0.jar:3.0.0]
	at org.molgenis.data.jobs.JobExecutionUpdaterImpl.lambda$updateInternal$1(JobExecutionUpdaterImpl.java:33) [molgenis-jobs-3.0.0.jar:3.0.0]
	at org.molgenis.security.core.runas.RunAsSystemProxy.lambda$runAsSystem$0(RunAsSystemProxy.java:47) ~[molgenis-security-core-3.0.0.jar:3.0.0]
	at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:61) ~[molgenis-security-core-3.0.0.jar:3.0.0]
	at org.molgenis.security.core.runas.RunAsSystemProxy.runAsSystem(RunAsSystemProxy.java:45) ~[molgenis-security-core-3.0.0.jar:3.0.0]
	at org.molgenis.data.jobs.JobExecutionUpdaterImpl.updateInternal(JobExecutionUpdaterImpl.java:33) [molgenis-jobs-3.0.0.jar:3.0.0]
	at org.molgenis.data.jobs.JobExecutionUpdaterImpl.lambda$update$0(JobExecutionUpdaterImpl.java:28) [molgenis-jobs-3.0.0.jar:3.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_112]`

**Comment by fdlk** [comment]
Same for progress message, if it exceeds 255 bytes, for example if it contains an error message, it cannot update the execution.

**Comment by marikaris** [comment]
`Apr 25, 2017 9:04:16 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Apr 25, 2017 9:04:16 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
09:04:17.337 [localhost-startStop-1] INFO  o.m.d.i.i.IdCardIndexerServiceImpl - Scheduler stopped
09:04:17.426 [localhost-startStop-1] INFO  o.m.d.e.f.EmbeddedElasticSearchServiceFactory - Elastic search server stopped
Apr 25, 2017 9:04:17 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Apr 25, 2017 9:04:17 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [ForkJoinPool.commonPool-worker-1] but has failed to stop it. This is very likely to create a memory leak.
Apr 25, 2017 9:04:17 AM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@63d77bd2]) and a value of type [org.springframework.security.core.context.SecurityContextImpl] (value [org.springframework.security.core.context.SecurityContextImpl@ffffffff: Null authentication]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Apr 25, 2017 9:04:17 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /srv/molgenis/apache-tomcat-7.0.70/webapps/ROOT.war has finished in 35,449 ms
Apr 25, 2017 9:04:17 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /srv/molgenis/apache-tomcat-7.0.70/webapps/host-manager
Apr 25, 2017 9:04:17 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Apr 25, 2017 9:04:17 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /srv/molgenis/apache-tomcat-7.0.70/webapps/host-manager has finished in 135 ms
Apr 25, 2017 9:04:17 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Apr 25, 2017 9:04:17 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Apr 25, 2017 9:04:17 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 155611 ms`

**Comment by marikaris** [comment]
[bootstrap_fail_log.txt](https://github.com/molgenis/molgenis/files/955143/bootstrap_fail_log.txt)
