### ISSUE TITLE
Mapping service map tab throws errors

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6057]
### How to Reproduce
Import [TypeTest](https://github.com/molgenis/molgenis/files/929578/it_emx_datatypes.xlsx)
Map TypeTest to TypeTest
Go into attribute mapping for xcategorical
xcategorical is selected, so click the map tab

### Expected behaviour
I can use the UI to select which source reference IDs map to which target reference IDs

### Observed behaviour
```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.molgenis.data.support.DynamicEntity.getString(DynamicEntity.java:111) ~[molgenis-data-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at org.molgenis.data.support.EntityWithComputedAttributes.getString(EntityWithComputedAttributes.java:183) ~[molgenis-data-4.0.0-SNAPSHOT.jar:4.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458) ~[freemarker-2.3.23.jar:2.3.23]
	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:71) ~[freemarker-2.3.23.jar:2.3.23]
```

**Comment by tommydeboer** [comment]
Already fixed.
