### ISSUE TITLE
I can not delete data that is created with the metadata-manager

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6253]
### How to Reproduce

```bash
git clone https://github.com/Mark-de-Haan/molgenis/tree/feature/metadata-manager
cd molgenis/metadata-manager/src/main/frontend
yarn install
yarn run dev
```
Run localhost:8080 and login as admin
Reload localhost:3000

Create a New entity
Add one attribute as id attribute
Save the entity, you can find it in the dataexplorer

Try and delete the new entity either via dataexplorer or the metadata-manager

Used API call:` '/api/v1/<entityTypeId>/meta'`, method = "DELETE"

EntityType created with following call:
adres: `http://localhost:3000/metadata-manager-service/entityType`
body: 
```
{"id":"aaaacxhd4oolgkx6sicqwdyaae","label":"Test12345abc","description":"Test","abstract0":false,"backend":"PostgreSQL","package0":{"id":"base","label":"Default"},"attributes":[{"id":"aaaacxhd4pe32kx6sicqwdyaae","name":"id","type":"STRING","nullable":false,"auto":false,"visible":true,"label":"id","description":"id","aggregatable":false,"enumOptions":[],"readonly":false,"unique":true,"tags":[],"sequenceNumber":0,"isNew":true}],"tags":[],"idAttribute":{"id":"aaaacxhd4pe32kx6sicqwdyaae","name":"id","type":"STRING","nullable":false,"auto":false,"visible":true,"label":"id","description":"id","aggregatable":false,"enumOptions":[],"readonly":false,"unique":true,"tags":[],"sequenceNumber":0,"isNew":true},"lookupAttributes":[],"isNew":true}
```

### Expected behavior
The Entity is deleted

### Observed behavior
```
10:37:58.596 [http-bio-8080-exec-4] ERROR o.molgenis.data.rest.RestController - 
org.molgenis.data.MolgenisDataException: ; nested exception is org.postgresql.util.PSQLException: ERROR: function validate_update_<ENTITY_TYPE_ID>#48f1f857() does not exist
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:97)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:59)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:443)
	at org.molgenis.data.postgresql.PostgreSqlRepositoryCollection.dropTables(PostgreSqlRepositoryCollection.java:153)
	at org.molgenis.data.postgresql.PostgreSqlRepositoryCollection.deleteRepository(PostgreSqlRepositoryCollection.java:126)
	at org.molgenis.data.postgresql.PostgreSqlRepositoryCollectionDecorator.deleteRepository(PostgreSqlRepositoryCollectionDecorator.java:51)
	at org.molgenis.data.RepositoryCollectionDecorator.deleteRepository(RepositoryCollectionDecorator.java:90)
	at org.molgenis.data.index.IndexActionRepositoryCollectionDecorator.deleteRepository(IndexActionRepositoryCollectionDecorator.java:46)
	at org.molgenis.data.meta.EntityTypeRepositoryDecorator.deleteEntityRepository(EntityTypeRepositoryDecorator.java:189)
	at org.molgenis.data.meta.EntityTypeRepositoryDecorator.deleteEntityType(EntityTypeRepositoryDecorator.java:167)
	at org.molgenis.data.meta.EntityTypeRepositoryDecorator.deleteById(EntityTypeRepositoryDecorator.java:80)
	at org.molgenis.data.AbstractRepositoryDecorator.deleteById(AbstractRepositoryDecorator.java:143)
	at org.molgenis.data.AbstractRepositoryDecorator.deleteById(AbstractRepositoryDecorator.java:143)
	at org.molgenis.data.security.meta.EntityTypeRepositorySecurityDecorator.deleteById(EntityTypeRepositorySecurityDecorator.java:267)
	at org.molgenis.data.CascadeDeleteRepositoryDecorator.deleteById(CascadeDeleteRepositoryDecorator.java:57)
```

**Comment by dennishendriksen** [comment]
In order to get the metadata manager on your branch running I had to:
- Install Yarn v0.24.6
- Upgrade my local NodeJS from 6.9.2 to 6.11.0
- Update "node": ">= 6.11.0" in molgenis-metadata-manager\src\main\frontend\package.json
- Run yarn on a shell opened as Administrator

Without these steps the build failed on a npm-sass error with a suggested npm --force command that resulted in a missing Python 2.x error.
