### ISSUE TITLE
Importer crashes due to out of memory error when importing large file

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#6361]
### How to Reproduce
Import [lifelines-emx-demo.xlsx](https://github.com/molgenis/molgenis/files/1135116/lifelines-emx-demo.xlsx)

### Expected behavior
Import succeeds

### Observed behavior
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.lang.StringCoding.safeTrim(StringCoding.java:79)
	at java.lang.StringCoding.access$300(StringCoding.java:50)
	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:305)
	at java.lang.StringCoding.encode(StringCoding.java:344)
	at java.lang.String.getBytes(String.java:918)
	at java.io.UnixFileSystem.list(Native Method)
	at java.io.File.list(File.java:1122)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:491)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1757)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:333)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1370)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1542)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1552)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1520)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Mark-de-Haan** [comment]
Caused by VM setting  `-Xmx1G`
Should be `-Xmx2G`
