### ISSUE TITLE
When I put a css file in the webapps/styles folder, I receive big stacktrace while it works

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6624]
### How to Reproduce
Make styles folder in webapps folder of tomcat
Go to your molgenis, go to admin settings
put ../../../../styles/yourcustomstyle.css in css href

### Expected behavior
Styling works (it does) and no stacktraces

### Observed behavior
Styling works but stacktraces:
```
Caused by: java.lang.IllegalArgumentException: resource /css/../../../../styles/hide_copy_and_delete.css relative to org.molgenis.util.ResourceFingerprintRegistry not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383) ~[guava-21.0.jar:na]
	at com.google.common.io.Resources.getResource(Resources.java:209) ~[guava-21.0.jar:na]
	at org.molgenis.util.ResourceUtils.getBytes(ResourceUtils.java:62) ~[molgenis-core-4.1.0.jar:4.1.0]
	at org.molgenis.util.ResourceFingerprintRegistry.createFingerprint(ResourceFingerprintRegistry.java:38) ~[molgenis-core-4.1.0.jar:4.1.0]
	at org.molgenis.util.ResourceFingerprintRegistry.getFingerprint(ResourceFingerprintRegistry.java:30) ~[molgenis-core-4.1.0.jar:4.1.0]
	at org.molgenis.util.ResourceFingerprintRegistry.getFingerprint(ResourceFingerprintRegistry.java:22) ~[molgenis-core-4.1.0.jar:4.1.0]
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458) ~[freemarker-2.3.23.jar:2.3.23]
	at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:52) ~[freemarker-2.3.23.jar:2.3.23]
	at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:48) ~[freemarker-2.3.23.jar:2.3.23]
	at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:62) ~[freemarker-2.3.23.jar:2.3.23]
	... 141 common frames omitted
```

the css, which hides the copy and delete button of entitytypes: 
```css
#dropdownMenu1{display:none;}
#copy-data-btn{display:none;}
```

**Comment by ConnorStroomberg** [comment]
As far as i can see ( maybe @dennishendriksen can have a look, it looks like @dennishendriksen wrote most of the original code around the part of the application) from the code this was never designed to work as described in the 'how to reproduce steps'. The resources ( .css , .js, ...)  need to be bundled with the jars. Using the settings in is only possible to reference a previously bundled .css file. If we want to change this ( i do not think we want this) we would need to update the server config allow serving files from additional locations.  

Maybe its better to have a story where some additional css code or css file can be uploaded using the admin interface. We could reuse/refactor parts of the theme upload to do this. And use the file store to store the css code.

**Comment by dennishendriksen** [comment]
> this was never designed to work as described in the 'how to reproduce steps'
Indeed

@marikaris In versions < 4.1 this used to work?

**Comment by dennishendriksen** [comment]
Workaround:

Admin > Settings > Tracking footer
```
$(function () {
    $('#dropdownMenu1').css('display', 'none');
    $('#copy-data-btn').css('display', 'none');
});
```

**Comment by ConnorStroomberg** [comment]
@dennishendriksen  evil work around , i like it :)

**Comment by dennishendriksen** [comment]
@marikaris Could you create a story in the backlog to add data explorer settings to enable/disable copy functionality and enable/disable download functionality so that this workaround will become obsolete?
