### ISSUE TITLE
When filtering in the dataexplorer with a huge dataset, the number of entries is correct after a few refreshes

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#6655]
### How to Reproduce
Load the model and data of VKGL (contact me please, I cannot put it online, but I made an export to reproduce this)
Go to the consensus table
Filter consensus classification on "Opposite classification"

### Expected behavior
All 33 results are shown

### Observed behavior
Less results are shown, when i refresh i receive more, I have to refresh until 33 is reached

**Comment by fdlk** [comment]
@marikaris Could it be that the dataset was in the process of being reindexed?

**Comment by marikaris** [comment]
No, I though the same but when emptying the cache and reloading it happens everytime again

**Comment by marikaris** [comment]
Little investigation, some observations:
- This data is uploaded by a python script: https://github.com/marikaris/vkgl-consensus
The script uses the add all. And this code in row 324 in the RESTControler V2 causes the app to create way too many indexing jobs (Ik have >2000 PENDING): ```
entities.forEach(entity ->
			{
				restService.updateMappedByEntities(entity);

				String id = entity.getIdValue().toString();
				ids.add(id);
				responseBody.getResources()
							.add(new AutoValue_ResourcesResponseV2(
									Href.concatEntityHref(RestControllerV2.BASE_URI, entityTypeId, id)));
			});
```
- When searching and filtering at once, the number right below the table tells I have 26 results. My First page shows around 10 and my second 6. So the first page pagination doesn't go ok.
- When removing the search and just filtering I retrieve my 26 results after many refreshes. This is due to the indexing which takes forever.

**Comment by marikaris** [comment]
When killing tomcat, building again and then restarting, my tomcat won't come up again:
13:58:18.714 [RMI TCP Connection(2)-127.0.0.1] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.molgenis.data.MolgenisDataException: ; nested exception is org.springframework.dao.DataAccessResourceFailureException: PreparedStatementCallback; SQL [DELETE FROM "sys_job_IndexJobExecution#1d1bc397" WHERE "identifier" = ?]; ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.; nested exception is org.postgresql.util.PSQLException: ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:74)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:59)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:950)
	at org.molgenis.data.postgresql.PostgreSqlRepository.lambda$deleteAll$0(PostgreSqlRepository.java:224)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at org.molgenis.data.postgresql.PostgreSqlRepository.deleteAll(PostgreSqlRepository.java:213)
	at org.molgenis.data.postgresql.PostgreSqlRepository.delete(PostgreSqlRepository.java:201)
	at org.molgenis.data.postgresql.PostgreSqlRepository.delete(PostgreSqlRepository.java:195)
	at org.molgenis.data.AbstractRepositoryDecorator.delete(AbstractRepositoryDecorator.java:149)
	at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.delete(L1CacheRepositoryDecorator.java:148)
	at org.molgenis.data.AbstractRepositoryDecorator.delete(AbstractRepositoryDecorator.java:149)
	at org.molgenis.data.AbstractRepositoryDecorator.delete(AbstractRepositoryDecorator.java:149)
	at org.molgenis.data.index.IndexActionRepositoryDecorator.delete(IndexActionRepositoryDecorator.java:51)
	at org.molgenis.data.CascadeDeleteRepositoryDecorator.delete(CascadeDeleteRepositoryDecorator.java:35)
	at org.molgenis.data.AbstractRepositoryDecorator.delete(AbstractRepositoryDecorator.java:149)
	at org.molgenis.data.AbstractRepositoryDecorator.delete(AbstractRepositoryDecorator.java:149)
	at org.molgenis.data.AbstractRepositoryDecorator.delete(AbstractRepositoryDecorator.java:149)
	at org.molgenis.data.AbstractRepositoryDecorator.delete(AbstractRepositoryDecorator.java:149)
	at org.molgenis.data.RepositorySecurityDecorator.delete(RepositorySecurityDecorator.java:135)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$delete$13(TransactionalRepositoryDecorator.java:134)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.delete(TransactionalRepositoryDecorator.java:132)
	at org.molgenis.data.AbstractRepositoryDecorator.delete(AbstractRepositoryDecorator.java:149)
	at org.molgenis.data.support.DataServiceImpl.delete(DataServiceImpl.java:122)
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$4c05f283.delete(<generated>)
	at org.molgenis.data.index.bootstrap.IndexBootstrapper.registerNewIndexActionForDirtyJobs(IndexBootstrapper.java:73)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.molgenis.data.index.bootstrap.IndexBootstrapper.bootstrap(IndexBootstrapper.java:63)
	at org.molgenis.bootstrap.MolgenisBootstrapper.onApplicationEvent(MolgenisBootstrapper.java:98)
	at org.molgenis.bootstrap.MolgenisBootstrapper.onApplicationEvent(MolgenisBootstrapper.java:25)
	at org.molgenis.bootstrap.MolgenisBootstrapper$$FastClassBySpringCGLIB$$96732c53.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:44)
	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at org.molgenis.bootstrap.MolgenisBootstrapper$$EnhancerBySpringCGLIB$$3d3ee70d.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5116)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1863)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:618)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:565)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.DataAccessResourceFailureException: PreparedStatementCallback; SQL [DELETE FROM "sys_job_IndexJobExecution#1d1bc397" WHERE "identifier" = ?]; ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.; nested exception is org.postgresql.util.PSQLException: ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:251)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:54)
	... 117 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:463)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:794)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1662)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:966)
	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:950)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	... 115 common frames omitted
It's now been more than 3 hours since my script has finished.

**Comment by dennishendriksen** [comment]
Issue cause:
- Filtering consensus classification results in a 'SEARCH' query handled by Elasticsearch
- Elasticsearch index rebuilding is in progress due to
  - #5519 Poor indexing performance
  - Suboptimal indexing algorithm that performs too much work (@fdlk can you add a story link?)
  - Overeager indexing (e.g. ngram tokenization configuration), lack of control over what to index how
- Elasticsearch index rebuilding first deletes index and then builds a new index instead of building a new index and pointing the index alias to the new index before deleting the old index
- In our deployment setup
  - Elasticsearch is running with only one shard
  - Elasticsearch data is stored on the same disk as the PostgreSQL data
  - a VM is slower than a regular laptop

The issue can be circumvented by:
- Scheduling the VKGL data update at a user-inactive time
- Updating the VKGL data model such that filtering on the consensus classification attribute does not result in a search query (e.g. convert to enum data type)
- Perform the data update in a separate table and swap the data sets when done
