### ISSUE TITLE
Incomprehensible error message during import of entity with duplicateID.

### ISSUE THREAD

**Issue by Sipkovandam** [molgenis/molgenis#7099]
### How to Reproduce
Import attached file

### Expected behavior
Import succeeded

### Observed behavior
Import failed
Unknown attribute for column name ["PersonID"]

Catalina stacktrace:
```
14:22:21.859 [pool-4-thread-13] INFO  org.molgenis.data.importer.ImportJob - Import failed.
java.lang.RuntimeException: Unknown attribute for column name ["PersonID"]
        at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.getAttributeName(PostgreSqlExceptionTranslator.java:483)
        at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.translateUniqueKeyViolation(PostgreSqlExceptionTranslator.java:378)
        at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:112)
        at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:71)
        at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:59)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662)
        at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:950)
        at org.molgenis.data.postgresql.PostgreSqlRepository.lambda$addBatching$3(PostgreSqlRepository.java:445)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at org.molgenis.data.postgresql.PostgreSqlRepository.addBatching(PostgreSqlRepository.java:433)
        at org.molgenis.data.postgresql.PostgreSqlRepository.add(PostgreSqlRepository.java:256)
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
        at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.add(L1CacheRepositoryDecorator.java:53)
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
        at org.molgenis.data.index.IndexActionRepositoryDecorator.add(IndexActionRepositoryDecorator.java:83)
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
        at org.molgenis.data.validation.RepositoryValidationDecorator.add(RepositoryValidationDecorator.java:79)
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
        at org.molgenis.data.RepositorySecurityDecorator.add(RepositorySecurityDecorator.java:183)
        at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$add$19(TransactionalRepositoryDecorator.java:192)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at org.molgenis.data.transaction.TransactionalRepositoryDecorator.add(TransactionalRepositoryDecorator.java:192)
        at org.molgenis.data.AbstractRepositoryDecorator.add(AbstractRepositoryDecorator.java:173)
        at org.molgenis.data.importer.emx.ImportWriter.update(ImportWriter.java:476)
        at org.molgenis.data.importer.emx.ImportWriter.importData(ImportWriter.java:252)
        at org.molgenis.data.importer.emx.ImportWriter.doImport(ImportWriter.java:93)
        at org.molgenis.data.importer.emx.ImportWriter$$FastClassBySpringCGLIB$$df3d0c02.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at org.molgenis.data.importer.emx.ImportWriter$$EnhancerBySpringCGLIB$$918009a.doImport(<generated>)
        at org.molgenis.data.importer.emx.EmxImportService.doImport(EmxImportService.java:80)
        at org.molgenis.data.importer.emx.EmxImportService.doImport(EmxImportService.java:67)
        at org.molgenis.data.importer.ImportJob.run(ImportJob.java:50)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
[bug_emx.xlsx](https://github.com/molgenis/molgenis/files/1667868/bug_emx.xlsx)

**Comment by marikaris** [comment]
Why would you expect the import to be successful? You have duplicate ID's, they should be unique

**Comment by dennishendriksen** [comment]
@Sipkovandam Could you address @marikaris her questions?
