### ISSUE TITLE
Importing large files kills the tomcat on MOLGENIS servers

### ISSUE THREAD

**Issue by Mark-de-Haan** [molgenis/molgenis#7106]
### How to Reproduce
Import [this file](https://github.com/molgenis/molgenis/files/1673633/Chr6_vragen_emx_testimport_12_fix.xlsx) on molgenis01 / 09 / 62

### Expected behavior
I can go through the importer steps one by one

### Observed behavior
503 service temporarily unavailable

**Comment by ConnorStroomberg** [comment]
Not able to reproduce this issue locally

**Comment by ConnorStroomberg** [comment]
when trying to import the file on molgenis62 the server returns 503 (Server Temporarily Unavailible)

looking at 'catalina.2018-01-31.log' 

i see:


`
Jan 31, 2018 2:35:21 PM unknown unknown
SEVERE: Unexpected death of background thread ContainerBackgroundProcessor[StandardEngine[Catalina]]
java.lang.OutOfMemoryError: Java heap space
	at java.util.LinkedList.listIterator(LinkedList.java:868)
	at java.util.AbstractList.listIterator(AbstractList.java:299)
	at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:239)
	at org.apache.catalina.realm.CombinedRealm.backgroundProcess(CombinedRealm.java:289)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1356)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1542)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1520)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by ConnorStroomberg** [comment]
The molgenis manual suggests the following settings:
`CATALINA_OPTS="-Xmx2g`
The molgenis62 server however uses:
`CATALINA_OPTS="-Xmx1g`

**Comment by ConnorStroomberg** [comment]
When is increase the mem available to the tomcat process on molgenis62 from 1g to 2g i am able to successfully import the file. I suggest we increase the memory available to the tomcat process to at least 2g.

**Comment by Mark-de-Haan** [comment]
Updating to 2g memory marked as the fix (for now)
