### ISSUE TITLE
Python tests are failing

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7665]
### How to Reproduce
1. Add a new group 'it'
2. Import it_emx_datatypes
3. Copy the Python REST test from https://github.com/molgenis/molgenis/blob/7.0/molgenis-python/src/test/python/test-rest.py and run it

### Expected behavior
No test failures

### Observed behavior
```
======================================================================
ERROR: test_login_logout_and_get_MolgenisUser (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "rest-test.py", line 26, in test_login_logout_and_get_MolgenisUser
    response = s.get(self.user_entity)
  File "/Users/tommy/temp/molgenis.py", line 110, in get
    return response.json()["items"]
  File "/Library/Python/2.7/site-packages/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

======================================================================
FAIL: test_get_attribute_meta (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "rest-test.py", line 123, in test_get_attribute_meta
    meta)
AssertionError: {'labelAttribute': True, 'auto': False, 'visible': True, 'readOnly': False, 'hre [truncated]... != {u'labelAttribute': True, u'isAggregatable': False, u'name': u'username', u'auto [truncated]...
Diff is 926 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_no_login_and_get_MolgenisUser (__main__.TestStringMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "rest-test.py", line 37, in test_no_login_and_get_MolgenisUser
    self.assertEqual(e.response.json()['errors'][0]['message'], self.no_count_permission_user_msg)
AssertionError: u"No 'Read metadata' permission on entity type 'User' with id 'sys_sec_User'." != 'No [COUNT] permission on entity type [User] with id [sys_sec_User]'

----------------------------------------------------------------------
Ran 10 tests in 9.358s

FAILED (failures=2, errors=1)
```

**Comment by LuukDijkhuis** [comment]
done
