### ISSUE TITLE
Import fails on EMX update with one-to-many attributes

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#7739]
### How to Reproduce
Upload: 
[eric_data_quality.xlsx](https://github.com/molgenis/molgenis/files/2318147/eric_data_quality.xlsx)
With data + metadata (edit @dennishendriksen smaller input file: [it_emx_onetomany.xlsx](https://github.com/molgenis/molgenis/files/2360198/it_emx_onetomany.xlsx))
Go to metadata manager (edit @dennishendriksen step is not required)
Select collections (edit @dennishendriksen step is not required)
Delete standards attribute (edit @dennishendriksen step is not required)
Go to importer
Import same dataset with only data (update mode)

### Expected behavior
A yellow attribute, I get data but I will not import it blablabla, but I am nice and will import the rest

### Observed behavior
I get the message but when the importer succeeds I get an infinite spinner (what's new?) and a nullpointer in my log #saddatamanager:
<img width="975" alt="screen shot 2018-08-24 at 13 29 59" src="https://user-images.githubusercontent.com/10075439/44582653-961fb100-a7a2-11e8-9460-0d18ef0e7d40.png">
```
java.lang.NullPointerException: null
	at org.molgenis.data.validation.meta.AttributeValidator.validateUpdate(AttributeValidator.java:116)
	at org.molgenis.data.validation.meta.AttributeValidator.validate(AttributeValidator.java:72)
	at org.molgenis.data.validation.meta.AttributeRepositoryValidationDecorator.lambda$update$0(AttributeRepositoryValidationDecorator.java:35)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.google.common.collect.Iterators$4.hasNext(Iterators.java:602)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at org.molgenis.data.postgresql.PostgreSqlRepository.updateBatching(PostgreSqlRepository.java:523)
	at org.molgenis.data.postgresql.PostgreSqlRepository.update(PostgreSqlRepository.java:183)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.update(L1CacheRepositoryDecorator.java:140)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.index.IndexActionRepositoryDecorator.update(IndexActionRepositoryDecorator.java:91)
	at org.molgenis.data.meta.AttributeRepositoryDecorator.update(AttributeRepositoryDecorator.java:41)
	at org.molgenis.data.validation.meta.AttributeRepositoryValidationDecorator.update(AttributeRepositoryValidationDecorator.java:33)
	at org.molgenis.data.security.meta.AttributeRepositorySecurityDecorator.update(AttributeRepositorySecurityDecorator.java:219)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.listeners.EntityListenerRepositoryDecorator.update(EntityListenerRepositoryDecorator.java:34)
	at org.molgenis.data.validation.RepositoryValidationDecorator.update(RepositoryValidationDecorator.java:60)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.security.RepositorySecurityDecorator.update(RepositorySecurityDecorator.java:131)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$update$12(TransactionalRepositoryDecorator.java:124)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.update(TransactionalRepositoryDecorator.java:122)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.support.DataServiceImpl.update(DataServiceImpl.java:111)
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$b7cf39f0.update(<generated>)
	at org.molgenis.data.meta.MetaDataServiceImpl.upsertAttributes(MetaDataServiceImpl.java:513)
	at org.molgenis.data.meta.MetaDataServiceImpl.updateEntityType(MetaDataServiceImpl.java:360)
	at org.molgenis.data.meta.MetaDataServiceImpl.updateEntityType(MetaDataServiceImpl.java:243)
	at org.molgenis.data.meta.MetaDataServiceImpl$$FastClassBySpringCGLIB$$7c65c46d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.data.meta.MetaDataServiceImpl$$EnhancerBySpringCGLIB$$dd4a0243.updateEntityType(<generated>)
	at org.molgenis.data.importer.DataPersisterImpl.persistEntityTypeSecondPass(DataPersisterImpl.java:279)
	at org.molgenis.data.importer.DataPersisterImpl.lambda$persistSecondPass$1(DataPersisterImpl.java:101)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.molgenis.data.importer.DataPersisterImpl.persistSecondPass(DataPersisterImpl.java:99)
	at org.molgenis.data.importer.DataPersisterImpl.persist(DataPersisterImpl.java:52)
	at org.molgenis.data.importer.DataPersisterImpl$$FastClassBySpringCGLIB$$3469260b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.data.importer.DataPersisterImpl$$EnhancerBySpringCGLIB$$a7f719dd.persist(<generated>)
	at org.molgenis.data.importer.emx.ImportWriter.doImport(ImportWriter.java:68)
	at org.molgenis.data.importer.emx.ImportWriter$$FastClassBySpringCGLIB$$df3d0c02.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.data.importer.emx.ImportWriter$$EnhancerBySpringCGLIB$$909abe22.doImport(<generated>)
	at org.molgenis.data.importer.emx.EmxImportService.doImport(EmxImportService.java:83)
	at org.molgenis.data.importer.emx.EmxImportService.doImport(EmxImportService.java:70)
	at org.molgenis.data.importer.ImportJob.run(ImportJob.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-08-24_13:27:55.161 [pool-4-thread-8] INFO  org.molgenis.data.importer.ImportJob - Import failed.
java.lang.NullPointerException: null
	at org.molgenis.data.validation.meta.AttributeValidator.validateUpdate(AttributeValidator.java:116)
	at org.molgenis.data.validation.meta.AttributeValidator.validate(AttributeValidator.java:72)
	at org.molgenis.data.validation.meta.AttributeRepositoryValidationDecorator.lambda$update$0(AttributeRepositoryValidationDecorator.java:35)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.google.common.collect.Iterators$4.hasNext(Iterators.java:602)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at org.molgenis.data.postgresql.PostgreSqlRepository.updateBatching(PostgreSqlRepository.java:523)
	at org.molgenis.data.postgresql.PostgreSqlRepository.update(PostgreSqlRepository.java:183)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.cache.l1.L1CacheRepositoryDecorator.update(L1CacheRepositoryDecorator.java:140)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.index.IndexActionRepositoryDecorator.update(IndexActionRepositoryDecorator.java:91)
	at org.molgenis.data.meta.AttributeRepositoryDecorator.update(AttributeRepositoryDecorator.java:41)
	at org.molgenis.data.validation.meta.AttributeRepositoryValidationDecorator.update(AttributeRepositoryValidationDecorator.java:33)
	at org.molgenis.data.security.meta.AttributeRepositorySecurityDecorator.update(AttributeRepositorySecurityDecorator.java:219)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.listeners.EntityListenerRepositoryDecorator.update(EntityListenerRepositoryDecorator.java:34)
	at org.molgenis.data.validation.RepositoryValidationDecorator.update(RepositoryValidationDecorator.java:60)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.security.RepositorySecurityDecorator.update(RepositorySecurityDecorator.java:131)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$update$12(TransactionalRepositoryDecorator.java:124)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.update(TransactionalRepositoryDecorator.java:122)
	at org.molgenis.data.AbstractRepositoryDecorator.update(AbstractRepositoryDecorator.java:179)
	at org.molgenis.data.support.DataServiceImpl.update(DataServiceImpl.java:111)
	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$b7cf39f0.update(<generated>)
	at org.molgenis.data.meta.MetaDataServiceImpl.upsertAttributes(MetaDataServiceImpl.java:513)
	at org.molgenis.data.meta.MetaDataServiceImpl.updateEntityType(MetaDataServiceImpl.java:360)
	at org.molgenis.data.meta.MetaDataServiceImpl.updateEntityType(MetaDataServiceImpl.java:243)
	at org.molgenis.data.meta.MetaDataServiceImpl$$FastClassBySpringCGLIB$$7c65c46d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.data.meta.MetaDataServiceImpl$$EnhancerBySpringCGLIB$$dd4a0243.updateEntityType(<generated>)
	at org.molgenis.data.importer.DataPersisterImpl.persistEntityTypeSecondPass(DataPersisterImpl.java:279)
	at org.molgenis.data.importer.DataPersisterImpl.lambda$persistSecondPass$1(DataPersisterImpl.java:101)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.molgenis.data.importer.DataPersisterImpl.persistSecondPass(DataPersisterImpl.java:99)
	at org.molgenis.data.importer.DataPersisterImpl.persist(DataPersisterImpl.java:52)
	at org.molgenis.data.importer.DataPersisterImpl$$FastClassBySpringCGLIB$$3469260b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.data.importer.DataPersisterImpl$$EnhancerBySpringCGLIB$$a7f719dd.persist(<generated>)
	at org.molgenis.data.importer.emx.ImportWriter.doImport(ImportWriter.java:68)
	at org.molgenis.data.importer.emx.ImportWriter$$FastClassBySpringCGLIB$$df3d0c02.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.data.importer.emx.ImportWriter$$EnhancerBySpringCGLIB$$909abe22.doImport(<generated>)
	at org.molgenis.data.importer.emx.EmxImportService.doImport(EmxImportService.java:83)
	at org.molgenis.data.importer.emx.EmxImportService.doImport(EmxImportService.java:70)
	at org.molgenis.data.importer.ImportJob.run(ImportJob.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dennishendriksen** [comment]
The infinite spinner is caused by https://github.com/molgenis/molgenis/issues/3172

**Comment by dennishendriksen** [comment]
I can reproduce the issue. With a simple dataset however I cannot: [it_emx_idlabel.xlsx](https://github.com/molgenis/molgenis/files/2360098/it_emx_idlabel.xlsx)
