### ISSUE TITLE
500 Error adding source to mapping project

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7902]
### How to Reproduce
Import bbmri-eu metadata
Create mapping project with target `eu_bbmri_eric_collections`
Add source `eu_bbmri_eric_collections`

### Expected behavior
Source gets added

### Observed behavior
Source gets added but exception is displayed:
> 500
matchedQueryRule.entrySet() shouldn't return an empty Set 

Stacktrace says
```
molgenis_1       | 2018-10-17_09:19:37.304 [http-nio-8080-exec-1] ERROR o.m.w.e.FallbackExceptionHandler - 
molgenis_1       | java.lang.IllegalStateException: matchedQueryRule.entrySet() shouldn't return an empty Set
molgenis_1       |      at org.molgenis.semanticsearch.explain.service.ElasticSearchExplainServiceImpl.lambda$findQueriesFromExplanation$0(ElasticSearchExplainServiceImpl.java:58)
molgenis_1       |      at java.util.Optional.orElseThrow(Optional.java:290)
molgenis_1       |      at org.molgenis.semanticsearch.explain.service.ElasticSearchExplainServiceImpl.findQueriesFromExplanation(ElasticSearchExplainServiceImpl.java:56)
molgenis_1       |      at org.molgenis.semanticsearch.service.impl.SemanticSearchServiceImpl.convertAttributeToExplainedAttribute(SemanticSearchServiceImpl.java:278)
molgenis_1       |      at org.molgenis.semanticsearch.service.impl.SemanticSearchServiceImpl.lambda$findAttributes$0(SemanticSearchServiceImpl.java:127)
molgenis_1       |      at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
molgenis_1       |      at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
molgenis_1       |      at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
molgenis_1       |      at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
molgenis_1       |      at java.util.Iterator.forEachRemaining(Iterator.java:116)
molgenis_1       |      at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
molgenis_1       |      at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
molgenis_1       |      at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
molgenis_1       |      at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
molgenis_1       |      at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
molgenis_1       |      at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
molgenis_1       |      at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
molgenis_1       |      at org.molgenis.semanticsearch.service.impl.SemanticSearchServiceImpl.findAttributes(SemanticSearchServiceImpl.java:119)
molgenis_1       |      at org.molgenis.semanticsearch.service.impl.SemanticSearchServiceImpl.findAttributes(SemanticSearchServiceImpl.java:232)
molgenis_1       |      at org.molgenis.semanticsearch.service.impl.SemanticSearchServiceImpl.lambda$findAttributes$6(SemanticSearchServiceImpl.java:187)
molgenis_1       |      at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
molgenis_1       |      at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
molgenis_1       |      at java.util.Iterator.forEachRemaining(Iterator.java:116)
molgenis_1       |      at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
molgenis_1       |      at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
molgenis_1       |      at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
molgenis_1       |      at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
molgenis_1       |      at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
molgenis_1       |      at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
molgenis_1       |      at org.molgenis.semanticsearch.service.impl.SemanticSearchServiceImpl.findAttributes(SemanticSearchServiceImpl.java:190)
molgenis_1       |      at org.molgenis.semanticsearch.service.SemanticSearchService.findAttributes(SemanticSearchService.java:31)
molgenis_1       |      at org.molgenis.semanticmapper.service.impl.AlgorithmServiceImpl.autoGenerateAlgorithm(AlgorithmServiceImpl.java:87)
molgenis_1       |      at org.molgenis.semanticmapper.service.impl.AlgorithmServiceImpl$$FastClassBySpringCGLIB$$ee750b08.invoke(<generated>)
molgenis_1       |      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
molgenis_1       |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
molgenis_1       |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
molgenis_1       |      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
molgenis_1       |      at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:37)
molgenis_1       |      at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:19)
molgenis_1       |      at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
molgenis_1       |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
molgenis_1       |      at java.lang.reflect.Method.invoke(Method.java:498)
molgenis_1       |      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
molgenis_1       |      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
molgenis_1       |      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
molgenis_1       |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
molgenis_1       |      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
molgenis_1       |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
molgenis_1       |      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
molgenis_1       |      at org.molgenis.semanticmapper.service.impl.AlgorithmServiceImpl$$EnhancerBySpringCGLIB$$59865d97.autoGenerateAlgorithm(<generated>)
molgenis_1       |      at org.molgenis.semanticmapper.controller.MappingServiceController.autoGenerateAlgorithms(MappingServiceController.java:997)
molgenis_1       |      at org.molgenis.semanticmapper.controller.MappingServiceController.addEntityMapping(MappingServiceController.java:233)
molgenis_1       |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
molgenis_1       |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
molgenis_1       |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
molgenis_1       |      at java.lang.reflect.Method.invoke(Method.java:498)
molgenis_1       |      at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
molgenis_1       |      at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
molgenis_1       |      at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
molgenis_1       |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
molgenis_1       |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
molgenis_1       |      at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
molgenis_1       |      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
molgenis_1       |      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
molgenis_1       |      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
molgenis_1       |      at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
molgenis_1       |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
molgenis_1       |      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
molgenis_1       |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       |      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       |      at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
molgenis_1       |      at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
molgenis_1       |      at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
molgenis_1       |      at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
molgenis_1       |      at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:170)
molgenis_1       |      at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:315)
molgenis_1       |      at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1325)
molgenis_1       |      at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1069)
molgenis_1       |      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1008)
molgenis_1       |      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
molgenis_1       |      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
molgenis_1       |      at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
molgenis_1       |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
molgenis_1       |      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
molgenis_1       |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       |      at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:108)
molgenis_1       |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       |      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
molgenis_1       |      at org.molgenis.security.twofactor.auth.TwoFactorAuthenticationFilter.doFilterInternal(TwoFactorAuthenticationFilter.java:54)
molgenis_1       |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.molgenis.security.MolgenisChangePasswordFilter.doFilter(MolgenisChangePasswordFilter.java:52)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
molgenis_1       |      at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.molgenis.security.token.TokenAuthenticationFilter.doFilter(TokenAuthenticationFilter.java:52)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
molgenis_1       |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:128)
molgenis_1       |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
molgenis_1       |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
molgenis_1       |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
molgenis_1       |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
molgenis_1       |      at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
molgenis_1       |      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
molgenis_1       |      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       |      at org.molgenis.core.ui.browserdetection.BrowserDetectionFilter.doFilter(BrowserDetectionFilter.java:52)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       |      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
molgenis_1       |      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
molgenis_1       |      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
molgenis_1       |      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
molgenis_1       |      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
molgenis_1       |      at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
molgenis_1       |      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
molgenis_1       |      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
molgenis_1       |      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
molgenis_1       |      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
molgenis_1       |      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
molgenis_1       |      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
molgenis_1       |      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
molgenis_1       |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
molgenis_1       |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
molgenis_1       |      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
molgenis_1       |      at java.lang.Thread.run(Thread.java:748)

```

**Comment by fdlk** [comment]
Checked in 7.2 and there the source gets added normally.

**Comment by sidohaakma** [comment]
Created by #7884
