### ISSUE TITLE
Style files end up missing

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#7925]
### How to Reproduce
Unsure how to reproduce. Best guess would be:
Bootstrap and kill molgenis after the styles are downloaded but before the transaction commits.
Then start molgenis again

### Expected behavior
It works

### Observed behavior
Stack traces in the log:
```
2018-11-01_12:23:59.981 [http-nio-8080-exec-1] ERROR freemarker.runtime - Error executing FreeMarker template part in the #attempt block
molgenis_1       | freemarker.core._TemplateModelException: Java method "org.molgenis.core.ui.style.ThemeFingerprintRegistry.getFingerprint(String)" threw an exception when invoked on org.molgenis.core.ui.style.ThemeFingerprintRegistry object "org.molgenis.core.ui.style.ThemeFingerprintRegistry@6ca942b7"; see cause exception in the Java stack trace.
molgenis_1       |
molgenis_1       | ----
molgenis_1       | FTL stack trace ("~" means nesting-related):
molgenis_1       | 	- Failed at: ${theme_fingerprint_registry.getFinge...  [in template "theme-macros.ftl" in macro "theme_href" at line 3, column 160]
molgenis_1       | 	- Reached through: @theme_href "/css/bootstrap-3/${app_s...  [in template "molgenis-header.ftl" in macro "header" at line 21, column 38]
molgenis_1       | 	- Reached through: @header css, js  [in template "view-wizard.ftl" at line 7, column 1]
molgenis_1       | ----
molgenis_1       | 	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289)
molgenis_1       | 	at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:252)
molgenis_1       | 	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:77)
molgenis_1       | 	at freemarker.core.MethodCall._eval(MethodCall.java:65)
molgenis_1       | 	at freemarker.core.Expression.eval(Expression.java:83)
molgenis_1       | 	at freemarker.core.BuiltInForLegacyEscaping._eval(BuiltInForLegacyEscaping.java:33)
molgenis_1       | 	at freemarker.core.Expression.eval(Expression.java:83)
molgenis_1       | 	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
molgenis_1       | 	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:330)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:336)
molgenis_1       | 	at freemarker.core.Environment.visitAttemptRecover(Environment.java:549)
molgenis_1       | 	at freemarker.core.AttemptBlock.accept(AttemptBlock.java:45)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:330)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:372)
molgenis_1       | 	at freemarker.core.Environment.invoke(Environment.java:775)
molgenis_1       | 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:330)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:372)
molgenis_1       | 	at freemarker.core.Environment.invoke(Environment.java:775)
molgenis_1       | 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:330)
molgenis_1       | 	at freemarker.core.Environment.visit(Environment.java:336)
molgenis_1       | 	at freemarker.core.Environment.process(Environment.java:309)
molgenis_1       | 	at freemarker.template.Template.process(Template.java:384)
molgenis_1       | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:396)
molgenis_1       | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:309)
molgenis_1       | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:257)
molgenis_1       | 	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:165)
molgenis_1       | 	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:315)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1325)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1069)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1008)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
molgenis_1       | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
molgenis_1       | 	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:170)
molgenis_1       | 	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:315)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1325)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1069)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1008)
molgenis_1       | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
molgenis_1       | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
molgenis_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:108)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.molgenis.core.ui.browserdetection.BrowserDetectionFilter.doFilter(BrowserDetectionFilter.java:52)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
molgenis_1       | 	at org.molgenis.security.twofactor.auth.TwoFactorAuthenticationFilter.doFilterInternal(TwoFactorAuthenticationFilter.java:54)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.molgenis.security.MolgenisChangePasswordFilter.doFilter(MolgenisChangePasswordFilter.java:52)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
molgenis_1       | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.molgenis.security.token.TokenAuthenticationFilter.doFilter(TokenAuthenticationFilter.java:52)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:128)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
molgenis_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
molgenis_1       | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
molgenis_1       | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
molgenis_1       | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
molgenis_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
molgenis_1       | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
molgenis_1       | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
molgenis_1       | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
molgenis_1       | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
molgenis_1       | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
molgenis_1       | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
molgenis_1       | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
molgenis_1       | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
molgenis_1       | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
molgenis_1       | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
molgenis_1       | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
molgenis_1       | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
molgenis_1       | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
molgenis_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
molgenis_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
molgenis_1       | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
molgenis_1       | 	at java.lang.Thread.run(Thread.java:748)
molgenis_1       | Caused by: java.io.FileNotFoundException: /home/molgenis/data/filestore/aaaaczubp2hmiascvqlqaaqaae
molgenis_1       | 	at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:129)
molgenis_1       | 	at org.molgenis.core.ui.style.ThemeFingerprintRegistry.createFingerprint(ThemeFingerprintRegistry.java:41)
molgenis_1       | 	at org.molgenis.core.ui.style.ThemeFingerprintRegistry.getFingerprint(ThemeFingerprintRegistry.java:31)
molgenis_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
molgenis_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
molgenis_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
molgenis_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
molgenis_1       | 	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
molgenis_1       | 	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:72)
molgenis_1       | 	... 137 common frames omitted
```

**Comment by dennishendriksen** [comment]
> @molgenis/data-management do you have any information that could help pinpoint the cause of this issue?

do you have any info?
