### ISSUE TITLE
Default value reference entity type incorrect: improved message

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#7935]
### How to Reproduce
1. Import [it_emx_onetomany.xlsx](https://github.com/molgenis/molgenis/files/2553194/it_emx_onetomany.xlsx) which has an xref _coauthor_ with 'orwell' as default value.

### Expected behavior
Import succeeds.

### Observed behavior
```
org.molgenis.data.validation.MolgenisValidationException: Unknown attribute 'bookId' of entity type 'Test: Book'.
	at org.molgenis.data.validation.QueryValidator.getQueryRuleAttribute(QueryValidator.java:129)
	at org.molgenis.data.validation.QueryValidator.validateQueryRule(QueryValidator.java:75)
	at org.molgenis.data.validation.QueryValidator.lambda$validate$0(QueryValidator.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at org.molgenis.data.validation.QueryValidator.validate(QueryValidator.java:56)
	at org.molgenis.data.validation.QueryValidationRepositoryDecorator.count(QueryValidationRepositoryDecorator.java:31)
	at org.molgenis.data.support.QueryImpl.count(QueryImpl.java:88)
	at org.molgenis.data.validation.meta.AttributeValidator.validateDefaultValue(AttributeValidator.java:211)
	at org.molgenis.data.validation.meta.AttributeValidator.validate(AttributeValidator.java:81)
	at org.molgenis.data.validation.meta.AttributeRepositoryValidationDecorator.lambda$add$1(AttributeRepositoryValidationDecorator.java:49)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
        ...
```

**Comment by tommydeboer** [comment]
I kinda ran in to issue while writing the copy functionality:

OneToManys require that the metadata is added first, but references with default values require that the data is present first.

**Comment by mswertz** [comment]
I suppose the metadata should be added first, and then during insertion the default value should be resolved?

**Comment by dennishendriksen** [comment]
The import fails due to an error in the data:
![image](https://user-images.githubusercontent.com/2477186/51617560-c5427600-1f2c-11e9-85b9-345b05e413f9.png)
The refEntity should be ```it_emx_onetomany_author``` instead of ```it_emx_onetomany_author```.

The error message is very confusing and should say: ```Default value [orwell] refers to an unknown entity```.
