### ISSUE TITLE
Error message viewing SORTA results

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis#8039]
### How to Reproduce
Execute the SORTA test plan, view the result on line 19

### Expected behavior
No error message

### Observed behavior
Stackoverflow
In the server log I see repeated incantations of

```
at org.molgenis.ontology.utils.SortaServiceUtil.getEntityAsMap(SortaServiceUtil.java:30)
at org.molgenis.ontology.utils.SortaServiceUtil.getEntityAsMap(SortaServiceUtil.java:35)
```

**Comment by fdlk** [comment]
f8737c1bd814c0476b17c5e110c4a353920e412b is the first bad commit
commit f8737c1bd814c0476b17c5e110c4a353920e412b
Author: Dennis Hendriksen <d.hendriksen@umcg.nl>
Date:   Wed Oct 3 11:11:58 2018 +0200

    Fix #7862 Ontology-deletion non-practical (#7863)
