### ISSUE TITLE
Molgenis fails to start with NoSuchFileException (molgenis-security-8.0.0-SNAPSHOT.jar)r

### ISSUE THREAD

**Issue by ConnorStroomberg** [molgenis/molgenis#8203]
### How to Reproduce
As developer build using 'mvn clean install -DskipTests'.
Then run with settings as described in molgenis [manual](https://molgenis.gitbooks.io/molgenis/content/quickstart/guide-tomcat.html) 

context:
````
30-Jan-2019 14:03:46.957 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.14
30-Jan-2019 14:03:46.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 6 2018 21:13:53 UTC
30-Jan-2019 14:03:46.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.14.0
30-Jan-2019 14:03:46.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Mac OS X
30-Jan-2019 14:03:46.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.14.2
30-Jan-2019 14:03:46.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          x86_64
30-Jan-2019 14:03:46.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home
30-Jan-2019 14:03:46.961 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.2+9-LTS
30-Jan-2019 14:03:46.961 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
````
### Expected behavior
Webapp starts 

### Observed behavior
Webapp fails to start and logs exception
````
ERROR o.s.web.context.ContextLoader - Context initialization failed
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /Users/user/Code/molgenis/molgenis-app/target/molgenis-app-8.0.0-SNAPSHOT/WEB-INF/lib/molgenis-security-8.0.0-SNAPSHOT.jar
	at org.molgenis.security.acl.DataSourceAclTablesPopulator.createTable(DataSourceAclTablesPopulator.java:50)
	at org.molgenis.security.acl.DataSourceAclTablesPopulator.lambda$populate$0(DataSourceAclTablesPopulator.java:37)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.molgenis.security.acl.DataSourceAclTablesPopulator.populate(DataSourceAclTablesPopulator.java:37)
	at org.molgenis.bootstrap.MolgenisBootstrapper.onApplicationEvent(MolgenisBootstrapper.java:89)
	at org.molgenis.bootstrap.MolgenisBootstrapper.onApplicationEvent(MolgenisBootstrapper.java:31)
	at org.molgenis.bootstrap.MolgenisBootstrapper$$FastClassBySpringCGLIB$$96732c53.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.molgenis.metrics.MolgenisTimedAspect.timedProceed(MolgenisTimedAspect.java:80)
	at org.molgenis.metrics.MolgenisTimedAspect.timedMethod(MolgenisTimedAspect.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:38)
	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.bootstrap.MolgenisBootstrapper$$EnhancerBySpringCGLIB$$e4dbb211.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4661)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5131)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:713)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1729)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:457)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:406)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: /Users/user/Code/molgenis/molgenis-app/target/molgenis-app-8.0.0-SNAPSHOT/WEB-INF/lib/molgenis-security-8.0.0-SNAPSHOT.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1222)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:824)
	at java.base/java.util.zip.ZipFile$CleanableResource$FinalizableResource.<init>(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:839)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
	at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
	at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
	at java.base/java.net.URL.openStream(URL.java:1117)
	at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:70)
	at com.google.common.io.ByteSource.read(ByteSource.java:285)
	at com.google.common.io.ByteSource$AsCharSource.read(ByteSource.java:470)
	at com.google.common.io.Resources.toString(Resources.java:109)
	at org.molgenis.util.ResourceUtils.getString(ResourceUtils.java:74)
	at org.molgenis.util.ResourceUtils.getString(ResourceUtils.java:43)
	at org.molgenis.security.acl.DataSourceAclTablesPopulator.createTable(DataSourceAclTablesPopulator.java:45)
	... 92 common frames omitted
````

**Comment by ConnorStroomberg** [comment]
@dennishendriksen do you suggest closing the issue and making 'click the synchronize button in intelij' part of the 'how to run molgenis in tomcat via intelij' steps ?

**Comment by dennishendriksen** [comment]
After our chat this morning it is clear to me that my findings are due to a functional misunderstanding:
- A clean install of 8.0 results in a new logo and other menu colors
- A clean install of 7.4 and upgrading to 8.0 does not result in a new logo and other menu colors
- After upgrading the size of the old logo increases, I consider this a bug (@mswertz?)

@ConnorStroomberg since my issue turns out not to be related to the issue reported by @marikaris it depends on whether @marikaris can reproduce the issue.

**Comment by mswertz** [comment]
has this been verified?

**Comment by fdlk** [comment]
If this only happened when skipping js compilation, it should now be fixed.

**Comment by dennishendriksen** [comment]
@ConnorStroomberg ?

**Comment by connoratrug** [comment]
@fdlk @mswertz no i do not think it is related to skip js, is seems to be more of a intelij / filesystem syn issue, i get this a lot when rebuilding and switching branches. But if i am the only one experiencing  this issue we can close it.

**Comment by marikaris** [comment]
Documentation updated in #8310.

**Comment by tommydeboer** [comment]
I have this problem too sometimes and indeed synchronizing my files solves the problem. Still a bit annoying though :)

**Comment by dennishendriksen** [comment]
@connoratrug can you close if you are happy with the documentation provided by @marikaris ?

**Comment by connoratrug** [comment]
@dennishendriksen no, as discussed with the PO we leave it open as it is still an issue even if the work-around is documented.
