### ISSUE TITLE
IndexActions all end up PENDING when ... 

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis#8287]
### How to Reproduce
```
2019-02-16_12:00:00.133 [schedulerFactoryBean_Worker-4] ERROR org.molgenis.jobs.JobExecutor - Error creating job for JobExecution.
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Unexpected exception class [SQLException]
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.getUnchecked(CaffeinatedGuavaLoadingCache.java:81)
	at org.molgenis.data.cache.l3.L3Cache.get(L3Cache.java:63)
	at org.molgenis.data.cache.l3.L3CacheRepositoryDecorator.findOne(L3CacheRepositoryDecorator.java:85)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.EntityReferenceResolverDecorator.findOne(EntityReferenceResolverDecorator.java:35)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.security.RepositorySecurityDecorator.findOne(RepositorySecurityDecorator.java:75)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$findOne$5(TransactionalRepositoryDecorator.java:76)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.findOne(TransactionalRepositoryDecorator.java:76)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.validation.QueryValidationRepositoryDecorator.findOne(QueryValidationRepositoryDecorator.java:47)
	at org.molgenis.data.support.QueryImpl.findOne(QueryImpl.java:108)
	at org.molgenis.security.user.UserDetailsService.loadUserByUsername(UserDetailsService.java:41)
	at org.molgenis.security.user.UserDetailsService$$FastClassBySpringCGLIB$$1483fd27.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:44)
	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:23)
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.security.user.UserDetailsService$$EnhancerBySpringCGLIB$$283ae4b2.loadUserByUsername(<generated>)
	at org.molgenis.jobs.JobExecutorTokenServiceImpl.createAuthorization(JobExecutorTokenServiceImpl.java:35)
	at org.molgenis.jobs.JobExecutorTokenServiceImpl.createToken(JobExecutorTokenServiceImpl.java:30)
	at org.molgenis.jobs.JobExecutor.runJob(JobExecutor.java:145)
	at org.molgenis.jobs.JobExecutor.executeScheduledJob(JobExecutor.java:77)
	at org.molgenis.jobs.JobExecutor$$FastClassBySpringCGLIB$$bc2e61ec.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:44)
	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:23)
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.jobs.JobExecutor$$EnhancerBySpringCGLIB$$1188b621.executeScheduledJob(<generated>)
	at org.molgenis.jobs.schedule.MolgenisQuartzJob.execute(MolgenisQuartzJob.java:33)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: Unexpected exception class [SQLException]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:92)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:61)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:620)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:657)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:688)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:751)
	at org.molgenis.data.postgresql.PostgreSqlRepository$1.getBatch(PostgreSqlRepository.java:416)
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:36)
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:14)
	at org.molgenis.data.util.BatchingIterable$1.nextBatch(BatchingIterable.java:138)
	at org.molgenis.data.util.BatchingIterable$1.hasNext(BatchingIterable.java:58)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.molgenis.data.cache.l3.L3Cache$1.load(L3Cache.java:107)
	at org.molgenis.data.cache.l3.L3Cache$1.load(L3Cache.java:95)
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache$SingleLoader.load(CaffeinatedGuavaLoadingCache.java:136)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3366)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:143)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2064)
	at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.getUnchecked(CaffeinatedGuavaLoadingCache.java:75)
	... 60 common frames omitted
2019-02-16_12:00:00.171 [schedulerFactoryBean_Worker-4] ERROR org.quartz.core.JobRunShell - Job DEFAULT.aaaacz3ds7txyaawhyjtokqaai threw an unhandled Exception: 
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Unexpected exception class [SQLException]
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.getUnchecked(CaffeinatedGuavaLoadingCache.java:81)
	at org.molgenis.data.cache.l3.L3Cache.get(L3Cache.java:63)
	at org.molgenis.data.cache.l3.L3CacheRepositoryDecorator.findOne(L3CacheRepositoryDecorator.java:85)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.EntityReferenceResolverDecorator.findOne(EntityReferenceResolverDecorator.java:35)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.security.RepositorySecurityDecorator.findOne(RepositorySecurityDecorator.java:75)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$findOne$5(TransactionalRepositoryDecorator.java:76)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.findOne(TransactionalRepositoryDecorator.java:76)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.validation.QueryValidationRepositoryDecorator.findOne(QueryValidationRepositoryDecorator.java:47)
	at org.molgenis.data.support.QueryImpl.findOne(QueryImpl.java:108)
	at org.molgenis.security.user.UserDetailsService.loadUserByUsername(UserDetailsService.java:41)
	at org.molgenis.security.user.UserDetailsService$$FastClassBySpringCGLIB$$1483fd27.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:44)
	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:23)
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.security.user.UserDetailsService$$EnhancerBySpringCGLIB$$283ae4b2.loadUserByUsername(<generated>)
	at org.molgenis.jobs.JobExecutorTokenServiceImpl.createAuthorization(JobExecutorTokenServiceImpl.java:35)
	at org.molgenis.jobs.JobExecutorTokenServiceImpl.createToken(JobExecutorTokenServiceImpl.java:30)
	at org.molgenis.jobs.JobExecutor.runJob(JobExecutor.java:145)
	at org.molgenis.jobs.JobExecutor.executeScheduledJob(JobExecutor.java:77)
	at org.molgenis.jobs.JobExecutor$$FastClassBySpringCGLIB$$bc2e61ec.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:44)
	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:23)
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.jobs.JobExecutor$$EnhancerBySpringCGLIB$$1188b621.executeScheduledJob(<generated>)
	at org.molgenis.jobs.schedule.MolgenisQuartzJob.execute(MolgenisQuartzJob.java:33)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: Unexpected exception class [SQLException]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:92)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:61)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:620)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:657)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:688)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:751)
	at org.molgenis.data.postgresql.PostgreSqlRepository$1.getBatch(PostgreSqlRepository.java:416)
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:36)
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:14)
	at org.molgenis.data.util.BatchingIterable$1.nextBatch(BatchingIterable.java:138)
	at org.molgenis.data.util.BatchingIterable$1.hasNext(BatchingIterable.java:58)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.molgenis.data.cache.l3.L3Cache$1.load(L3Cache.java:107)
	at org.molgenis.data.cache.l3.L3Cache$1.load(L3Cache.java:95)
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache$SingleLoader.load(CaffeinatedGuavaLoadingCache.java:136)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3366)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:143)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2064)
	at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.getUnchecked(CaffeinatedGuavaLoadingCache.java:75)
	... 60 common frames omitted
2019-02-16_12:00:00.173 [schedulerFactoryBean_Worker-4] ERROR org.quartz.core.ErrorLogger - Job (DEFAULT.aaaacz3ds7txyaawhyjtokqaai threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Unexpected exception class [SQLException]
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.getUnchecked(CaffeinatedGuavaLoadingCache.java:81)
	at org.molgenis.data.cache.l3.L3Cache.get(L3Cache.java:63)
	at org.molgenis.data.cache.l3.L3CacheRepositoryDecorator.findOne(L3CacheRepositoryDecorator.java:85)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.EntityReferenceResolverDecorator.findOne(EntityReferenceResolverDecorator.java:35)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.security.RepositorySecurityDecorator.findOne(RepositorySecurityDecorator.java:75)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.lambda$findOne$5(TransactionalRepositoryDecorator.java:76)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.findOne(TransactionalRepositoryDecorator.java:76)
	at org.molgenis.data.AbstractRepositoryDecorator.findOne(AbstractRepositoryDecorator.java:95)
	at org.molgenis.data.validation.QueryValidationRepositoryDecorator.findOne(QueryValidationRepositoryDecorator.java:47)
	at org.molgenis.data.support.QueryImpl.findOne(QueryImpl.java:108)
	at org.molgenis.security.user.UserDetailsService.loadUserByUsername(UserDetailsService.java:41)
	at org.molgenis.security.user.UserDetailsService$$FastClassBySpringCGLIB$$1483fd27.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:44)
	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:23)
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.security.user.UserDetailsService$$EnhancerBySpringCGLIB$$283ae4b2.loadUserByUsername(<generated>)
	at org.molgenis.jobs.JobExecutorTokenServiceImpl.createAuthorization(JobExecutorTokenServiceImpl.java:35)
	at org.molgenis.jobs.JobExecutorTokenServiceImpl.createToken(JobExecutorTokenServiceImpl.java:30)
	at org.molgenis.jobs.JobExecutor.runJob(JobExecutor.java:145)
	at org.molgenis.jobs.JobExecutor.executeScheduledJob(JobExecutor.java:77)
	at org.molgenis.jobs.JobExecutor$$FastClassBySpringCGLIB$$bc2e61ec.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.molgenis.security.core.runas.RunAsSystemAspect.runAsSystem(RunAsSystemAspect.java:44)
	at org.molgenis.security.core.runas.RunAsSystemAspect.aroundAdvice(RunAsSystemAspect.java:23)
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.molgenis.jobs.JobExecutor$$EnhancerBySpringCGLIB$$1188b621.executeScheduledJob(<generated>)
	at org.molgenis.jobs.schedule.MolgenisQuartzJob.execute(MolgenisQuartzJob.java:33)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.RuntimeException: Unexpected exception class [SQLException]
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:92)
	at org.molgenis.data.postgresql.PostgreSqlExceptionTranslator.doTranslate(PostgreSqlExceptionTranslator.java:61)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:620)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:657)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:688)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:751)
	at org.molgenis.data.postgresql.PostgreSqlRepository$1.getBatch(PostgreSqlRepository.java:416)
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:36)
	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:14)
	at org.molgenis.data.util.BatchingIterable$1.nextBatch(BatchingIterable.java:138)
	at org.molgenis.data.util.BatchingIterable$1.hasNext(BatchingIterable.java:58)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.molgenis.data.cache.l3.L3Cache$1.load(L3Cache.java:107)
	at org.molgenis.data.cache.l3.L3Cache$1.load(L3Cache.java:95)
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache$SingleLoader.load(CaffeinatedGuavaLoadingCache.java:136)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.lambda$new$0(BoundedLocalCache.java:3366)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:143)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2064)
	at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.getUnchecked(CaffeinatedGuavaLoadingCache.java:75)
	... 60 common frames omitted
```

Problem is probably here:
```
at org.molgenis.jobs.JobExecutorTokenServiceImpl.createAuthorization(JobExecutorTokenServiceImpl.java:35)
```
Still working on how to reproduce, possibly, run scheduled job at the time that the database is down.

### Expected behavior
Job fails, but my index keeps working

### Observed behavior
Pending index jobs, that never get scheduled (unless indexed using index manager)

**Comment by fdlk** [comment]
Tried out scheduling a simple job and then stopping postgres. When I bring postgres up again, everything recovers just fine.

**Comment by dennishendriksen** [comment]
@marikaris could you reproduce the problem when including https://github.com/molgenis/molgenis/pull/8314 so that we know what the underlying exception is?

**Comment by dennishendriksen** [comment]
@marikaris *bump*

**Comment by dennishendriksen** [comment]
cannot reproduce.
