### ISSUE TITLE
[c3p0] A PooledConnection that has already signalled a Connection error is still in use!

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis#8685]
### How to Reproduce
Inspect https://sentry.molgenis.org/sentry/molgenis/issues/4/events/153/. The event occured in 8.2.0.

### Expected behavior
No connection issues

### Observed behavior
```
[c3p0] A PooledConnection that has already signalled a Connection error is still in use!
at com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$WarnLogger.log(Slf4jMLog.java:220)
    at com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger.log(Slf4jMLog.java:247)
    at com.mchange.v2.c3p0.impl.NewPooledConnection.handleThrowable(NewPooledConnection.java:559)
    at com.mchange.v2.c3p0.impl.NewProxyConnection.getAutoCommit(NewProxyConnection.java:239)
    at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:278)
    at org.molgenis.data.postgresql.transaction.PostgreSqlTransactionManager.doBegin(PostgreSqlTransactionManager.java:84)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137)
```

**Comment by dennishendriksen** [comment]
Cause: cluster downtime
