### ISSUE TITLE
nl_NL locale causes tests to fail [v8.1]

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/molgenis#8955]
### How to Reproduce
1. Set locale to `nl_NL` (for MacOS: https://support.apple.com/guide/mac-help/mh26684/mac -> change primary language, then check if set correctly using `defaults read -g AppleLocale` on the commandline).
2. Run `mvn clean install` from molgenis directory.

Tested on MacOS Mojave using commit 80faca813e216ee1f70fe2e761c3e9a748daf69e (8.1.8).

### Expected behavior
Build success independent of system language.

### Observed behavior
```
15:42:38.714 [main] DEBUG org.springframework.test.context.cache - Spring test ApplicationContext cache statistics: [DefaultContextCache@4d9a46fc size = 2, maxSize = 32, parentContextCount = 0, hitCount = 5, missCount = 2]
15:42:38.720 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - After test method: context [DefaultTestContext@4b35c252 testClass = HttpLocaleResolverTest, testInstance = org.molgenis.web.i18n.HttpLocaleResolverTest@2f4d01b6, testMethod = testSetLocaleUnusedLanguage@HttpLocaleResolverTest, testException = java.lang.UnsupportedOperationException: Cannot set language to unsupported languageCode, mergedContextConfiguration = [MergedContextConfiguration@4477baf2 testClass = HttpLocaleResolverTest, locations = '{}', classes = '{class org.molgenis.web.i18n.HttpLocaleResolverTest$Config}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null].
15:42:38.724 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - After test class: context [DefaultTestContext@4b35c252 testClass = HttpLocaleResolverTest, testInstance = [null], testMethod = [null], testException = [null], mergedContextConfiguration = [MergedContextConfiguration@4477baf2 testClass = HttpLocaleResolverTest, locations = '{}', classes = '{class org.molgenis.web.i18n.HttpLocaleResolverTest$Config}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{}', contextCustomizers = set[[empty]], contextLoader = 'org.springframework.test.context.support.DelegatingSmartContextLoader', parent = [null]], attributes = map[[empty]]], class annotated with @DirtiesContext [false] with mode [null].
15:42:39.429 [main] INFO org.molgenis.web.exception.ExceptionHandlerUtils - 
org.springframework.web.context.request.async.AsyncRequestTimeoutException$MockitoMock$2013897616: null
15:42:39.438 [main] INFO org.molgenis.web.exception.ExceptionHandlerUtils - 
org.springframework.validation.BindException$MockitoMock$1868361626: null
15:42:39.452 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.460 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.515 [main] INFO org.molgenis.web.exception.ExceptionHandlerUtils - 
java.lang.Exception: message
	at org.molgenis.web.exception.ExceptionHandlerUtilsTest.testHandleExceptionHtmlRequest(ExceptionHandlerUtilsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
15:42:39.592 [main] INFO org.molgenis.web.exception.ExceptionHandlerUtils - 
org.mockito.codegen.Exception$MockitoMock$1901310170: null
	at class.method(file:1)
15:42:39.594 [main] INFO org.molgenis.web.exception.ExceptionHandlerUtils - 
java.lang.Exception: message
	at org.molgenis.web.exception.ExceptionHandlerUtilsTest.testHandleExceptionNonHtmlRequest(ExceptionHandlerUtilsTest.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
15:42:39.741 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.742 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.747 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.912 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.915 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.916 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.927 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.936 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
15:42:39.962 [main] WARN org.molgenis.i18n.properties.AllPropertiesMessageSource - ResourceBundle [l10n.web] not found for MessageSource: Can't find bundle for base name l10n.web, locale nl_NL
[ERROR] Tests run: 120, Failures: 2, Errors: 0, Skipped: 52, Time elapsed: 7.947 s <<< FAILURE! - in TestSuite
[ERROR] testBindException(org.molgenis.web.exception.SpringExceptionHandlerTest)  Time elapsed: 0.042 s  <<< FAILURE!
org.springframework.context.NoSuchMessageException: No message found under code 'org.molgenis.web.exception.ObjectError' for locale 'nl_NL'.
	at org.molgenis.web.exception.SpringExceptionHandlerTest.testBindException(SpringExceptionHandlerTest.java:146)

[ERROR] tearDownAfterMethod(org.molgenis.web.exception.SpringExceptionHandlerTest)  Time elapsed: 0.054 s  <<< FAILURE!
org.mockito.exceptions.misusing.UnnecessaryStubbingException: 

Unnecessary stubbings detected.
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at org.molgenis.web.exception.SpringExceptionHandlerTest.testBindException(SpringExceptionHandlerTest.java:143)
Please remove unnecessary stubbings or use 'lenient' strictness. More info: javadoc for UnnecessaryStubbingException class.
```

**Comment by fdlk** [comment]
Duplicates #8956
