### ISSUE TITLE
nl_NL locale causes tests to fail

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/molgenis#8956]
### How to Reproduce
1. Set locale to `nl_NL` (for MacOS: https://support.apple.com/guide/mac-help/mh26684/mac -> change primary language, then check if set correctly using `defaults read -g AppleLocale` on the commandline).
2. Run `mvn clean install` from molgenis directory.

Tested on MacOS Mojave using commit a524de0fd5d0a02f5c3e9eb27c29698d14f727af (8.3.5).

### Expected behavior
Build success independent of system language.

### Observed behavior
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.126 s <<< FAILURE! - in org.molgenis.api.metadata.v3.EntityTypeResponseMapperTest
[ERROR] toEntityTypeResponse  Time elapsed: 0.043 s  <<< ERROR!
org.mockito.exceptions.misusing.PotentialStubbingProblem: 

Strict stubbing argument mismatch. Please check:
 - this invocation of 'getLabel' method:
    entityType.getLabel("nl");
    -> at org.molgenis.api.metadata.v3.EntityTypeResponseMapperImpl.mapInternal(EntityTypeResponseMapperImpl.java:81)
 - has following stubbing(s) with different arguments:
    1. entityType.getLabel();
      -> at org.molgenis.api.metadata.v3.EntityTypeResponseMapperTest.toEntityTypeResponse(EntityTypeResponseMapperTest.java:103)
    2. entityType.getLabel("en");
      -> at org.molgenis.api.metadata.v3.EntityTypeResponseMapperTest.toEntityTypeResponse(EntityTypeResponseMapperTest.java:104)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at org.molgenis.api.metadata.v3.EntityTypeResponseMapperTest.toEntityTypeResponse(EntityTypeResponseMapperTest.java:147)

[INFO] Running org.molgenis.api.metadata.v3.MetadataApiJobServiceImplTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.192 s - in org.molgenis.api.metadata.v3.MetadataApiJobServiceImplTest
[INFO] Running org.molgenis.api.metadata.v3.AttributeResponseMapperTest
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.068 s <<< FAILURE! - in org.molgenis.api.metadata.v3.AttributeResponseMapperTest
[ERROR] mapAttribute  Time elapsed: 0.041 s  <<< ERROR!
org.mockito.exceptions.misusing.PotentialStubbingProblem: 

Strict stubbing argument mismatch. Please check:
 - this invocation of 'getLabel' method:
    attribute.getLabel("nl");
    -> at org.molgenis.api.metadata.v3.AttributeResponseMapperImpl.mapInternal(AttributeResponseMapperImpl.java:100)
 - has following stubbing(s) with different arguments:
    1. attribute.getLabel();
      -> at org.molgenis.api.metadata.v3.AttributeResponseMapperTest.mapAttribute(AttributeResponseMapperTest.java:122)
    2. attribute.getLabel("en");
      -> at org.molgenis.api.metadata.v3.AttributeResponseMapperTest.mapAttribute(AttributeResponseMapperTest.java:123)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at org.molgenis.api.metadata.v3.AttributeResponseMapperTest.mapAttribute(AttributeResponseMapperTest.java:170)
```

**Comment by svandenhoek** [comment]
Re-tested with `mvn clean install -T4 -fae`. Outside of `api-metadata`, it seems other modules do not have this issue. That is, `molgenis-platform-integration-tests` fails due to a non-related issue (`password authentication failed for user "postgres"`, which might be a configuration issue on my side) and 2 modules (`app` + `api-tests`) are being skipped. So for these it cannot be said conclusive yet.

```
[INFO] MOLGENIS ........................................... SUCCESS [  4.093 s]
[INFO] test ............................................... SUCCESS [  4.689 s]
[INFO] util ............................................... SUCCESS [ 16.604 s]
[INFO] security-core ...................................... SUCCESS [ 17.594 s]
[INFO] validation ......................................... SUCCESS [ 17.562 s]
[INFO] data ............................................... SUCCESS [ 36.920 s]
[INFO] settings ........................................... SUCCESS [ 29.365 s]
[INFO] data-security ...................................... SUCCESS [ 45.783 s]
[INFO] data-file .......................................... SUCCESS [ 30.915 s]
[INFO] core ............................................... SUCCESS [ 15.663 s]
[INFO] data-plugin ........................................ SUCCESS [ 25.514 s]
[INFO] api ................................................ SUCCESS [ 25.432 s]
[INFO] data-csv ........................................... SUCCESS [ 21.058 s]
[INFO] scripts-core ....................................... SUCCESS [ 32.432 s]
[INFO] js ................................................. SUCCESS [01:10 min]
[INFO] data-validation .................................... SUCCESS [ 32.629 s]
[INFO] i18n ............................................... SUCCESS [ 14.826 s]
[INFO] web ................................................ SUCCESS [ 28.016 s]
[INFO] security ........................................... SUCCESS [ 51.172 s]
[INFO] jobs ............................................... SUCCESS [ 33.974 s]
[INFO] data-excel ......................................... SUCCESS [ 30.909 s]
[INFO] data-i18n .......................................... SUCCESS [ 25.892 s]
[INFO] data-import ........................................ SUCCESS [ 47.454 s]
[INFO] amazon-bucket ...................................... SUCCESS [ 40.965 s]
[INFO] api-permissions .................................... SUCCESS [ 36.357 s]
[INFO] api-data ........................................... SUCCESS [01:06 min]
[INFO] data-cache ......................................... SUCCESS [ 44.410 s]
[INFO] data-index ......................................... SUCCESS [ 33.630 s]
[INFO] data-platform ...................................... SUCCESS [ 24.093 s]
[INFO] core-ui ............................................ SUCCESS [01:15 min]
[INFO] data-elasticsearch ................................. SUCCESS [01:08 min]
[INFO] ontology-core ...................................... SUCCESS [ 35.287 s]
[INFO] semantic-search .................................... SUCCESS [ 29.851 s]
[INFO] api-fair ........................................... SUCCESS [ 40.576 s]
[INFO] api-files .......................................... SUCCESS [ 16.715 s]
[INFO] api-identities ..................................... SUCCESS [ 42.828 s]
[INFO] api-metadata ....................................... FAILURE [ 45.285 s]
[INFO] api-metrics ........................................ SUCCESS [  7.497 s]
[INFO] app-manager ........................................ SUCCESS [ 46.141 s]
[INFO] data-vcf ........................................... SUCCESS [ 28.630 s]
[INFO] genomebrowser ...................................... SUCCESS [ 30.135 s]
[INFO] beacon ............................................. SUCCESS [ 25.686 s]
[INFO] data-migrate ....................................... SUCCESS [ 23.461 s]
[INFO] data-postgresql .................................... SUCCESS [ 32.833 s]
[INFO] bootstrap .......................................... SUCCESS [ 22.206 s]
[INFO] dataexplorer ....................................... SUCCESS [01:01 min]
[INFO] metrics ............................................ SUCCESS [ 12.085 s]
[INFO] python ............................................. SUCCESS [ 16.591 s]
[INFO] r .................................................. SUCCESS [ 26.593 s]
[INFO] searchall .......................................... SUCCESS [ 23.120 s]
[INFO] data-row-edit ...................................... SUCCESS [ 24.522 s]
[INFO] semantic-mapper .................................... SUCCESS [ 55.054 s]
[INFO] ontology ........................................... SUCCESS [ 51.996 s]
[INFO] questionnaires ..................................... SUCCESS [ 40.982 s]
[INFO] scripts ............................................ SUCCESS [ 34.074 s]
[INFO] file-ingester ...................................... SUCCESS [ 32.449 s]
[INFO] data-icd10 ......................................... SUCCESS [ 19.238 s]
[INFO] settings-ui ........................................ SUCCESS [ 29.537 s]
[INFO] swagger ............................................ SUCCESS [ 12.389 s]
[INFO] navigator .......................................... SUCCESS [ 56.697 s]
[INFO] metadata-manager ................................... SUCCESS [ 51.133 s]
[INFO] one-click-importer ................................. SUCCESS [ 36.234 s]
[INFO] security-ui ........................................ SUCCESS [ 26.671 s]
[INFO] app ................................................ SKIPPED
[INFO] api-tests .......................................... SKIPPED
[INFO] platform-integration-tests ......................... FAILURE [ 13.870 s]
```

**Comment by svandenhoek** [comment]
Additional tests using `mvn test -f molgenis-api-metadata/` combined with different locales (checked with `defaults read -g AppleLocale` before running maven):
| locale | success/fail |
| -------- | -------- |
| en_NL | success |
| nl_NL | fails |
| de_NL | fails |
| nl_US | fails
