### ISSUE TITLE
Problem with Python module

### ISSUE THREAD

**Issue by holubp** [molgenis/molgenis#8966]
### How to Reproduce
Get BBMRI-ERIC Directory data quality check script:
git clone https://github.com/djvanenckevort/molgenis-app-bbmri-eric-scripts.git
pip install molgenis-py-client
$ ./data-check.py --purge-cache directory --disable-checks-all-remote

(this is a version of the code which used the original molgenis.py code -- upgraded to the last version of the PIP-based module)

### Expected behavior

Should succeed.

### Observed behavior

$ ./data-check.py --purge-cache directory --disable-checks-all-remote
Traceback (most recent call last):
  File "./data-check.py", line 388, in <module>
    dir = Directory()
  File "./data-check.py", line 161, in __init__
    self.biobanks = session.get("eu_bbmri_eric_biobanks", num=2000, expand=['contact','collections','country'])
  File "/usr/lib/python3.6/site-packages/molgenis/client.py", line 139, in get
    expand=expand)
  File "/usr/lib/python3.6/site-packages/molgenis/client.py", line 166, in _get_batch
    url = self._build_api_url(self._url + "v2/" + quote_plus(entity), possible_options)
  File "/usr/lib/python3.6/site-packages/molgenis/client.py", line 375, in _build_api_url
    attrs = self._merge_attrs(option_value)
  File "/usr/lib/python3.6/site-packages/molgenis/client.py", line 350, in _merge_attrs
    expands = self._split_if_not_none(attr_expands[1])
  File "/usr/lib/python3.6/site-packages/molgenis/client.py", line 337, in _split_if_not_none
    return operator.split(',') if operator else []
AttributeError: 'list' object has no attribute 'split'

**Comment by fdlk** [comment]
Hi @holubp what is your python version?

**Comment by tommydeboer** [comment]
Hi @holubp. The problem lies in the query `session.get("eu_bbmri_eric_biobanks", num=2000, expand=['contact','collections','country'])`. The `expand` parameter expects a comma-separated string instead of a list.

I will update the method's documentation because it has a wrong example.
