### ISSUE TITLE
UnknownEntityException when adding an entity with a reference to an existing FileMeta with REST API v2

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#9069]
### How to Reproduce
1. In the MetadataManager, create an EntityType with an id attribute `id` and a file attribute `file`.
2. Go to the FileMeta table and copy an identifier of one of the files there.
3. Login to the REST API and execute the following request:

```POST <yourserver>/api/v2/<your_entitytype_id>```
```json
{"entities": [
    {
        "id": "test",
        "file": "<your_file_id>"
    }
]}
```

### Expected behavior
The entity is added without problems.

### Observed behavior
```json
{
    "errors": [
        {
            "message": "Unknown entity 'test' of type '<your_entitytype_id>'.",
            "code": "D02a"
        }
    ]
}
```

**Comment by fdlk** [comment]
Do you have a stacktrace perhaps?

**Comment by tommydeboer** [comment]
@fdlk Here you go!
```
2020-08-06_07:31:32.233 [http-nio-8080-exec-5] WARN  o.m.w.e.ExceptionHandlerFacadeImpl - 
org.molgenis.data.UnknownEntityException: type:aaaac46cvg4o6ascvqmqabqaae id:test2 attribute:null
at org.molgenis.api.data.RestService.convertFile(RestService.java:230)
at org.molgenis.api.data.RestService.toEntityValue(RestService.java:153)
at org.molgenis.api.data.RestService.toEntity(RestService.java:95)
at org.molgenis.api.data.v2.RestControllerV2.lambda$createEntities$1(RestControllerV2.java:333)
...
```

**Comment by fdlk** [comment]
I think this got introduced in 0847e50. `EntityType entityType = attr.getEntity();` should probably be `attr.getRefEntity()` instead. (Though I cannot oversee the consequences for all other usages)

**Comment by bartcharbon** [comment]
I think the getEntity is correct.

The code path in which the exception occured is meant for:
`If an entity is updated and no new file is passed, use the old file value`
So I think the real issue is that you end up in that branch of code.

I believe the supported behaviour is:
- create/POST a new entity with an actual file (multipart thingy)
- update an entity with a new file (multipart thingy)
- update an entity without changing the file -> you'll end up in this code path and the old filestore reference value is looked up (that's where the getEntity is needed for) and used.

So the question is:
- do we need to support creating an entity this way, or:
- should we make sure you don't end up here and throw a proper exception

**Comment by bartcharbon** [comment]
@mswertz Can you decide if this:
- should be fixed/implemented in v2 api
- should work in the new data api (which is currently missing batch functionality, which is the reason v2 is still used for this)
- doesn't need to be fixed/implemented (works as intended?)

**Comment by mswertz** [comment]
I think indeed you don't want to end up here; and instead have put/post multi-part thingy. Does that work in v2? And should indeed work in v3 -> we are back to batch which in my mind needs some discussion for now make sure it works in existing APIs.
