### ISSUE TITLE
Python API delete_list not working with cascadeDelete

### ISSUE THREAD

**Issue by ellendejong** [molgenis/molgenis#9109]
### How to Reproduce

1. Start a Molgenis 8.3.10 instance.
2. Upload test data [it_emx_onetomany (2).xlsx](https://github.com/molgenis/molgenis/files/5340944/it_emx_onetomany.2.xlsx)
(found it in https://github.com/molgenis/molgenis/issues/8447)
4. Using the metadata manager plugin to enable cascade delete for Author.books
5. Use python API to delete multiple list items, using similar code as:

```
from molgenis import client as molgenis
api = molgenis.Session(url="https://molgenis.mydomain.example/api/")
api.login("username", "password")
api.delete_list(entity="it_emx_onetomany_author", entities=["hemingway","orwell"])
```

### Expected behavior
All provided author ids are removed from entity _it_emx_onetomany_author_ and Books with author in entity _it_emx_onetomany_book_ are removed as well.

### Observed behavior
Response code 400, _Value 'hemingway' for attribute 'authorId' is referenced by entity 'it_emx_onetomany_book'_.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/molgenis/client.py", line 268, in delete_list
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mol8.trecodedevs.bioinf.prinsesmaximacentrum.nl/api/v2/it_emx_onetomany_author
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/molgenis/client.py", line 270, in delete_list
    self._raise_exception(ex)
  File "/usr/local/lib/python3.8/site-packages/molgenis/client.py", line 408, in _raise_exception
    raise MolgenisRequestError(error_msg, ex.response)
molgenis.client.MolgenisRequestError: ("400 Client Error: Bad Request for url: https://mol8.trecodedevs.bioinf.prinsesmaximacentrum.nl/api/v2/it_emx_onetomany_author: Value 'hemingway' for attribute 'authorId' is referenced by entity 'it_emx_onetomany_book'.", <Response [400]>)
```

### Additional Information
molgenis-py-client 2.3.0
Python 3.8

Single delete using api.delete() and a single author id does work and returns 204 response code.
`api.delete(entity="it_emx_onetomany_author", id_="orwell")
`

**Comment by tommydeboer** [comment]
Thanks for the bug report @ellendejong. I did some digging around and found that the issue is with MOLGENIS. I took the liberty of rewriting your issue a bit to reflect that, hope you don't mind :)

**Comment by ellendejong** [comment]
Good to hear. Ofcourse I don't mind, thanks a lot.
