### ISSUE TITLE
Download job broken

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#9225]
### How to Reproduce
1. Download an entity type in the Data Explorer 2

### Expected behavior
Download is prepared and file can be downloaded after a while.

### Observed behavior
```Download failed: An error occured while downloading your selection. (NAV01)```

Logs:
```
org.molgenis.navigator.download.exception.DownloadFailedException: org.molgenis.data.export.exception.EmxExportException: An error occured while downloading your selection.
	at org.molgenis.navigator.download.job.ResourceDownloadService.download(ResourceDownloadService.java:60)
	at org.molgenis.navigator.download.job.ResourceDownloadConfig$1.lambda$createJob$0(ResourceDownloadConfig.java:38)
	at org.molgenis.jobs.JobExecutionTemplate.tryCall(JobExecutionTemplate.java:53)
	at org.molgenis.jobs.JobExecutionTemplate.lambda$call$0(JobExecutionTemplate.java:29)
	at org.molgenis.jobs.JobExecutionTemplate.runWithContext(JobExecutionTemplate.java:39)
	at org.molgenis.jobs.JobExecutionTemplate.call(JobExecutionTemplate.java:29)
	at org.molgenis.jobs.JobExecutor.runJob(JobExecutor.java:185)
	at org.molgenis.jobs.JobExecutor.lambda$submit$0(JobExecutor.java:126)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.molgenis.data.export.exception.EmxExportException: java.nio.file.NoSuchFileException: /home/molgenis/data/filestore/2021-04-27_09_08_34.527.xlsx
```

**Comment by tommydeboer** [comment]
Might be related to #9222 since in both cases the file can't be found in the filestore

**Comment by tommydeboer** [comment]
Can't reproduce this locally so I think its a problem with the filestore on https://latest.test.molgenis.org

**Comment by tommydeboer** [comment]
Confirmed as a problem on the test server
