### ISSUE TITLE
Occasional NPEs when an entity is updated and read simultaneously

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis#9321]
### How to Reproduce
1. Import the BBMRI ERIC model and at least the PL node
2. Run the following script until you get one or more errors:
```javascript
const axios = require("axios");
const biobank = require("./biobank.json");

const molgenisApi = axios.create({
  baseURL: "http://localhost/api/v2",
  timeout: 10000,
});

async function login() {
  const responseLogin = await axios.post("http://localhost/api/v1/login", {
    username: "admin",
    password: "admin",
  });
  if (responseLogin.status !== 200 || !responseLogin.data.token)
    throw new Error(`Login failed`);
  molgenisApi.defaults.headers["x-molgenis-token"] = responseLogin.data.token;
  console.log(new Date(), "Logged");
}

async function getBiobank(requestId) {
  await molgenisApi
    .get(`/eu_bbmri_eric_PL_biobanks/${biobank.id}`)
    .catch((e) =>
      console.error(
        new Date(),
        `Request getBiobank #${requestId} errors: `,
        e.toString()
      )
    );
}

async function updateBiobank() {
  await molgenisApi
    .put("eu_bbmri_eric_PL_biobanks", { entities: [biobank] })
    .catch((e) =>
      console.error(
        new Date(),
        "Biobank update errors: ",
        e.toString()
      )
    );
}

async function sendRequests(request, iterations, delay = 0) {
  for (let i = 0; i <= iterations; i++) {
    request(i);
    console.log(new Date(), `Sending ${request.name} request #${i}`);
    await new Promise((res) => setTimeout(res, delay));
  }
}

(async function () {
  await login();
  sendRequests(updateBiobank, 50, 200);
  sendRequests(getBiobank, 100, 100);
})();
```

Ask me for the `biobank.json` file :) 

### Expected behavior
All requests finish succesfully.

### Observed behavior
Occasionally a request fails with a `NullPointerException`:

```
molgenis_1       | java.lang.NullPointerException: null
molgenis_1       | 	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapValue(PostgreSqlEntityFactory.java:105)
molgenis_1       | 	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapValue(PostgreSqlEntityFactory.java:114)
molgenis_1       | 	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapValue(PostgreSqlEntityFactory.java:89)
molgenis_1       | 	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapRow(PostgreSqlEntityFactory.java:73)
molgenis_1       | 	at org.molgenis.data.postgresql.PostgreSqlEntityFactory$EntityMapper.mapRow(PostgreSqlEntityFactory.java:51)
molgenis_1       | 	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
molgenis_1       | 	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
molgenis_1       | 	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679)
molgenis_1       | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
molgenis_1       | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
molgenis_1       | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
molgenis_1       | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:712)
molgenis_1       | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:763)
molgenis_1       | 	at org.molgenis.data.postgresql.PostgreSqlRepository$1.getBatch(PostgreSqlRepository.java:464)
molgenis_1       | 	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:29)
molgenis_1       | 	at org.molgenis.data.support.BatchingQueryResult.getBatch(BatchingQueryResult.java:13)
molgenis_1       | 	at org.molgenis.data.util.BatchingIterable$1.nextBatch(BatchingIterable.java:106)
molgenis_1       | 	at org.molgenis.data.util.BatchingIterable$1.hasNext(BatchingIterable.java:48)
molgenis_1       | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
molgenis_1       | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
molgenis_1       | 	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1338)
molgenis_1       | 	at org.molgenis.data.support.AbstractRepository.findAllBatched(AbstractRepository.java:109)
molgenis_1       | 	at org.molgenis.data.support.AbstractRepository.lambda$findAll$1(AbstractRepository.java:100)
molgenis_1       | 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
molgenis_1       | 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
molgenis_1       | 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
molgenis_1       | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
molgenis_1       | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
molgenis_1       | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
molgenis_1       | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
molgenis_1       | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
molgenis_1       | 	at org.molgenis.data.cache.l2.L2Cache$1.loadAll(L2Cache.java:246)
molgenis_1       | 	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache$BulkLoader.loadAll(CaffeinatedGuavaLoadingCache.java:179)
molgenis_1       | 	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newBulkMappingFunction$3(LocalLoadingCache.java:162)
molgenis_1       | 	at com.github.benmanes.caffeine.cache.LocalManualCache.bulkLoad(LocalManualCache.java:102)
molgenis_1       | 	at com.github.benmanes.caffeine.cache.LocalManualCache.getAll(LocalManualCache.java:89)
molgenis_1       | 	at com.github.benmanes.caffeine.cache.LocalLoadingCache.getAll(LocalLoadingCache.java:62)
molgenis_1       | 	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.getAll(CaffeinatedGuavaLoadingCache.java:91)
molgenis_1       | 	at org.molgenis.data.cache.l2.L2Cache.getBatch(L2Cache.java:148)
molgenis_1       | 	at org.molgenis.data.cache.l2.L2CacheRepositoryDecorator.findAllCache(L2CacheRepositoryDecorator.java:149)
molgenis_1       | 	at org.molgenis.data.cache.l2.L2CacheRepositoryDecorator.lambda$findAll$3(L2CacheRepositoryDecorator.java:89)
molgenis_1       | 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
molgenis_1       | 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
molgenis_1       | 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
molgenis_1       | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
molgenis_1       | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
molgenis_1       | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
molgenis_1       | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
molgenis_1       | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
molgenis_1       | 	at org.molgenis.data.EntityManagerImpl.resolveReferences(EntityManagerImpl.java:196)
molgenis_1       | 	at org.molgenis.data.EntityManagerImpl.resolveReferences(EntityManagerImpl.java:116)
molgenis_1       | 	at org.molgenis.data.EntityReferenceResolverDecorator.resolveEntityReferences(EntityReferenceResolverDecorator.java:89)
molgenis_1       | 	at org.molgenis.data.EntityReferenceResolverDecorator.findOneById(EntityReferenceResolverDecorator.java:67)
molgenis_1       | 	at org.molgenis.data.AbstractRepositoryDecorator.findOneById(AbstractRepositoryDecorator.java:98)
molgenis_1       | 	at org.molgenis.data.AbstractRepositoryDecorator.findOneById(AbstractRepositoryDecorator.java:98)
molgenis_1       | 	at org.molgenis.data.AbstractRepositoryDecorator.findOneById(AbstractRepositoryDecorator.java:98)
molgenis_1       | 	at org.molgenis.data.security.RepositorySecurityDecorator.findOneById(RepositorySecurityDecorator.java:91)
molgenis_1       | 	at org.molgenis.data.transaction.TransactionalRepositoryDecorator.findOneById(TransactionalRepositoryDecorator.java:116)
molgenis_1       | 	at org.molgenis.data.AbstractRepositoryDecorator.findOneById(AbstractRepositoryDecorator.java:98)
molgenis_1       | 	at org.molgenis.data.validation.QueryValidationRepositoryDecorator.findOneById(QueryValidationRepositoryDecorator.java:63)
molgenis_1       | 	at org.molgenis.data.support.DataServiceImpl.findOneById(DataServiceImpl.java:231)
molgenis_1       | 	at org.molgenis.data.support.DataServiceImpl$$FastClassBySpringCGLIB$$2e5f77dc.invoke(<generated>)
molgenis_1       | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
molgenis_1       | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
molgenis_1       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
molgenis_1       | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
molgenis_1       | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
molgenis_1       | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
molgenis_1       | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
molgenis_1       | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
molgenis_1       | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
molgenis_1       | 	at org.molgenis.data.support.DataServiceImpl$$EnhancerBySpringCGLIB$$ab0b94eb.findOneById(<generated>)
molgenis_1       | 	at org.molgenis.api.data.v2.RestControllerV2.getEntityResponse(RestControllerV2.java:226)
molgenis_1       | 	at org.molgenis.api.data.v2.RestControllerV2.retrieveEntity(RestControllerV2.java:195)
```

**Comment by tommydeboer** [comment]
@fdlk and I looked at it and we suspect it has something to do with the metadata administration and concurrency. Because of all the updates, the L2 cache redirects to the database. When the database rows are mapped to objects, one of the reference attributes is null because it is not present in the metadata (we think). More analysis is needed 🧐

**Comment by tommydeboer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Null pointer exception BBMRI.pl](https://trello.com/c/2FzGhJyS/237-null-pointer-exception-bbmripl)
